"""Run with isolated ui-audit-server.cjs:4107 and Next production server:3107."""
from pathlib import Path
from playwright.sync_api import sync_playwright
import json
import re
failures = []

with sync_playwright() as p:
    browser = p.chromium.launch(channel="msedge", headless=True)
    context = browser.new_context(viewport={"width": 1440, "height": 1000}, timezone_id="Asia/Bangkok")
    context.set_default_timeout(12000)
    context.route('**/*', lambda route: route.continue_() if route.request.url.startswith(('http://localhost:', 'http://127.0.0.1:', 'data:')) else route.abort())
    def proxy(route):
        response = route.fetch(url=route.request.url.replace("http://localhost:3107/api", "http://127.0.0.1:4107"))
        route.fulfill(response=response)
    context.route("http://localhost:3107/api/**", proxy)
    admin_auth = context.request.post("http://127.0.0.1:4107/auth/login", data={"username": "admin", "password": "password"}).json()
    context.request.post("http://127.0.0.1:4107/bookings/reset", headers={"Authorization": "Bearer " + admin_auth['access_token']})
    auth = context.request.post("http://127.0.0.1:4107/auth/login", data={"username": "testuser", "password": "password"}).json()
    created = context.request.post("http://127.0.0.1:4107/bookings", headers={"Authorization": "Bearer " + auth["access_token"]}, data={"courtId": 1, "date": "2026-09-17", "startTime": "18:00:00"})
    print('fixture booking HTTP', created.status)
    page = context.new_page()
    page.clock.set_fixed_time("2026-09-17T18:00:00+07:00")
    page.goto("http://localhost:3107/login")
    page.wait_for_load_state("networkidle")
    page.locator('input[type=text]').fill('admin')
    page.locator('input[type=password]').fill('password')
    page.get_by_role('button', name=re.compile('Login')).click()
    page.wait_for_url('**/dashboard')
    page.wait_for_load_state('networkidle')
    page.get_by_text('Test Student', exact=True).click()
    page.locator('svg[width="200"]').screenshot(path=str(Path(__file__).with_name('ui-audit-qr.png')))
    user_context = browser.new_context(viewport={"width": 1440, "height": 1000}, timezone_id="Asia/Bangkok")
    user_context.set_default_timeout(12000)
    user_context.route('**/*', lambda route: route.continue_() if route.request.url.startswith(('http://localhost:', 'http://127.0.0.1:', 'data:')) else route.abort())
    user_context.route("http://localhost:3107/api/**", proxy)
    user = user_context.new_page()
    user.clock.set_fixed_time("2026-09-17T18:00:00+07:00")
    user.goto('http://localhost:3107/login')
    user.wait_for_load_state('networkidle')
    user.locator('input[type=text]').fill('testuser')
    user.locator('input[type=password]').fill('password')
    user.get_by_role('button', name=re.compile('Login')).click()
    user.wait_for_url('**/dashboard')
    user.goto('http://localhost:3107/scan')
    user.wait_for_load_state('networkidle')
    user.get_by_text('Scan an Image File', exact=True).click()
    user.locator('input[type=file]').set_input_files(str(Path(__file__).with_name('ui-audit-qr.png')))
    user.wait_for_url('**/dashboard', timeout=15000)
    print('PASS: User decoded Admin QR image and returned to dashboard')
    page.get_by_text('01:00:00', exact=True).wait_for(timeout=15000)
    print('PASS: Open Admin popup updates after user QR check-in')
    page.screenshot(path=str(Path(__file__).with_name('ui-audit-admin.png')), full_page=True)
    page.clock.set_fixed_time('2026-09-17T18:00:05+07:00')
    page.get_by_text('00:59:55', exact=True).wait_for()
    print('PASS: Countdown advances toward time_out')
    for path in ('/booking', '/scan'):
        page.goto('http://localhost:3107' + path)
        page.wait_for_url('**/dashboard')
        print('PASS: Admin redirect', path)
    for name, target in [('admin', page), ('user', user)]:
        target.goto('http://localhost:3107/dashboard')
        target.wait_for_load_state('networkidle')
        print('Theme buttons', name, target.locator('button').all_text_contents())
        # Icon font is external and blocked in this audit; its fallback text overlaps.
        # Exercise the accessible keyboard path without forcing a pointer click.
        menu = target.get_by_role('button', name='Menu', exact=True)
        menu.focus()
        menu.press('Enter')
        switch = target.locator('input[type=checkbox]')
        switch.wait_for(state='attached')
        if switch.is_checked():
            switch.focus()
            switch.press('Space')
        target.wait_for_function("!document.documentElement.classList.contains('dark')")
        light = target.locator('body').evaluate('(e)=>getComputedStyle(e).backgroundColor')
        switch.focus()
        switch.press('Space')
        if not switch.is_checked():
            switch.press('Space')
        target.wait_for_function("document.documentElement.classList.contains('dark')")
        try:
            target.wait_for_function("getComputedStyle(document.body).backgroundColor !== '" + light + "'", timeout=2000)
        except Exception:
            failures.append(name + ': body background unchanged in dark mode')
        dark = target.locator('body').evaluate('(e)=>getComputedStyle(e).backgroundColor')
        print('Theme', name, light, '->', dark)
        target.screenshot(path=str(Path(__file__).with_name('ui-audit-' + name + '-dark.png')), full_page=True)
        target.set_viewport_size({'width': 390, 'height': 844})
        print('Mobile overflow', name, target.evaluate('document.documentElement.scrollWidth > window.innerWidth'))
        target.screenshot(path=str(Path(__file__).with_name('ui-audit-' + name + '-mobile.png')), full_page=True)
    browser.close()
print('UI audit failures:', failures)
raise SystemExit(1 if failures else 0)
