const assert=require('node:assert/strict'),mysql=require('../backend/node_modules/mysql2/promise'),fs=require('node:fs'),{execFileSync}=require('node:child_process');
const root='http://127.0.0.1:4001',volume='badminton_qa_20260928_mysql_data',date=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok'}).format(new Date()),stamp=new Date().toISOString().replace(/[:.]/g,'-'),out=`C:/GuisTee/Project_Y3/Book-a-Badminton/Book-a-Badminton_Court/testing/evidence/qa_remaining_probe_results_${stamp}.json`;
const ids=Array.from({length:8},(_,i)=>String(Date.now()).slice(-7)+String(i));let db,tokens=[],owned=[],results=[];
async function req(method,path,body,token){const r=await fetch(root+path,{method,headers:{...(body===undefined?{}:{'content-type':'application/json'}),...(token?{authorization:'Bearer '+token}:{})},body:body===undefined?undefined:JSON.stringify(body)});let data;try{data=await r.json()}catch{data=null}return{status:r.status,data}}
const rows=async(q,p=[]) => (await db.query(q,p))[0];
async function check(id,fn){try{await db.query('DELETE FROM Booking WHERE stu_id IN ('+ids.map(()=>'?').join(',')+')',ids);for(const uid of ids)await db.query('UPDATE users_students SET quota=1 WHERE stu_id=?',[uid]);const actual=await fn();results.push({id,status:'pass',actual})}catch(e){results.push({id,status:'fail',actual:String(e.message).slice(0,500)})}console.log(id,results.at(-1).status,results.at(-1).actual)}
async function main(){try{const mounts=JSON.parse(execFileSync('docker',['inspect','badminton_mysql','--format','{{json .Mounts}}'],{encoding:'utf8'}));assert.ok(mounts.some(m=>m.Type==='volume'&&m.Name===volume&&m.Destination==='/var/lib/mysql'));db=await mysql.createConnection({host:'127.0.0.1',port:13306,user:'badminton_user',password:'password',database:'badminton_db',dateStrings:true});assert.equal((await rows('SELECT COUNT(*) n FROM Booking'))[0].n,0,'booking table nonempty; abort');
for(let i=0;i<ids.length;i++){const id=ids[i],name=`qa_now_${id}`;assert.equal((await rows('SELECT COUNT(*) n FROM users_students WHERE stu_id=? OR username=?',[id,name]))[0].n,0,'fixture collision');const r=await req('POST','/auth/register',{studentId:id,username:name,name:`QA ${id}`,email:`${id}@kmitl.ac.th`,phone:'0812345678',major:'IT',year:3,password:'QA-only-123!'});assert.equal(r.status,201,JSON.stringify(r.data));tokens.push(r.data.access_token)}
for(const id of ids){await db.query('UPDATE users_students SET quota=1 WHERE stu_id=?',[id])}
async function booking(i,court=1,time='18:00'){return req('POST','/bookings',{courtId:court,date,startTime:time},tokens[i])}
async function seed(i,{court=1,status='PENDING',day=date,start='21:00:00',end='22:00:00'}={}){const r=await rows("INSERT INTO Booking(stu_id,court,booking_date,time_in,time_out,status,admin_id,created_at,updated_at) VALUES(?,?,?,?,?,?,'A001',NOW(),NOW())",[ids[i],court,day,start,end,status]);owned.push(r.insertId);return r.insertId}
await check('fresh_book_quota_active',async()=>{let r=await booking(0,1,'18:00');assert.equal(r.status,201,JSON.stringify(r.data));let second=await booking(0,2,'20:00');assert.equal(second.status,400);assert.match(second.data.message,/active booking/);return `first=${r.status}, second=${second.status}: ${second.data.message}`});
await check('fresh_book_adjacent',async()=>{let a=await booking(0,1,'18:00');assert.equal(a.status,201);let rows1=await rows('SELECT * FROM Booking WHERE stu_id=?',[ids[0]]);await db.query("UPDATE Booking SET status='COMPLETED' WHERE booking_id=?",[rows1[0].booking_id]);let b=await booking(1,1,'19:00');assert.equal(b.status,201,JSON.stringify(b.data));return '18:00 and 19:00 adjacent bookings both 201 (first completed)'});
await check('fresh_book_overlap_partial',async()=>{let a=await booking(0,1,'18:00');assert.equal(a.status,201);let b=await booking(1,1,'18:30');assert.equal(b.status,400);assert.match(b.data.message,/booked|overlap/i);return `18:00=${a.status},18:30=${b.status} ${b.data.message}`});
await check('fresh_book_samecourt_race',async()=>{let [a,b]=await Promise.all([booking(0,1,'20:00'),booking(1,1,'20:00')]);assert.deepEqual([a.status,b.status].sort(),[201,400]);return `simultaneous ${a.status}/${b.status}`});
await check('fresh_book_cancel_rebook',async()=>{let r=await booking(0,1,'18:00');assert.equal(r.status,201);let c=await req('POST',`/bookings/${r.data.booking_id}/cancel`,{},tokens[0]);assert.equal(c.status,201,JSON.stringify(c.data));let b=await booking(0,1,'18:00');assert.equal(b.status,201,JSON.stringify(b.data));return `book/cancel/rebook=${r.status}/${c.status}/${b.status}`});
await check('fresh_book_own_read',async()=>{let r=await booking(0,3,'21:00');assert.equal(r.status,201);let m=await req('GET','/bookings/me',undefined,tokens[1]);assert.equal(m.status,200);assert.ok(Array.isArray(m.data));assert.ok(m.data.every(x=>x.stu_id===ids[1]||x.student_id===ids[1]));return `other student GET /bookings/me rows=${m.data.length}`});
await check('fresh_checkin_owner_and_role',async()=>{const id=await seed(0,{court:2,status:'PENDING'});let other=await req('POST',`/bookings/${id}/check-in`,{courtId:2},tokens[1]);assert.equal(other.status,400,JSON.stringify(other.data));return `non-owner check-in HTTP ${other.status}: ${other.data.message}`});
await check('fresh_admin_finish_state',async()=>{const adm=await req('POST','/auth/login',{username:'admin',password:'password'});assert.equal(adm.status,201);const id=await seed(0,{status:'CHECKED_IN'});let r=await req('POST',`/bookings/${id}/finish`,{},adm.data.access_token);assert.equal(r.status,201,JSON.stringify(r.data));const dbrow=(await rows('SELECT status FROM Booking WHERE booking_id=?',[id]))[0];assert.equal(dbrow.status,'COMPLETED');return `finish API=${r.status}, DB=${dbrow.status}`});
await check('fresh_admin_bad_id',async()=>{const adm=await req('POST','/auth/login',{username:'admin',password:'password'});let r=await req('POST','/bookings/not-an-id/finish',{},adm.data.access_token);assert.ok(r.status>=400&&r.status<500,`bad booking ID HTTP${r.status}`);return `malformed id HTTP ${r.status}: ${r.data.message}`});
await check('fresh_forbidden_admin_collection',async()=>{let r=await req('POST','/users/admin',{admin_id:'A951',username:`qa_now_admin_${Date.now()}`,name:'QA admin',password:'x'},tokens[0]);assert.ok(r.status>=400&&r.status<500,`student admin-create HTTP${r.status}`);return `student POST /users/admin HTTP ${r.status}`});
await check('fresh_missing_password_admin_create',async()=>{const adm=await req('POST','/auth/login',{username:'admin',password:'password'});let name=`qa_now_nopw_${Date.now()}`;let r=await req('POST','/users/admin',{admin_id:'A952',username:name,name:'No pw'},adm.data.access_token);if(r.status===201)owned.push(['admin',name]);assert.ok(r.status>=400&&r.status<500,`missing password HTTP${r.status}`);return `missing password HTTP ${r.status}`});
await check('fresh_delete_user_booking_fk',async()=>{const id=await seed(0,{status:'COMPLETED'});let adm=(await req('POST','/auth/login',{username:'admin',password:'password'})).data.access_token;let r=await req('DELETE',`/users/${ids[0]}`,undefined,adm);assert.ok(r.status>=400&&r.status<500,`delete with booking HTTP${r.status}`);let n=(await rows('SELECT COUNT(*) n FROM Booking WHERE booking_id=?',[id]))[0].n;assert.equal(n,1);return `delete HTTP ${r.status}, booking preserved`});
await check('fresh_status_extra_payload',async()=>{let r=await req('POST','/bookings',{courtId:1,date,startTime:'22:00',status:'COMPLETED',admin_id:'A001'},tokens[2]);assert.equal(r.status,201,JSON.stringify(r.data));let b=(await rows('SELECT status,admin_id FROM Booking WHERE booking_id=?',[r.data.booking_id]))[0];owned.push(r.data.booking_id);assert.equal(b.status,'PENDING');assert.notEqual(b.admin_id,'A001');return `HTTP${r.status}, ignored status/admin_id; DB ${b.status}, admin=${b.admin_id}`});
}finally{if(db){try{for(const x of owned){if(Array.isArray(x))await db.query('DELETE FROM admin WHERE username=?',[x[1]]);else await db.query('DELETE FROM Booking WHERE booking_id=?',[x])}await db.query('DELETE FROM Booking WHERE stu_id IN ('+ids.map(()=>'?').join(',')+')',ids);await db.query('DELETE FROM users_students WHERE stu_id IN ('+ids.map(()=>'?').join(',')+')',ids);const left=await rows('SELECT COUNT(*) bookings FROM Booking');console.log('CLEANUP',JSON.stringify(left[0]));const image=execFileSync('docker',['inspect','badminton_qa_backend','--format','{{.Image}}'],{encoding:'utf8'}).trim();fs.writeFileSync(out,JSON.stringify({environment:{commit:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),image,volume,api:root,date,started:new Date().toISOString(),cleanup:'only unique QA student IDs/booking IDs/admin username fixtures'},results},null,2));console.log('EVIDENCE',out)}finally{await db.end()}}}}
main().catch(e=>{console.error('ABORT',e.stack);process.exitCode=1});