const assert=require('node:assert/strict'), mysql=require('../backend/node_modules/mysql2/promise'), fs=require('node:fs'),{execFileSync}=require('node:child_process');
const root='http://127.0.0.1:4001',volume='badminton_qa_20260928_mysql_data',run=new Date().toISOString(),stamp=run.replace(/[:.]/g,'-'),out=`testing/evidence/qa_fresh_auth_cancel_${stamp}.json`,results=[];let db;const ids=[];
async function req(method,path,data,token){const r=await fetch(root+path,{method,headers:{...(data===undefined?{}:{'content-type':'application/json'}),...(token?{authorization:`Bearer ${token}`}:{})},body:data===undefined?undefined:JSON.stringify(data)});return{status:r.status,data:await r.json().catch(()=>null)}}
async function sql(q,p=[]){return(await db.query(q,p))[0]}
async function runCase(id,fn){try{const actual=await fn();results.push({id,status:'PASS',actual})}catch(e){results.push({id,status:'FAIL',actual:String(e.message).slice(0,500)})}}
async function create(prefix){const id=String(76000000+Number(String(Date.now()).slice(-5))+ids.length);const username=`${prefix}${id}`;assert.equal((await sql('SELECT COUNT(*) n FROM users_students WHERE stu_id=? OR username=?',[id,username]))[0].n,0);const r=await req('POST','/auth/register',{studentId:id,username,name:`QA ${id}`,email:`${username}@kmitl.ac.th`,phone:'0812345678',major:'IT',year:3,password:'QA-only-123!'});assert.equal(r.status,201,JSON.stringify(r.data));ids.push(id);return{id,username,token:r.data.access_token}}
async function main(){try{const mounts=JSON.parse(execFileSync('docker',['inspect','badminton_mysql','--format','{{json .Mounts}}'],{encoding:'utf8'}));assert.ok(mounts.some(x=>x.Type==='volume'&&x.Name===volume&&x.Destination==='/var/lib/mysql'));db=await mysql.createPool({host:'127.0.0.1',port:13306,user:'badminton_user',password:'password',database:'badminton_db',dateStrings:true});assert.equal((await sql('SELECT COUNT(*) n FROM Booking'))[0].n,0,'preserve nonempty QA DB; abort');
await runCase('TC_AUTH_032',async()=>{const a=await create('freshA'),b=await create('freshB');const own=await req('GET','/bookings/me',undefined,b.token),notice=await req('GET','/bookings/user-notifications',undefined,b.token);assert.equal(own.status,200);assert.equal(notice.status,200);assert.ok(Array.isArray(own.data)&&Array.isArray(notice.data));assert.ok(own.data.every(x=>String(x.stu_id??x.student_id)===b.id));assert.ok(notice.data.every(x=>!x.stu_id||String(x.stu_id)===b.id));return`two isolated students registered; B /bookings/me=${own.data.length} rows, user-notifications=${notice.data.length}; no A rows returned`});
await runCase('TC_AUTH_017',async()=>{const x=await create('freshName');const row=(await sql('SELECT password,first_name,last_name FROM users_students WHERE stu_id=?',[x.id]))[0];assert.ok(/^\$2[aby]\$/.test(row.password),'password must be bcrypt hash');assert.equal(row.first_name,`QA`);assert.equal(row.last_name, x.id);return`stored bcrypt prefix ${row.password.slice(0,4)}; split name ${row.first_name} ${row.last_name}`});
await runCase('TC_CANC_017',async()=>{const x=await create('freshCancel');const now=new Date();const day=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(now);const h=Number(new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Bangkok',hour:'2-digit',hourCycle:'h23'}).format(now));const start=`${String(Math.min(22,Math.max(8,h+1))).padStart(2,'0')}:00:00`,end=`${String(Math.min(23,Math.max(9,h+2))).padStart(2,'0')}:00:00`;const ins=await sql("INSERT INTO Booking(stu_id,court,booking_date,time_in,time_out,status,admin_id,created_at,updated_at) VALUES(?,1,?,?,?,'PENDING','A001',NOW(),NOW())",[x.id,day,start,end]);const before=(await sql('SELECT strikes FROM users_students WHERE stu_id=?',[x.id]))[0].strikes;const me=await req('GET','/bookings/me',undefined,x.token);assert.equal(me.status,200);assert.ok(me.data.some(r=>r.booking_id===ins.insertId&&r.status==='PENDING'));const after=(await sql('SELECT status FROM Booking WHERE booking_id=?',[ins.insertId]))[0].status;const strikes=(await sql('SELECT strikes FROM users_students WHERE stu_id=?',[x.id]))[0].strikes;assert.equal(after,'PENDING');assert.equal(strikes,before);return`fixture ${ins.insertId} PENDING remains unchanged; no cancel POST was issued; strikes ${before}->${strikes} (API/UI dialog behavior itself not exercised)`});
}finally{if(db){if(ids.length){await sql('DELETE FROM Booking WHERE stu_id IN (?)',[ids]);await sql('DELETE FROM users_students WHERE stu_id IN (?)',[ids])}const remaining=(await sql('SELECT COUNT(*) n FROM Booking'))[0].n;fs.writeFileSync(out,JSON.stringify({environment:{started:run,commit:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),databaseVolume:volume,api:root,cleanup:'deleted only case-created fixture student IDs and their bookings'},results,cleanup:{remainingBookings:remaining}},null,2));console.log('EVIDENCE',out,results,`remainingBookings=${remaining}`);await db.end()}}}
main().catch(e=>{console.error('ABORT',e.stack);process.exitCode=1});