const assert=require('node:assert/strict'),fs=require('node:fs'),mysql=require('../backend/node_modules/mysql2/promise'),jwt=require('../backend/node_modules/jsonwebtoken'),{execFileSync}=require('node:child_process');
const root='http://127.0.0.1:4001',volume='badminton_qa_20260928_mysql_data',out='C:/GuisTee/Project_Y3/Book-a-Badminton/Book-a-Badminton_Court/testing/evidence/qa_sec_api_focused_results.json';const results=[];let db,a,b,admin,own=[];const studentIds=['85010001','85010002'];
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok'}).format(new Date());
async function req(method,path,body,token){let r=await fetch(root+path,{method,headers:{...(body===undefined?{}:{'content-type':'application/json'}),...(token?{authorization:'Bearer '+token}:{})},body:body===undefined?undefined:JSON.stringify(body)});let text=await r.text(),data;try{data=JSON.parse(text)}catch{data=text.slice(0,120)}return {status:r.status,data}}
async function ck(id,fn,partial=false){try{const actual=await fn();results.push({id,status:partial?'ตรวจไม่ได้':'ผ่าน',actual:String(actual).slice(0,650)})}catch(e){results.push({id,status:'ไม่ผ่าน',actual:String(e.message).slice(0,650)})}console.log(id,results.at(-1).status,results.at(-1).actual)}
async function rows(q,p=[]){return (await db.query(q,p))[0]}
async function seed(stu,court=1,status='PENDING'){let [x]=await db.query("INSERT INTO Booking(stu_id,court,booking_date,time_in,time_out,status,admin_id,created_at,updated_at) VALUES(?,?,?,'18:00:00','19:00:00',?,'A001',NOW(),NOW())",[stu,court,today(),status]);own.push(x.insertId);return x.insertId}
async function main(){assert.equal(process.env.QA_ISOLATED_DB,volume);assert.ok(execFileSync('docker',['inspect','--format','{{range .Mounts}}{{.Name}} {{end}}','badminton_mysql'],{encoding:'utf8'}).split(/\s+/).includes(volume));db=await mysql.createConnection({host:'127.0.0.1',user:process.env.DB_USER,password:process.env.DB_PASSWORD,database:'badminton_db'});assert.equal((await rows('SELECT COUNT(*) n FROM Booking'))[0].n,0);for(const stu of studentIds){let r=await req('POST','/auth/register',{studentId:stu,username:'qasec_'+stu,name:'QA Sec '+stu,email:`qasec${stu}@kmitl.ac.th`,phone:'0812345678',major:'IT',year:3,password:'QA-only-123!'});assert.equal(r.status,201);if(stu===studentIds[0])a=r.data.access_token;else b=r.data.access_token}admin=(await req('POST','/auth/login',{username:'admin',password:'password'})).data.access_token;assert.ok(admin);
await ck('TC_SEC_001',async()=>{let r=await req('GET','/bookings/me');assert.equal(r.status,401);assert.ok(!Array.isArray(r.data));return 'GET /bookings/me without bearer ->401, no booking array'});
await ck('TC_SEC_002',async()=>{let part=a.split('.'),obj=JSON.parse(Buffer.from(part[1],'base64url'));obj.role='ADMIN';part[1]=Buffer.from(JSON.stringify(obj)).toString('base64url');let r=await req('GET','/users',undefined,part.join('.'));assert.equal(r.status,401);return 'JWT payload role=ADMIN modified without re-signing; GET /users ->401'});
await ck('TC_SEC_003',async()=>{let token=jwt.sign({sub:studentIds[0],username:'qasec_'+studentIds[0],role:'STUDENT'},'DO_NOT_USE_THIS_VALUE_IN_PROD',{expiresIn:-1});let r=await req('GET','/bookings/me',undefined,token);assert.equal(r.status,401);return 'expired signed QA token ->401 API; browser redirect not exercised'},true);
await ck('TC_SEC_004',async()=>{let r=await req('GET','/bookings',undefined,a);assert.equal(r.status,403);return 'STUDENT GET /bookings ->403'});
await ck('TC_SEC_005',async()=>{let r=await req('GET','/users',undefined,a);assert.equal(r.status,403);return 'STUDENT GET /users ->403, no user list'});
await ck('TC_SEC_006',async()=>{let id=await seed(studentIds[0]);let r=await req('POST',`/bookings/${id}/finish`,{},a);assert.equal(r.status,403);assert.equal((await rows('SELECT status FROM Booking WHERE booking_id=?',[id]))[0].status,'PENDING');return 'STUDENT finish ->403; booking remains PENDING'});
await ck('TC_SEC_007',async()=>{let before=(await rows('SELECT COUNT(*) n FROM Booking'))[0].n;let r=await req('POST','/bookings/reset',{},a);assert.equal(r.status,403);assert.equal((await rows('SELECT COUNT(*) n FROM Booking'))[0].n,before);return 'STUDENT reset ->403; booking count unchanged'});
await ck('TC_SEC_008',async()=>{await seed(studentIds[1],2);let r=await req('GET','/bookings/me',undefined,b);assert.equal(r.status,200);assert.ok(r.data.length>0);assert.ok(r.data.every(x=>x.stu_id===studentIds[1]));return 'B sees only own booking(s), no A IDs'});
await ck('TC_SEC_009',async()=>{let t=jwt.sign({username:'qasec_'+studentIds[0],role:'STUDENT'},'DO_NOT_USE_THIS_VALUE_IN_PROD',{expiresIn:'5m'});let r=await req('GET','/bookings/me',undefined,t);assert.equal(r.status,200);assert.deepEqual(r.data,[]);return 'signed missing-sub token receives [] even with A/B bookings in DB'});
await ck('TC_SEC_010',async()=>{let x=await req('POST','/auth/login',{username:'qasec_'+studentIds[0],password:'QA-only-123!'});assert.equal(x.status,201);let txt=JSON.stringify(x.data);assert.ok(!/"password"|\$2[aby]\$/.test(txt));return 'login response has no password/hash; register response was 201 but not captured for field inspection; logs not inspected'},true);
await ck('TC_SEC_016',async()=>{let endpoints=['/bookings','/bookings/notifications','/bookings/me'];let leaking=[];for(let path of endpoints){let r=await req('GET',path,undefined,path.endsWith('/me')?a:admin);assert.equal(r.status,200);if(/"password"\s*:/.test(JSON.stringify(r.data)))leaking.push(path)}assert.deepEqual(leaking,[],'password key leaked via '+leaking.join(','));return 'GET /bookings, /bookings/notifications, /bookings/me nested entities contain no password'});
await ck('TC_SEC_019',async()=>{let r=await req('GET','/users',undefined,a);assert.equal(r.status,403);let payload={courtId:3,date:today(),startTime:'22:00',stu_id:studentIds[1]};let book=await req('POST','/bookings',payload,a);if(book.status===201){own.push(book.data.booking_id||book.data.id);assert.equal(book.data.stu_id,studentIds[0]);return 'forged stu_id=B ignored; booking owner=A; /users 403'}return `GET /users 403; booking endpoint ${book.status} at wall clock (owner override not exercised)`},true);
await ck('TC_SEC_020',async()=>{let r=await req('GET','/courts/availability?date='+today());assert.equal(r.status,200);assert.ok(Array.isArray(r.data));assert.ok(!/email|tel|password|token|first_name|last_name/i.test(JSON.stringify(r.data)));return 'guest availability 200 with no identity fields'});
await ck('TC_SEC_022',async()=>{let r=await req('POST','/auth/login',{username:"' OR 1=1 --",password:'X'});assert.equal(r.status,401);let q=await req('GET',"/bookings/me?id=%27%20OR%20%271%27%3D%271",undefined,b);assert.equal(q.status,200);assert.ok(q.data.every(x=>x.stu_id===studentIds[1]));assert.ok(!/sql|syntax|SELECT/i.test(JSON.stringify(r.data)));return 'SQL-like login 401; query does not bypass /me ownership'});
await ck('TC_SEC_024',async()=>{let status=[];for(let i=0;i<20;i++)status.push((await req('POST','/auth/login',{username:'qasec_'+studentIds[0],password:'bad-'+i})).status);let good=await req('GET','/bookings/me',undefined,b);assert.equal(good.status,200);return `20 QA failed logins: status distribution=${JSON.stringify(status.reduce((v,s)=>(v[s]=(v[s]||0)+1,v),{}))}; other user still served; rate-limit policy absent/unknown`},true);
await ck('TC_SEC_028',async()=>{let current=await req('GET','/bookings/me',undefined,a);assert.equal(current.status,200);return 'pre-logout token valid; logout/replay and revocation policy not exercised'},true);
fs.writeFileSync(out,JSON.stringify({environment:{commit:'37aea29',dbVolume:volume,at:new Date().toISOString()},results},null,2));console.log('EVIDENCE',out);}
main().catch(e=>{console.error('ABORT',e.message);process.exitCode=1}).finally(async()=>{if(db){try{if(own.length)await db.query('DELETE FROM Booking WHERE booking_id IN (?)',[own]);await db.query('DELETE FROM Booking WHERE stu_id IN (?,?)',studentIds);await db.query('DELETE FROM users_students WHERE stu_id IN (?,?)',studentIds);console.log('cleanup scoped fixtures')}finally{await db.end()}}});
