// Browser REQ-BOOK checks against localhost QA. Fixtures are isolated to created users.
const {chromium}=require('C:/Users/TEE/AppData/Local/hermes/cache/scratch/qa-node/node_modules/playwright');
const mysql=require('../backend/node_modules/mysql2/promise');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {execFileSync}=require('node:child_process');
const base='http://localhost:3001',api='http://127.0.0.1:4001';
const volume='badminton_qa_20260928_mysql_data';
const out=`C:/GuisTee/Project_Y3/Book-a-Badminton/Book-a-Badminton_Court/testing/evidence/${process.env.QA_ONLY?'qa_book_ui_'+process.env.QA_ONLY.replaceAll(',','_'):'qa_book_ui_results'}.json`;
const date=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const tomorrow=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(Date.now()+86400000));
const yesterday=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(Date.now()-86400000));
const results=[],users=[];let browser,db,seq=0;
async function sql(q,p=[]){return(await db.query(q,p))[0]}
async function req(method,path,data,token){let r=await fetch(api+path,{method,headers:{...(data===undefined?{}:{'Content-Type':'application/json'}),...(token?{Authorization:'Bearer '+token}:{})},body:data===undefined?undefined:JSON.stringify(data)});return {status:r.status,data:await r.json().catch(()=>({}))}}
async function student(){let n=String(76100000+Number(String(Date.now()).slice(-5))+ ++seq);assert.equal((await sql('SELECT COUNT(*) n FROM users_students WHERE stu_id=?',[n]))[0].n,0);let username='bookui_'+n,name='Book UI '+n;let r=await req('POST','/auth/register',{studentId:n,username,name,email:`bookui${n}@kmitl.ac.th`,phone:'0812345678',major:'IT',year:3,password:'QA-only-123!'});assert.equal(r.status,201,`register HTTP ${r.status}`);users.push(n);return {id:n,username,name,token:r.data.access_token}}
async function clean(){if(!users.length)return;await sql('DELETE FROM Booking WHERE stu_id IN (?)',[users]);await sql('DELETE FROM users_students WHERE stu_id IN (?)',[users]);users.length=0}
async function check(id,fn,partial=false,keep=false){if(process.env.QA_ONLY&&!process.env.QA_ONLY.split(',').includes(id))return;try{let actual=await fn();results.push({id,status:partial?'ตรวจไม่ได้':'ผ่าน',actual:String(actual).slice(0,470)})}catch(e){results.push({id,status:'ไม่ผ่าน',actual:String(e.message).slice(0,470)})}finally{if(!keep)await clean()}console.log(id,results.at(-1).status,results.at(-1).actual)}
async function page(opts={}){let p=await browser.newPage({viewport:{width:1440,height:900},...opts});p.setDefaultTimeout(15000);return p}
async function goto(p,path){await p.goto(base+path,{waitUntil:'domcontentloaded'})}
async function hydrate(p,selector){await p.waitForFunction(s=>Object.keys(document.querySelector(s)||{}).some(k=>k.startsWith('__reactProps')),selector,{timeout:30000})}
async function login(p,u){await goto(p,'/login');await hydrate(p,'#username');await p.locator('#username').fill(u.username);await p.locator('#password').fill('QA-only-123!');await p.locator('button[type=submit]').click();await p.waitForURL('**/dashboard',{timeout:30000})}
const selectPath=(slot='20:00')=>`/booking/select-court?date=${date}&time=${slot}`;
async function selectPage(p,slot='20:00'){await goto(p,selectPath(slot));await p.getByRole('heading',{name:'เลือกสนามที่ว่าง'}).waitFor({timeout:30000});await p.getByRole('heading',{name:'Court 2'}).waitFor({timeout:30000})}
async function dialog(p,court=2){await p.locator('.court-select-btn').nth(court-1).click();const d=p.getByRole('dialog');await d.getByText('ตรวจสอบรายละเอียดการจอง').waitFor();return d}
async function main(){
 assert.equal(process.env.QA_ISOLATED_DB,volume);assert.equal(process.env.DB_HOST,'127.0.0.1');assert.equal(process.env.DB_NAME,'badminton_db');
 assert.ok(execFileSync('docker',['inspect','--format','{{range .Mounts}}{{.Name}} {{end}}','badminton_mysql'],{encoding:'utf8'}).split(/\s+/).includes(volume));
 db=await mysql.createPool({host:'127.0.0.1',port:3306,user:process.env.DB_USER,password:process.env.DB_PASSWORD,database:'badminton_db',dateStrings:true});
 assert.equal((await sql('SELECT COUNT(*) n FROM Booking'))[0].n,0,'preserve existing records');
 assert.equal((await req('GET','/courts/availability?date='+date)).status,200);
 browser=await chromium.launch({headless:true});
 await check('TC_BOOK_002',async()=>{let u=await student(),p=await page();try{await login(p,u);await selectPage(p);let d=await dialog(p,2);let labels=await d.locator('dt').allTextContents(),values=await d.locator('dd').allTextContents();assert.deepEqual(labels,['วันที่','เดือน','คอร์ท','เวลา','ชื่อผู้จอง']);assert.ok(values[0].includes(String(Number(date.slice(-2)))));assert.ok(values[1]);assert.match(values[2],/Court 2/);assert.match(values[3],/20:00.*21:00/);assert.equal(values[4],u.name);return `dialog fields ${labels.join('/')}; values ${values.join(' | ')}`}finally{await p.close()}});
 await check('TC_BOOK_003',async()=>{let u=await student(),p=await page();try{await login(p,u);await selectPage(p);let d=await dialog(p,2),text=(await d.getByRole('button').allTextContents()).map(x=>x.trim()).filter(Boolean);assert.ok(text.includes('จองคอร์ต'),`actual buttons: ${text.join(' | ')}; expected exact จองคอร์ต`);return 'exact confirm label จองคอร์ต'}finally{await p.close()}});
 await check('TC_BOOK_038',async()=>{let u=await student(),p=await page();try{await login(p,u);let before=(await sql('SELECT COUNT(*) n FROM Booking WHERE stu_id=?',[u.id]))[0].n;let posts=0;p.on('request',r=>{if(r.method()==='POST'&&new URL(r.url()).pathname==='/api/bookings')posts++});await selectPage(p);let d=await dialog(p,1);await d.getByRole('button',{name:'กลับไปเลือก'}).click();await d.waitFor({state:'hidden'});let after=(await sql('SELECT COUNT(*) n FROM Booking WHERE stu_id=?',[u.id]))[0].n;let me=await req('GET','/bookings/me',undefined,u.token);assert.equal(posts,0);assert.equal(after,before);assert.equal(me.data.length,0);assert.equal(await p.locator('.court-select-btn').first().isEnabled(),true);return `close dialog: POST=0, Booking ${before}->${after}, /bookings/me=0; Court 1 still selectable`}finally{await p.close()}});
 await check('TC_BOOK_006',async()=>{let u=await student(),p=await page();try{await login(p,u);await goto(p,'/booking');await p.getByText('กฎและกติกาการใช้สนาม').waitFor();await p.getByTitle('ปิดหน้าต่างเพื่อดำเนินการจอง').click();const body=await p.locator('body').innerText();assert.ok(body.includes('วันที่'));assert.ok(body.includes('เฉพาะวันนี้เท่านั้นที่จองได้'));assert.equal(await p.locator('input[type=date]').count(),0);assert.equal(await p.locator('select').count(),0);return `today ${date} shown with วันที่; no date input/dropdown; only today selectable`}finally{await p.close()}});
 await check('TC_BOOK_015',async()=>{let u=await student(),p=await page();try{await login(p,u);await goto(p,'/booking');await p.getByText('กฎและกติกาการใช้สนาม').waitFor();await p.getByTitle('ปิดหน้าต่างเพื่อดำเนินการจอง').click();let body=await p.locator('body').innerText();assert.match(body,/เปิดให้บริการ 15 ช่วงเวลา/);assert.match(body,/08:00 - 09:00/);assert.match(body,/22:00 - 23:00/);assert.ok(!body.includes('23:00 - 24:00'));return 'UI 15 slots from 08:00-09:00 to 22:00-23:00; API/DB 22:00-23:00 separately confirmed'}finally{await p.close()}});
 await check('TC_BOOK_030',async()=>{let u=await student(),p=await page();try{await login(p,u);let av=await req('GET','/courts/availability?date='+date);assert.equal(av.status,200);assert.equal(av.data.length,4);await selectPage(p,'18:00');let names=await p.locator('.court-select-btn').count();let available=await p.locator('.court-select-btn:enabled').count();assert.equal(names,av.data.length);assert.equal(available,4);let body=await p.locator('body').innerText();assert.match(body,/4 คอร์ทพร้อมใช้/);for(let court of av.data)assert.ok(body.includes(court.name),court.name);return 'availability API 4 empty courts equals UI 4 cards/4 selectable for 18:00'}finally{await p.close()}});
 await check('TC_BOOK_031',async()=>{let u=await student(),p=await page();try{await sql("INSERT INTO Booking(stu_id,court,booking_date,time_in,time_out,status,admin_id,created_at,updated_at) VALUES(?,2,?,'18:00:00','19:00:00','PENDING','A001',NOW(),NOW())",[u.id,date]);let viewer=await student();await login(p,viewer);let av=await req('GET','/courts/availability?date='+date);await selectPage(p,'18:00');assert.equal(await p.locator('.court-select-btn').count(),4);assert.equal(await p.locator('.court-select-btn:enabled').count(),3);assert.equal(await p.locator('.court-select-btn').nth(1).isDisabled(),true);assert.match(await p.locator('body').innerText(),/3 คอร์ทพร้อมใช้/);assert.ok(av.data.find(c=>c.id===2).bookings.some(b=>b.status==='PENDING'));return 'Court 2 PENDING disabled; UI 3/4 selectable; availability agrees; other courts enabled'}finally{await p.close()}});
 await check('TC_BOOK_032',async()=>{let u=await student(),p=await page();try{await login(p,u);let invalidCalls=[];p.on('request',r=>{if(r.url().includes('/api/courts/availability')&&/date=(?:&|$)/.test(r.url()))invalidCalls.push(r.url())});for(const path of ['/booking/select-court',`/booking/select-court?date=${date}`]){await goto(p,path);await p.waitForURL('**/booking',{timeout:20000});await p.getByText('กฎและกติกาการใช้สนาม').waitFor()}assert.equal(invalidCalls.length,0);return 'missing date/time both redirect to /booking; no empty-date availability'}finally{await p.close()}});
 await check('TC_BOOK_033',async()=>{let u=await student(),p=await page();try{await login(p,u);let bad=[];p.on('response',r=>{if(r.status()===500)bad.push(r.url())});let posts=0;p.on('request',r=>{if(r.method()==='POST'&&r.url().includes('/api/bookings'))posts++});let outcomes=[];for(const [name,path] of [['past',`/booking/select-court?date=${yesterday}&time=18:00`],['tomorrow',`/booking/select-court?date=${tomorrow}&time=18:00`],['invalid-date','/booking/select-court?date=2026-02-30&time=18:00'],['invalid-time',`/booking/select-court?date=${date}&time=10:30`]]){await goto(p,path);await p.waitForFunction(()=>document.querySelector('h1')?.textContent?.includes('เลือกสนามที่ว่าง')||location.pathname==='/booking',{timeout:10000});await p.waitForURL('**/booking',{timeout:2500}).catch(()=>{});outcomes.push(`${name}:${new URL(p.url()).pathname}`)}assert.equal(posts,0);assert.equal(bad.length,0);assert.ok(outcomes.every(s=>s.endsWith(':/booking')),outcomes.join(', '));return outcomes.join(', ')+'; no POST or 500'}finally{await p.close()}});
 await check('TC_BOOK_036',async()=>{let u=await student(),p=await page();try{await login(p,u);await p.route('**/api/courts/availability**',r=>r.fulfill({status:500,contentType:'application/json',body:'{"message":"QA simulated error"}'}));let response=p.waitForResponse(r=>r.url().includes('/api/courts/availability')&&r.status()===500);await goto(p,selectPath('18:00'));await response;await p.getByRole('heading',{name:'เลือกสนามที่ว่าง'}).waitFor();await p.getByText('Failed to load courts').waitFor();let text=await p.locator('body').innerText();let buttons=await p.locator('button').allTextContents();assert.ok(buttons.some(x=>/ลองใหม่|Retry|โหลดใหม่/.test(x)),`HTTP 500: no retry button; visible=${text.slice(0,200)}; buttons=${buttons.slice(0,8).join('|')}`);return 'error state with retry controls'}finally{await p.close()}});
 await check('TC_BOOK_017',async()=>{let a=await student(),b=await student(),first=await req('POST','/bookings',{courtId:1,date,startTime:'18:00'},a.token);assert.equal(first.status,201);let p=await page();try{await login(p,b);await p.route('**/api/courts/availability**',async route=>{let response=await route.fetch(),list=await response.json();for(let c of list)if(c.id===1)c.bookings=[];await route.fulfill({response,json:list})});await selectPage(p,'18:00');let d=await dialog(p,1);let response=p.waitForResponse(r=>r.url().endsWith('/api/bookings')&&r.request().method()==='POST');await d.getByRole('button',{name:'ยืนยันจองคอร์ท'}).click();assert.equal((await response).status(),400);await p.getByText(/คอร์ท\/เวลาชน/).waitFor();assert.equal((await sql('SELECT COUNT(*) n FROM Booking WHERE stu_id IN (?)',[users]))[0].n,1);return 'stale availability simulated for B; POST /bookings HTTP 400; UI shows คอร์ท/เวลาชน; DB remains 1 booking'}finally{await p.close()}});
 await check('TC_BOOK_018',async()=>{let u=await student(),first=await req('POST','/bookings',{courtId:1,date,startTime:'18:00'},u.token);assert.equal(first.status,201);let p=await page();try{await login(p,u);await selectPage(p,'20:00');let d=await dialog(p,2);let response=p.waitForResponse(r=>r.url().endsWith('/api/bookings')&&r.request().method()==='POST');await d.getByRole('button',{name:'ยืนยันจองคอร์ท'}).click();assert.equal((await response).status(),400);await p.getByText(/ใช้โควตาประจำวันแล้ว/).waitFor();assert.equal((await sql('SELECT COUNT(*) n FROM Booking WHERE stu_id=?',[u.id]))[0].n,1);return 'existing Court1 18:00; Court2 20:00 POST 400, UI quota warning, only 1 DB row'}finally{await p.close()}});
 await check('TC_BOOK_019',async()=>{let u=await student(),p=await page();try{await login(p,u);let posts=0;p.on('request',r=>{if(r.method()==='POST'&&r.url().endsWith('/api/bookings'))posts++});await goto(p,`/booking/select-court?date=${tomorrow}&time=20:00`);await p.waitForURL('**/booking',{timeout:20000});await p.getByText('ระบบเปิดให้จองเฉพาะวันนี้เท่านั้น').waitFor();assert.equal(posts,0);assert.equal((await sql('SELECT COUNT(*) n FROM Booking WHERE stu_id=?',[u.id]))[0].n,0);return 'tomorrow URL redirected to /booking with Thai today-only toast; no POST/DB row'}finally{await p.close()}});
 await check('TC_BOOK_041',async()=>{let u=await student(),p=await page();try{await login(p,u);let persisted=false,requestCount=0;await p.route('**/api/bookings',async route=>{if(route.request().method()!=='POST')return route.continue();requestCount++;let response=await route.fetch();persisted=response.status()===201;await route.abort('timedout')});await selectPage(p,'21:00');let d=await dialog(p,1);await d.getByRole('button',{name:'ยืนยันจองคอร์ท'}).click();await p.getByText('Failed to book court').waitFor({timeout:15000});assert.equal(persisted,true,'server did not commit before client timeout');let me=await req('GET','/bookings/me',undefined,u.token);assert.equal(me.status,200);assert.equal(me.data.length,1);let retry=await req('POST','/bookings',{courtId:1,date,startTime:'21:00'},u.token);assert.equal(retry.status,400);assert.match(retry.data.message,/active booking/);assert.equal((await sql('SELECT COUNT(*) n FROM Booking WHERE stu_id=?',[u.id]))[0].n,1);return `proxy committed POST 201 then aborted client response; UI error; /bookings/me sees 1; retry HTTP 400 quota; DB 1 (requests=${requestCount})`}finally{await p.close()}});
 await check('TC_BOOK_027',async()=>{let u=await student(),p=await page();try{await login(p,u);await p.clock.install({time:new Date(`${date}T17:55:00+07:00`)});await goto(p,'/booking');await p.getByText('กฎและกติกาการใช้สนาม').waitFor();await p.getByTitle('ปิดหน้าต่างเพื่อดำเนินการจอง').click();await p.getByRole('button',{name:/18:00 - 19:00/}).click();await p.clock.setFixedTime(new Date(`${date}T19:05:00+07:00`));await p.getByRole('button',{name:/ดำเนินการจองต่อ/}).click();await p.getByText('รอบนี้หมดเวลาแล้ว กรุณาเลือกรอบใหม่').waitFor();let timePage=new URL(p.url()).pathname;await goto(p,selectPath('18:00'));await p.getByRole('heading',{name:'เลือกสนามที่ว่าง'}).waitFor();let selectable=await p.locator('.court-select-btn:enabled').count();assert.ok(selectable===0||new URL(p.url()).pathname==='/booking',`direct expired select-court URL still displays ${selectable} bookable courts`);return `booking page blocks expired selected slot and toast; direct URL also blocks (${selectable} selectable)`}finally{await p.close()}});
 await check('TC_BOOK_028',async()=>{let u=await student(),p=await page();try{await login(p,u);await p.clock.install({time:new Date(`${date}T23:10:00+07:00`)});await goto(p,'/booking');await p.getByText('กฎและกติกาการใช้สนาม').waitFor();await p.getByTitle('ปิดหน้าต่างเพื่อดำเนินการจอง').click();let body=await p.locator('body').innerText();let slots=await p.getByRole('button',{name:/\d\d:00 - \d\d:00/}).count();assert.equal(slots,0,`${slots} slots still selectable after 23:00`);assert.match(body,/หมดเวลา|ไม่มีรอบที่จองได้|ปิดรับจอง/,`no clear out-of-hours explanation; body=${body.slice(-400)}`);assert.equal(await p.getByRole('button',{name:/ดำเนินการจองต่อ/}).isDisabled(),true);return '23:10 Thai: no selectable slots; explicit explanation; proceed disabled'}finally{await p.close()}});
 await check('TC_BOOK_035',async()=>{let u=await student(),p=await page({timezoneId:'America/Los_Angeles'});try{let r=await req('POST','/bookings',{courtId:2,date,startTime:'20:00'},u.token);assert.equal(r.status,201);await login(p,u);await p.clock.install({time:new Date(`${date}T10:00:00+07:00`)});let tz=await p.evaluate(()=>({local:new Intl.DateTimeFormat('en-CA',{timeZone:'America/Los_Angeles'}).format(new Date()),thai:new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok'}).format(new Date())}));assert.notEqual(tz.local,tz.thai);await goto(p,'/booking');await p.getByText('กฎและกติกาการใช้สนาม').waitFor();await p.getByTitle('ปิดหน้าต่างเพื่อดำเนินการจอง').click();let body=await p.locator('body').innerText();assert.match(body,/วันที่[\s\S]*?28/);await goto(p,'/dashboard');await p.getByText('Recent Bookings').waitFor();let dash=await p.locator('body').innerText();assert.match(dash,/Recent Bookings/);assert.match(dash,/20:00/);return `browser LA ${tz.local} vs Thai ${tz.thai}; booking page today, dashboard booking 20:00 visible; dashboard date formatting not fully verified`}finally{await p.close()}},true);
 // One real browser booking also supplies the independently checked dashboard case.
 let bookUser=null,bookId=null;
 await check('TC_BOOK_001',async()=>{bookUser=await student();let p=await page();try{await login(p,bookUser);await selectPage(p,'18:00');let d=await dialog(p,1);await d.getByRole('button',{name:'ยืนยันจองคอร์ท'}).click();await p.getByText('จองคอร์ทสำเร็จ').waitFor({timeout:15000});let rows=await sql('SELECT booking_id,time_in,time_out,status FROM Booking WHERE stu_id=?',[bookUser.id]);assert.equal(rows.length,1);assert.deepEqual([rows[0].time_in,rows[0].time_out,rows[0].status],['18:00:00','19:00:00','PENDING']);bookId=rows[0].booking_id;return `browser confirmation/toast success, DB id=${bookId} 18:00-19:00 PENDING`}finally{await p.close()}},false,true);
 if(bookId){await check('TC_BOOK_021',async()=>{let p=await page();try{await login(p,bookUser);const start=Date.now();await p.getByText('Recent Bookings').waitFor({timeout:5000});await p.getByText('18:00', {exact:false}).first().waitFor({timeout:5000});assert.ok(Date.now()-start<=5000,`took ${Date.now()-start}ms`);assert.match(await p.locator('body').innerText(),/PENDING/);return `Recent Bookings shows new id=${bookId} 18:00/PENDING within 5s`}finally{await p.close()}})} else {await clean()}
 await clean();fs.writeFileSync(out,JSON.stringify({environment:{databaseVolume:volume,commit:'37aea29',codeCommit:'581a654',caseCommit:'ed3bdca',date,at:new Date().toISOString(),browser:'Chromium headless',cleanup:'all runner-created users/bookings removed'},results},null,2));console.log('EVIDENCE',out,results.reduce((m,x)=>(m[x.status]=(m[x.status]||0)+1,m),{}));
}
main().catch(e=>{console.error('ABORT',String(e.stack).slice(0,1800));process.exitCode=1}).finally(async()=>{if(browser)await browser.close();if(db){try{await clean()}finally{await db.end()}}});
