// Fresh UI evidence for TC_BOOK_037 and REQ-BAN popup cases.
const {chromium}=require('C:/Users/TEE/AppData/Local/hermes/cache/scratch/qa-node/node_modules/playwright');
const mysql=require('../backend/node_modules/mysql2/promise');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {execFileSync}=require('node:child_process');
const base='http://localhost:3001',api='http://127.0.0.1:4001',volume='badminton_qa_20260928_mysql_data';
const out='C:/GuisTee/Project_Y3/Book-a-Badminton/Book-a-Badminton_Court/testing/evidence/qa_book37_ban_ui_results.json';
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok'}).format(new Date());
const results=[],users=[];let db,browser,seq=0;
async function sql(q,p=[]){return(await db.query(q,p))[0]}
async function req(method,path,data,token){const r=await fetch(api+path,{method,headers:{...(data===undefined?{}:{'Content-Type':'application/json'}),...(token?{Authorization:'Bearer '+token}:{})},body:data===undefined?undefined:JSON.stringify(data)});return{status:r.status,data:await r.json().catch(()=>({}))}}
async function student(prefix){const id=String(79000000+Number(String(Date.now()).slice(-5))+ ++seq),username=`${prefix}_${id}`,name=`QA ${id}`;const r=await req('POST','/auth/register',{studentId:id,username,name,email:`${prefix}${id}@kmitl.ac.th`,phone:'0812345678',major:'IT',year:3,password:'QA-only-123!'});assert.equal(r.status,201);users.push(id);return{id,username,name,role:'STUDENT',token:r.data.access_token}}
async function admin(){const r=await req('POST','/auth/login',{username:'admin',password:'password'});assert.equal(r.status,201);return{id:'A001',username:'admin',name:'Administrator',role:'ADMIN',token:r.data.access_token}}
async function clean(){if(!users.length)return;await sql('DELETE FROM Booking WHERE stu_id IN (?)',[users]);await sql('DELETE FROM users_students WHERE stu_id IN (?)',[users]);users.length=0}
async function check(id,fn,forced){try{results.push({id,status:forced||'ผ่าน',actual:String(await fn()).slice(0,700)})}catch(e){results.push({id,status:'ไม่ผ่าน',actual:String(e.message).slice(0,700)})}finally{await clean()}console.log(id,results.at(-1).status,results.at(-1).actual)}
async function page(){const c=await browser.newContext({viewport:{width:1440,height:900},timezoneId:'Asia/Bangkok'}),p=await c.newPage();p.setDefaultTimeout(18000);return p}
async function authorize(p,u,path='/dashboard'){await p.goto(base+'/login',{waitUntil:'domcontentloaded'});await p.evaluate(u=>{localStorage.setItem('token',u.token);localStorage.setItem('user',JSON.stringify({id:u.id,name:u.name,username:u.username,role:u.role}))},u);await p.goto(base+path,{waitUntil:'domcontentloaded'})}
async function close(p){await p.context().close()}
async function main(){assert.equal(process.env.QA_ISOLATED_DB,volume);assert.equal(process.env.DB_HOST,'127.0.0.1');assert.equal(process.env.DB_NAME,'badminton_db');const mounts=execFileSync('docker',['inspect','--format','{{range .Mounts}}{{.Name}} {{end}}','badminton_mysql'],{encoding:'utf8'});assert.ok(mounts.split(/\s+/).includes(volume));db=await mysql.createPool({host:'127.0.0.1',port:3306,user:process.env.DB_USER,password:process.env.DB_PASSWORD,database:'badminton_db',dateStrings:true});assert.equal((await sql('SELECT COUNT(*) n FROM Booking'))[0].n,0);browser=await chromium.launch({headless:true});
 await check('TC_BOOK_037',async()=>{const u=await student('book37'),p=await page();try{await authorize(p,u);let call=0,releaseFirst,seenFirst,seenSecond;const firstGate=new Promise(r=>releaseFirst=r),firstStarted=new Promise(r=>seenFirst=r),secondGate=new Promise(r=>seenSecond=r);const courts=booked=>[1,2,3,4].map(id=>({id,name:`Court ${id}`,description:'QA',status:'AVAILABLE',bookings:booked===id?[{start_time:booked===1?'18:00:00':'20:00:00',status:'PENDING'}]:[]}));await p.route('**/api/courts/availability**',async route=>{call++;if(call===1){seenFirst();await firstGate;return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(courts(1))})}await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(courts(2))});seenSecond()});await p.goto(`${base}/booking/select-court?date=${today}&time=18:00`,{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>location.search.includes('time=18'));await firstStarted;await p.evaluate(today=>{history.pushState(null,'',`/booking/select-court?date=${today}&time=20:00`);window.dispatchEvent(new PopStateEvent('popstate'))},today);await Promise.race([secondGate,new Promise((_,reject)=>setTimeout(()=>reject(new Error('second availability request did not start after query change')),12000))]).catch(e=>{releaseFirst();throw e});await p.getByText(/20:00 - 21:00/).first().waitFor();releaseFirst();await p.waitForTimeout(900);assert.equal(call,2);assert.equal(await p.locator('.court-select-btn').nth(0).isEnabled(),true);assert.equal(await p.locator('.court-select-btn').nth(1).isDisabled(),true);return 'query changed 18:00→20:00 while first availability request was held; latest response rendered Court 2 booked; delayed first response ignored and did not overwrite Court 1/Court 2 states'}finally{await close(p)}});
 await check('TC_BAN_014',async()=>{const u=await student('ban14'),until=new Date(Date.now()+3600000);await sql('UPDATE users_students SET strikes=2,banned_until=? WHERE stu_id=?',[until,u.id]);const p=await page();try{await authorize(p,u);const d=p.getByRole('dialog');await d.getByText('บัญชีของคุณถูกระงับการใช้งาน').waitFor();const text=await d.innerText();assert.match(text,/ระยะเวลาพ้นแบน/);assert.match(text,/รับทราบ/);assert.match(text,/2 ครั้ง/);assert.match(text,/\d{1,2}\/\d{1,2}\/\d{2,4}[^\n]*\d{1,2}:\d{2}/);return `ban popup displayed title, two-strike reason, th-TH expiry and Acknowledge button; banned_until=${until.toISOString()}`}finally{await close(p)}});
 await check('TC_BAN_015',async()=>{const u=await student('ban15'),until=new Date(Date.now()+3600000);await sql('UPDATE users_students SET strikes=2,banned_until=? WHERE stu_id=?',[until,u.id]);const p=await page();try{await authorize(p,u);let d=p.getByRole('dialog');await d.getByText('บัญชีของคุณถูกระงับการใช้งาน').waitFor();await sql('UPDATE users_students SET strikes=0,banned_until=NULL WHERE stu_id=?',[u.id]);await d.getByRole('button',{name:/รับทราบ/}).click();await p.goto(base+'/news',{waitUntil:'domcontentloaded'});await p.goto(base+'/dashboard',{waitUntil:'domcontentloaded'});await p.getByText('Hi,',{exact:false}).first().waitFor();assert.equal(await p.getByText('บัญชีของคุณถูกระงับการใช้งาน').count(),0);const s=await req('GET','/users/me/ban-status',undefined,u.token);assert.equal(s.status,200);assert.deepEqual({isBanned:s.data.isBanned,strikes:s.data.strikes},{isBanned:false,strikes:0});return 'popup initially used server ban; after DB unban, close + page remount fetched central API and popup did not reappear; API isBanned=false/strikes=0'}finally{await close(p)}});
 await check('TC_BAN_016',async()=>{const a=await admin(),p=await page();try{const s=await req('GET','/users/me/ban-status',undefined,a.token);assert.equal(s.status,200);assert.deepEqual(s.data,{isBanned:false,bannedUntil:null,strikes:0});await authorize(p,a);await p.getByText(/Good (morning|afternoon|evening), Admin/).waitFor();assert.equal(await p.getByText('บัญชีของคุณถูกระงับการใช้งาน').count(),0);return 'Admin ban-status={isBanned:false,bannedUntil:null,strikes:0}; Admin dashboard rendered without ban popup'}finally{await close(p)}});
 await check('TC_BAN_024',async()=>{const a=await student('ban24a'),b=await student('ban24b'),until=new Date(Date.now()+3600000);await sql('UPDATE users_students SET strikes=2,banned_until=? WHERE stu_id=?',[until,a.id]);const p=await page();try{await authorize(p,a);await p.getByText('บัญชีของคุณถูกระงับการใช้งาน').waitFor();await p.getByRole('button',{name:/รับทราบ/}).click();await p.evaluate(()=>localStorage.clear());await authorize(p,b);await p.getByText('Hi,',{exact:false}).first().waitFor();assert.equal(await p.getByText('บัญชีของคุณถูกระงับการใช้งาน').count(),0);const s=await req('GET','/users/me/ban-status',undefined,b.token);assert.equal(s.status,200);assert.equal(s.data.isBanned,false);assert.equal(s.data.strikes,0);return 'Account A showed ban popup; local session cleared and Account B authorized in same browser; B showed no popup and API returned isBanned=false/strikes=0'}finally{await close(p)}});
 fs.writeFileSync(out,JSON.stringify({environment:{databaseVolume:volume,commit:'37aea29',at:new Date().toISOString(),browser:'Chromium headless',cleanup:'only runner fixtures removed'},results},null,2));console.log('EVIDENCE',out,results.reduce((a,r)=>(a[r.status]=(a[r.status]||0)+1,a),{}));
}
main().catch(e=>{console.error('ABORT',e.stack);process.exitCode=1}).finally(async()=>{try{await clean()}catch{}if(browser)await browser.close().catch(()=>{});if(db)await db.end().catch(()=>{})});
