require('../backend/node_modules/reflect-metadata');
const assert=require('node:assert/strict'),{mock}=require('node:test'),fs=require('node:fs'),{execFileSync}=require('node:child_process');const {DataSource}=require('../backend/node_modules/typeorm');
const {Booking}=require('../backend/dist/bookings/entities/booking.entity'),{Student}=require('../backend/dist/users/entities/student.entity'),{Admin}=require('../backend/dist/users/entities/admin.entity'),{Court}=require('../backend/dist/courts/entities/court.entity');const {BookingsService}=require('../backend/dist/bookings/bookings.service'),{CronService}=require('../backend/dist/cron/cron.service');
const volume='badminton_qa_20260928_mysql_data',uid='87010001',out='C:/GuisTee/Project_Y3/Book-a-Badminton/Book-a-Badminton_Court/testing/evidence/qa_conc_service_results.json';let ds,br,sr,ar,booking,cron;const results=[];const day='2026-09-28';
function at(s){mock.timers.setTime(Date.parse(s))}
async function reset(){await br.delete({stu_id:uid});await sr.update({stu_id:uid},{strikes:0,banned_until:null})}
async function fixture({status='PENDING',court=1,start='18:00:00',end='19:00:00',created='17:00:00',date=day}={}){return br.save(br.create({stu_id:uid,court,booking_date:date,time_in:start,time_out:end,status,admin_id:'A001',created_at:new Date(`${date}T${created}+07:00`)}))}
async function check(id,fn,partial=false){try{await reset();results.push({id,status:partial?'ตรวจไม่ได้':'ผ่าน',actual:String(await fn()).slice(0,750)})}catch(e){results.push({id,status:'ไม่ผ่าน',actual:String(e.message).slice(0,750)})}console.log(id,results.at(-1).status,results.at(-1).actual)}
async function main(){assert.equal(process.env.QA_ISOLATED_DB,volume);assert.ok(execFileSync('docker',['inspect','--format','{{range .Mounts}}{{.Name}} {{end}}','badminton_mysql'],{encoding:'utf8'}).split(/\s+/).includes(volume));ds=new DataSource({type:'mysql',host:'127.0.0.1',port:3306,username:process.env.DB_USER,password:process.env.DB_PASSWORD,database:'badminton_db',entities:[Booking,Student,Admin,Court],synchronize:false});await ds.initialize();br=ds.getRepository(Booking);sr=ds.getRepository(Student);ar=ds.getRepository(Admin);assert.equal(await br.count(),0);await sr.save(sr.create({stu_id:uid,email:'qaconcservice@kmitl.ac.th',username:'qaconcservice_87010001',first_name:'Conc',last_name:'Service',password:'not-used',tel:'0812345678',major:'IT',year:3,strikes:0,banned_until:null}));booking=new BookingsService(br,sr,ar);cron=new CronService(br,sr);mock.timers.enable({apis:['Date'],now:Date.parse(`${day}T18:00:00+07:00`)});
await check('TC_CONC_004',async()=>{let b=await fixture();at(`${day}T18:15:00+07:00`);let out=await Promise.allSettled([booking.cancelBooking(b.booking_id,uid),cron.handleCron()]);let row=await br.findOneByOrFail({booking_id:b.booking_id}),s=await sr.findOneByOrFail({stu_id:uid});assert.equal(row.status,'CANCELLED');assert.equal(s.strikes,1);return `cancel vs cron concurrently: ${out.map(x=>x.status).join(',')}, DB CANCELLED/strikes=1`});
await check('TC_CONC_005',async()=>{let b=await fixture();at(`${day}T18:15:00+07:00`);let manager=br.manager,tx=manager.transaction,failed=false;manager.transaction=async function(cb){return tx.call(this,async em=>{let save=em.save.bind(em);em.save=async(...args)=>{const v=args.length===2?args[1]:args[0];if(v?.constructor?.name==='Booking')throw Error('QA failpoint before booking save');return save(...args)};return cb(em)})};try{await booking.cancelBooking(b.booking_id,uid)}catch(e){failed=/QA failpoint/.test(e.message)}finally{manager.transaction=tx}assert.ok(failed);let r=await br.findOneByOrFail({booking_id:b.booking_id}),s=await sr.findOneByOrFail({stu_id:uid});assert.equal(r.status,'PENDING');assert.equal(s.strikes,0);await booking.cancelBooking(b.booking_id,uid);r=await br.findOneByOrFail({booking_id:b.booking_id});s=await sr.findOneByOrFail({stu_id:uid});assert.equal(r.status,'CANCELLED');assert.equal(s.strikes,1);return 'injected booking-write failure rolled back status/strike; retry produced one CANCELLED + one strike'});
await check('TC_CONC_006',async()=>{for(let i=0;i<3;i++)await fixture({court:i+1,start:`${15+i}:00:00`,end:`${16+i}:00:00`,created:'12:00:00'});at(`${day}T18:15:00+07:00`);await Promise.all([cron.handleCron(),cron.handleCron(),cron.handleCron()]);let rows=await br.find({where:{stu_id:uid}}),s=await sr.findOneByOrFail({stu_id:uid});assert.ok(rows.every(x=>x.status==='CANCELLED'));assert.equal(s.strikes,3);return 'same process: 3 concurrent cron calls on 3 bookings -> 3 CANCELLED / strikes=3; cross-process not exercised'},true);
await check('TC_CONC_009',async()=>{let b=await fixture();at(`${day}T18:01:00+07:00`);let r=await Promise.allSettled([booking.checkIn(b.booking_id,uid,1),booking.cancelBooking(b.booking_id,uid)]);let row=await br.findOneByOrFail({booking_id:b.booking_id}),s=await sr.findOneByOrFail({stu_id:uid});assert.equal(r.filter(x=>x.status==='fulfilled').length,1);assert.ok(['CHECKED_IN','CANCELLED'].includes(row.status));assert.equal(s.strikes,0);let rej=r.find(x=>x.status==='rejected');assert.equal(rej?.reason?.getStatus(),400);return `check-in vs cancel: one success/one 400, final ${row.status}, strikes=0`});
await check('TC_CONC_010',async()=>{let b=await fixture();at(`${day}T18:15:00+07:00`);let r=await Promise.allSettled([booking.checkIn(b.booking_id,uid,1),cron.handleCron()]);let row=await br.findOneByOrFail({booking_id:b.booking_id}),s=await sr.findOneByOrFail({stu_id:uid});assert.equal(row.status,'CANCELLED');assert.equal(s.strikes,1);assert.equal(r[0].status,'rejected');assert.ok(/check-in period has ended|Status is currently CANCELLED/.test(r[0].reason.message));return `at exact deadline: checkin rejected '${r[0].reason.message}', cron CANCELLED, strikes=1`});
await check('TC_CONC_011',async()=>{let b=await fixture({status:'CHECKED_IN'});at(`${day}T19:00:00+07:00`);let r=await Promise.allSettled([booking.finishBooking(b.booking_id),cron.handleCron()]);let row=await br.findOneByOrFail({booking_id:b.booking_id}),s=await sr.findOneByOrFail({stu_id:uid});assert.equal(row.status,'COMPLETED');assert.equal(s.strikes,0);return `finish vs cron results=${r.map(x=>x.status)}; final COMPLETED/strikes0 (single-process one trial)`},true);
await check('TC_CONC_012',async()=>{let b=await fixture();await sr.update({stu_id:uid},{strikes:1});at(`${day}T18:15:00+07:00`);await cron.handleCron();let s=await sr.findOneByOrFail({stu_id:uid});assert.equal(s.strikes,2);assert.ok(s.banned_until);let delta=new Date(s.banned_until).getTime()-Date.now();assert.equal(delta,86400000);let msg='';try{await booking.createBooking(uid,2,day,'20:00');throw Error('booking unexpectedly accepted')}catch(e){if(e.message==='booking unexpectedly accepted')throw e;msg=e.message;assert.equal(e.getStatus(),400)}assert.match(msg,/banned/);return `second strike ban=24h, post-ban booking 400; simultaneous ban-vs-create not exercised`},true);
await check('TC_CONC_016',async()=>{let outcomes=[];for(let kind of ['CHECKED_IN','CANCELLED','COMPLETED']){await reset();let b=await fixture({status:kind==='COMPLETED'?'CHECKED_IN':'PENDING',created:'10:30:00',start:'10:00:00',end:'11:00:00'}),before=(await br.findOneByOrFail({booking_id:b.booking_id})).created_at;at(`${day}T10:40:00+07:00`);if(kind==='CHECKED_IN')await booking.checkIn(b.booking_id,uid,1);if(kind==='CANCELLED')await booking.cancelBooking(b.booking_id,uid);if(kind==='COMPLETED')await booking.finishBooking(b.booking_id);let after=(await br.findOneByOrFail({booking_id:b.booking_id})).created_at;assert.equal(+before,+after);outcomes.push(kind)}return `created_at unchanged across ${outcomes.join(',')}; 10:30 booking grace deadline 10:45`});
fs.writeFileSync(out,JSON.stringify({environment:{commit:'37aea29',dbVolume:volume,clock:'mocked Date + real MySQL',at:new Date().toISOString()},results},null,2));console.log('EVIDENCE',out)}
main().catch(e=>{console.error('ABORT',e.stack);process.exitCode=1}).finally(async()=>{try{mock.timers.reset();if(ds?.isInitialized){await br?.delete({stu_id:uid});await sr?.delete({stu_id:uid});await ds.destroy()}}catch(e){console.error('CLEANUP ERROR',e.message)}});
