// Fresh direct-service REQ-BAN edge tests on isolated MySQL with controlled Date.
require('../backend/node_modules/reflect-metadata');
const assert=require('node:assert/strict'),{mock}=require('node:test'),fs=require('node:fs');
const {execFileSync}=require('node:child_process'),{DataSource}=require('../backend/node_modules/typeorm');
const {Booking}=require('../backend/dist/bookings/entities/booking.entity'),{Student}=require('../backend/dist/users/entities/student.entity'),{Admin}=require('../backend/dist/users/entities/admin.entity'),{Court}=require('../backend/dist/courts/entities/court.entity');
const {BookingsService}=require('../backend/dist/bookings/bookings.service'),{CronService}=require('../backend/dist/cron/cron.service'),{UsersService}=require('../backend/dist/users/users.service'),{UsersController}=require('../backend/dist/users/users.controller');
const volume='badminton_qa_20260928_mysql_data',out='C:/GuisTee/Project_Y3/Book-a-Badminton/Book-a-Badminton_Court/testing/evidence/qa_ban_service_results.json',uid='83000001';
let ds,br,sr,ar,booking,cron,users,controller;const results=[];
function at(s){mock.timers.setTime(Date.parse(s))}
async function reset(){await br.delete({stu_id:uid});await sr.update({stu_id:uid},{strikes:0,banned_until:null})}
async function fixture({date='2026-09-28',court=1,start='18:00:00',end='19:00:00',status='PENDING',created='17:00:00'}={}){return br.save(br.create({stu_id:uid,court,booking_date:date,time_in:start,time_out:end,status,admin_id:'A001',created_at:new Date(`${date}T${created}+07:00`)}))}
async function check(id,fn){try{await reset();results.push({id,status:'ผ่าน',actual:String(await fn()).slice(0,850)})}catch(e){results.push({id,status:'ไม่ผ่าน',actual:String(e.message).slice(0,850)})}console.log(id,results.at(-1).status,results.at(-1).actual)}
async function main(){assert.equal(process.env.QA_ISOLATED_DB,volume);assert.ok(execFileSync('docker',['inspect','--format','{{range .Mounts}}{{.Name}} {{end}}','badminton_mysql'],{encoding:'utf8'}).split(/\s+/).includes(volume));ds=new DataSource({type:'mysql',host:'127.0.0.1',port:Number(process.env.DB_PORT||13306),username:process.env.DB_USER,password:process.env.DB_PASSWORD,database:'badminton_db',entities:[Booking,Student,Admin,Court],synchronize:false});await ds.initialize();br=ds.getRepository(Booking);sr=ds.getRepository(Student);ar=ds.getRepository(Admin);assert.equal(await br.count(),0);await sr.save(sr.create({stu_id:uid,email:'banservice@kmitl.ac.th',username:'banservice_'+uid,first_name:'Ban',last_name:'Service',password:'not-used',tel:'0812345678',major:'IT',year:3,strikes:0,banned_until:null}));booking=new BookingsService(br,sr,ar);cron=new CronService(br,sr);users=new UsersService(ar,sr);controller=new UsersController(users);mock.timers.enable({apis:['Date'],now:Date.parse('2026-09-28T12:00:00+07:00')});
 await check('TC_BAN_004',async()=>{const b=await fixture();at('2026-09-28T18:14:30+07:00');await cron.handleCron();const row=await br.findOneByOrFail({booking_id:b.booking_id}),s=await sr.findOneByOrFail({stu_id:uid});assert.equal(row.status,'PENDING');assert.equal(s.strikes,0);return 'real MySQL CronService at 18:14:30 kept booking PENDING and strikes=0'});
 await check('TC_BAN_005',async()=>{const b=await fixture();at('2026-09-28T18:15:00+07:00');await cron.handleCron();const row=await br.findOneByOrFail({booking_id:b.booking_id}),s=await sr.findOneByOrFail({stu_id:uid});assert.equal(row.status,'CANCELLED');assert.equal(s.strikes,1);return 'real MySQL CronService at exact 18:15:00 changed PENDING→CANCELLED and strikes 0→1'});
 await check('TC_BAN_020',async()=>{const b=await fixture({start:'10:00:00',end:'11:00:00',created:'10:30:00'});at('2026-09-28T10:44:59+07:00');await booking.checkIn(b.booking_id,uid,1);at('2026-09-28T10:59:59+07:00');await cron.handleCron();assert.equal((await br.findOneByOrFail({booking_id:b.booking_id})).status,'CHECKED_IN');at('2026-09-28T11:00:00+07:00');await cron.handleCron();assert.equal((await br.findOneByOrFail({booking_id:b.booking_id})).status,'COMPLETED');return 'mid-round booking checked in at 10:44:59; remained CHECKED_IN at 10:59:59; became COMPLETED at original end 11:00:00'});
 await check('TC_BAN_012',async()=>{await sr.update({stu_id:uid},{strikes:2,banned_until:new Date('2026-09-28T11:59:59+07:00')});at('2026-09-28T12:00:00+07:00');await cron.handleCron();const s=await sr.findOneByOrFail({stu_id:uid});assert.equal(s.strikes,0);assert.equal(s.banned_until,null);return 'direct CronService on real MySQL at expiry cleared banned_until and reset strikes 2→0 automatically'});
 await check('TC_BAN_022',async()=>{await fixture({date:'2026-09-27',status:'CANCELLED'});at('2026-09-28T00:01:00+07:00');const b=await booking.createBooking(uid,2,'2026-09-28','18:00');assert.equal(b.status,'PENDING');const rows=await br.find({where:{stu_id:uid},order:{booking_date:'ASC'}});assert.deepEqual(rows.map(x=>x.booking_date),['2026-09-27','2026-09-28']);return `at Thai 00:01, new-day booking ${b.booking_id} succeeded while yesterday CANCELLED history remained; dates=${rows.map(x=>x.booking_date).join(',')}`});
 await check('TC_BAN_023',async()=>{await br.clear();await sr.update({stu_id:uid},{quota:1,strikes:2,banned_until:new Date('2026-09-28T12:00:00+07:00')});at('2026-09-28T11:59:59+07:00');let msg='';try{await booking.createBooking(uid,1,'2026-09-28','18:00');throw Error('11:59:59 unexpectedly booked')}catch(e){if(e.message==='11:59:59 unexpectedly booked')throw e;assert.equal(e.getStatus(),400);msg=e.message}assert.equal(msg,'Your account is currently banned from booking courts.');at('2026-09-28T12:00:00+07:00');const b=await booking.createBooking(uid,1,'2026-09-28','18:00');const s=await sr.findOneByOrFail({stu_id:uid});assert.equal(s.strikes,0);assert.equal(s.banned_until,null);return `11:59:59 rejected 400 exact ban message; 12:00:00 booking ${b.booking_id} succeeded and auto-unban reset strikes=0`});
 await check('TC_BAN_025',async()=>{await sr.update({stu_id:uid},{strikes:2,banned_until:new Date('2026-09-28T12:00:00+07:00')});at('2026-09-28T12:00:00+07:00');const request={user:{role:'STUDENT',userId:uid}};for(let i=0;i<3;i++)await Promise.all([controller.getBanStatus(request),cron.handleCron(),controller.getBanStatus(request)]);const s=await sr.findOneByOrFail({stu_id:uid}),r=await controller.getBanStatus(request);assert.equal(s.strikes,0);assert.equal(s.banned_until,null);assert.deepEqual({isBanned:r.isBanned,strikes:r.strikes,bannedUntil:r.bannedUntil},{isBanned:false,strikes:0,bannedUntil:null});return '3 concurrent rounds of ban-status + CronService at expiry converged idempotently: DB/API strikes=0, banned_until=null, no reversal'});
 await check('TC_BAN_026',async()=>{await fixture({date:'2026-09-27'});await fixture({date:'2026-09-28',court:2});at('2026-09-29T12:00:00+07:00');const manager=br.manager,origTx=manager.transaction.bind(manager),originalMethod=manager.transaction;manager.transaction=async callback=>origTx(async tx=>{const realSave=tx.save.bind(tx);tx.save=async(...args)=>{const target=args.length===2?args[1]:args[0],isBooking=target?.constructor?.name==='Booking';if(isBooking)throw Error('QA injected booking write failure');return realSave(...args)};return callback(tx)});let failed=false;try{await cron.handleCron()}catch(e){failed=/QA injected/.test(e.message)}finally{manager.transaction=originalMethod}assert.equal(failed,true);let rows=await br.find({where:{stu_id:uid}}),s=await sr.findOneByOrFail({stu_id:uid});assert.ok(rows.every(x=>x.status==='PENDING'));assert.equal(s.strikes,0);await cron.handleCron();rows=await br.find({where:{stu_id:uid}});s=await sr.findOneByOrFail({stu_id:uid});assert.ok(rows.every(x=>x.status==='CANCELLED'));assert.equal(s.strikes,2);assert.ok(s.banned_until);return 'injected failure after strike save/before booking save rolled transaction back: 2 PENDING/strikes0; next cron retry atomically produced 2 CANCELLED/strikes2/ban, no double count'});
 await reset();mock.timers.reset();fs.writeFileSync(out,JSON.stringify({environment:{databaseVolume:volume,commit:require('node:child_process').execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),at:new Date().toISOString(),approach:'mocked Date + real MySQL TypeORM services; backend process stopped',cleanup:'fixture removed'},results},null,2));console.log('EVIDENCE',out,results.reduce((a,r)=>(a[r.status]=(a[r.status]||0)+1,a),{}));}
main().catch(e=>{console.error('ABORT',e.stack);process.exitCode=1}).finally(async()=>{mock.timers.reset();if(ds?.isInitialized){try{await br?.delete({stu_id:uid});await sr?.delete({stu_id:uid})}finally{await ds.destroy()}}});
