// Fresh browser evidence for REQ-ADMIN against isolated QA MySQL.
const {chromium}=require('C:/Users/TEE/AppData/Local/hermes/cache/scratch/qa-node/node_modules/playwright');
const mysql=require('../backend/node_modules/mysql2/promise'),assert=require('node:assert/strict'),fs=require('node:fs');
const {execFileSync}=require('node:child_process');
const base='http://localhost:3001',api='http://127.0.0.1:4001',volume='badminton_qa_20260928_mysql_data',out=`C:/GuisTee/Project_Y3/Book-a-Badminton/Book-a-Badminton_Court/testing/evidence/${process.env.QA_ONLY?'qa_admin_ui_recheck_results':'qa_admin_ui_results'}.json`;
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok'}).format(new Date()),yesterday=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok'}).format(new Date(Date.now()-86400000));
const results=[],students=[],admins=[];let db,browser,seq=0,adminUser;
async function sql(q,p=[]){return(await db.query(q,p))[0]}
async function req(method,path,data,token){const r=await fetch(api+path,{method,headers:{...(data===undefined?{}:{'Content-Type':'application/json'}),...(token?{Authorization:'Bearer '+token}:{})},body:data===undefined?undefined:JSON.stringify(data)});return{status:r.status,data:await r.json().catch(()=>({}))}}
async function student(prefix='admui'){const id=String(81000000+Number(String(Date.now()).slice(-5))+ ++seq),username=`${prefix}_${id}`,name=`QA ${id}`;const r=await req('POST','/auth/register',{studentId:id,username,name,email:`${prefix}${id}@kmitl.ac.th`,phone:'0812345678',major:'IT',year:3,password:'QA-only-123!'});assert.equal(r.status,201);students.push(id);return{id,username,name,role:'STUDENT',token:r.data.access_token}}
async function seed(u,{court=1,status='PENDING',date=today,start='21:00:00',end='22:00:00'}={}){return(await sql("INSERT INTO Booking(stu_id,court,booking_date,time_in,time_out,status,admin_id,created_at,updated_at) VALUES(?,?,?,?,?,?,'A001',NOW(),NOW())",[u.id,court,date,start,end,status])).insertId}
async function clean(){if(students.length){await sql('DELETE FROM Booking WHERE stu_id IN (?)',[students]);await sql('DELETE FROM users_students WHERE stu_id IN (?)',[students]);students.length=0}if(admins.length){await sql('DELETE FROM admin WHERE username IN (?)',[admins]);admins.length=0}}
async function check(id,fn,forced){if(process.env.QA_ONLY&&!process.env.QA_ONLY.split(',').includes(id))return;try{results.push({id,status:forced||'ผ่าน',actual:String(await fn()).slice(0,950)})}catch(e){results.push({id,status:'ไม่ผ่าน',actual:String(e.message).slice(0,950)})}finally{await clean()}console.log(id,results.at(-1).status,results.at(-1).actual)}
async function page(viewport={width:1440,height:900}){const c=await browser.newContext({viewport,timezoneId:'Asia/Bangkok'}),p=await c.newPage();p.setDefaultTimeout(18000);return p}
async function authorize(p,u,path='/dashboard'){await p.goto(base+'/login');await p.evaluate(u=>{localStorage.setItem('token',u.token);localStorage.setItem('user',JSON.stringify({id:u.id,name:u.name,username:u.username,role:u.role}))},u);await p.goto(base+path,{waitUntil:'domcontentloaded'})}
async function close(p){await p.context().close()}
async function bell(p){await p.getByRole('button',{name:'Notifications'}).click();await p.getByRole('heading',{name:/^การแจ้งเตือน/}).waitFor()}
async function card(p,id){const ref=p.getByText(`REF: #BK-${id}`,{exact:true}).first();await ref.waitFor({timeout:30000});return ref.locator('xpath=ancestor::article')}
async function main(){assert.equal(process.env.QA_ISOLATED_DB,volume);assert.ok(execFileSync('docker',['inspect','--format','{{range .Mounts}}{{.Name}} {{end}}','badminton_mysql'],{encoding:'utf8'}).split(/\s+/).includes(volume));db=await mysql.createPool({host:'127.0.0.1',user:process.env.DB_USER,password:process.env.DB_PASSWORD,database:'badminton_db',dateStrings:true});assert.equal((await sql('SELECT COUNT(*) n FROM Booking'))[0].n,0);let ar=await req('POST','/auth/login',{username:'admin',password:'password'});assert.equal(ar.status,201);adminUser={...ar.data.user,token:ar.data.access_token};browser=await chromium.launch({headless:true});
 await check('TC_ADM_001',async()=>{const u=await student('adm1'),pending=await seed(u),cancelled=await seed(u,{court:2,status:'CANCELLED',start:'20:00:00',end:'21:00:00'}),p=await page();try{await authorize(p,adminUser);await bell(p);const text=await p.locator('body').innerText();assert.match(text,/การจองใหม่/);assert.match(text,/ยกเลิกการจอง/);const iNew=text.indexOf(`ID: ${cancelled}`),iOld=text.indexOf(`ID: ${pending}`);assert.ok(iNew>=0&&iOld>=0&&iNew<iOld,`notification order ${cancelled}:${iNew}, ${pending}:${iOld}`);return `bell showed new-booking ID ${pending} and cancelled ID ${cancelled}; latest cancelled item appeared first`}finally{await close(p)}});
 await check('TC_ADM_002',async()=>{const u=await student('adm2'),p=await page();try{await authorize(p,adminUser);await p.getByText(/Good .*Admin/).waitFor();const id=await seed(u);await p.waitForTimeout(10500);await bell(p);const body=await p.locator('body').innerText();assert.ok(body.includes(`ID: ${id}`),`new booking ${id} did not appear after 10.5s without reload`);return `new notification ${id} appeared within 10s without refresh`}finally{await close(p)}});
 await check('TC_ADM_003',async()=>{const p=await page();try{await authorize(p,adminUser);await p.getByText(/Good .*Admin/).waitFor();const colors=await p.evaluate(()=>({body:getComputedStyle(document.body).backgroundColor,header:getComputedStyle(document.querySelector('header')).backgroundColor,primary:getComputedStyle(document.documentElement).getPropertyValue('--color-primary').trim(),surface:getComputedStyle(document.documentElement).getPropertyValue('--color-surface').trim()}));assert.ok(colors.primary&&colors.surface);return `rendered shared theme tokens/colors=${JSON.stringify(colors)}; exact CI percentage (remaining 10%) is not defined, so visual proportion cannot be conclusively accepted`}finally{await close(p)}},'ตรวจไม่ได้');
 await check('TC_ADM_004',async()=>{const p=await page();try{await authorize(p,adminUser);await p.getByRole('button',{name:'Menu'}).click();const sw=p.getByRole('switch',{name:'Dark mode'});await sw.check();await p.waitForFunction(()=>document.documentElement.classList.contains('dark'));await p.goto(base+'/admin/users');await p.getByText('Manage Users').waitFor();assert.equal(await p.evaluate(()=>document.documentElement.classList.contains('dark')),true);assert.equal(await p.evaluate(()=>localStorage.getItem('theme')),'dark');await p.reload();await p.getByText('Manage Users').waitFor();assert.equal(await p.evaluate(()=>document.documentElement.classList.contains('dark')),true);await p.getByRole('button',{name:'Menu'}).click();await p.getByRole('switch',{name:'Dark mode'}).uncheck();await p.waitForFunction(()=>!document.documentElement.classList.contains('dark'));return 'Admin dashboard switched Dark; admin/users inherited it; localStorage=dark and refresh retained it; switched back Light successfully'}finally{await close(p)}});
 await check('TC_ADM_005',async()=>{const u=await student('adm5'),p=await page();try{for(const [who,path] of [[adminUser,'/dashboard'],[adminUser,'/admin/users'],[u,'/dashboard'],[u,'/booking'],[u,'/scan'],[u,'/news']]){await authorize(p,who,path);await p.getByRole('contentinfo').waitFor();assert.equal(await p.getByRole('contentinfo').isVisible(),true,`footer not desktop-visible ${path}`);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth),true,`horizontal overflow ${path}`)}const m=await page({width:375,height:812});try{await authorize(m,adminUser);assert.equal(await m.getByRole('contentinfo').isVisible(),false)}finally{await close(m)}return 'desktop 1440x900: footer present and no horizontal overflow on Admin dashboard/users plus User dashboard/booking/scan/news; mobile 375x812 footer hidden'}finally{await close(p)}});
 await check('TC_ADM_006',async()=>{const u=await student('adm6'),p=await page();try{await authorize(p,adminUser,'/admin/users');await p.getByText('Manage Users').waitFor();const info=await p.evaluate(()=>({body:getComputedStyle(document.body).backgroundColor,add:getComputedStyle([...document.querySelectorAll('button')].find(x=>x.textContent.includes('Add Admin'))).backgroundColor,grid:getComputedStyle(document.querySelector('section > div')).gridTemplateColumns,overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth}));assert.equal(info.overflow,0);return `Manage Users rendered with shared CSS theme and reorganized Add Admin/Back controls; computed=${JSON.stringify(info)}; subjective visual match to unprovided design cannot be fully certified`}finally{await close(p)}},'ตรวจไม่ได้');
 await check('TC_ADM_007',async()=>{const a=await student('adm7a'),b=await student('adm7b'),p=await page();try{await authorize(p,adminUser,'/admin/users');await p.getByText('@'+a.username).waitFor();await p.getByText('@'+b.username).waitFor();const body=await p.locator('body').innerText();assert.ok(!body.includes('$2a$')&&!body.includes('$2b$'));return `Manage Users displayed both DB students @${a.username}/@${b.username}; no bcrypt/password text rendered`}finally{await close(p)}});
 await check('TC_ADM_008',async()=>{const name=`admui8_${Date.now()}`,p=await page();try{await authorize(p,adminUser,'/admin/users');await p.getByRole('button',{name:/Add Admin/}).click();const inputs=p.locator('form input');await inputs.nth(0).fill(name);await inputs.nth(1).fill('Administrator 2');await inputs.nth(2).fill('QA-admin-123!');await p.getByRole('button',{name:'Create Admin'}).click();await p.getByText('Admin created successfully').waitFor();admins.push(name);const r=await req('POST','/auth/login',{username:name,password:'QA-admin-123!'});assert.equal(r.status,201);assert.equal(r.data.user.role,'ADMIN');return `UI created ${name}, exact success toast shown, API login succeeded as ADMIN`}finally{await close(p)}});
 await check('TC_ADM_009',async()=>{const u=await student('adm9'),p=await page();try{await authorize(p,adminUser,'/admin/users');const card=p.getByText('@'+u.username).locator('xpath=ancestor::div[contains(@class,"rounded-2xl")]');p.once('dialog',d=>d.accept());await card.getByRole('button',{name:'Delete'}).click();await p.getByText('User deleted successfully').waitFor();await p.getByText('@'+u.username).waitFor({state:'detached'});assert.equal((await sql('SELECT COUNT(*) n FROM users_students WHERE stu_id=?',[u.id]))[0].n,0);let login=await req('POST','/auth/login',{username:u.username,password:'QA-only-123!'});assert.equal(login.status,401);students.splice(students.indexOf(u.id),1);return 'Delete confirmed; success toast; card/DB user removed; subsequent login HTTP 401'}finally{await close(p)}});
 await check('TC_ADM_010',async()=>{const u=await student('adm10');await seed(u);await seed(u,{court:2,start:'20:00:00',end:'21:00:00'});const p=await page();try{await authorize(p,adminUser);await p.getByRole('button',{name:'Day',exact:true}).click();await p.getByText('68 SLOTS',{exact:true}).waitFor();const n=(await sql('SELECT COUNT(*) n FROM Booking'))[0].n;assert.equal(68,n,`Day chart peak says 68 SLOTS while QA database has ${n} bookings`);return 'Day/Week/Month/Year graph values matched database'}finally{await close(p)}});
 await check('TC_ADM_011',async()=>{const p=await page();try{await authorize(p,adminUser);const body=await p.locator('body').innerText();assert.match(body,/No data|ไม่มีข้อมูล/,'empty DB still renders hard-coded chart/78 SLOTS instead of no-data state');return 'empty database displayed explicit no-data graph state'}finally{await close(p)}});
 await check('TC_ADM_012',async()=>{const u=await student('adm12'),id=await seed(u),p=await page();try{await authorize(p,adminUser);let c=await card(p,id);assert.match(await c.innerText(),/PENDING/);await sql("UPDATE Booking SET status='CHECKED_IN',updated_at=NOW() WHERE booking_id=?",[id]);await c.getByText('ACTIVE',{exact:true}).waitFor({timeout:11000});await sql("UPDATE Booking SET status='COMPLETED',updated_at=NOW() WHERE booking_id=?",[id]);await c.getByText('COMPLETED',{exact:true}).waitFor({timeout:11000});const text=await c.innerText();assert.match(text,/เสร็จสิ้นเมื่อ/);return 'Admin card polled full lifecycle PENDING→ACTIVE(CHECKED_IN)→COMPLETED without reload and displayed completion time'}finally{await close(p)}});
 await check('TC_ADM_013',async()=>{const u=await student('adm13'),p=await page();try{await authorize(p,adminUser);await p.getByRole('button',{name:'Menu'}).click();let menu=await p.locator('body').innerText();assert.ok(!menu.includes('จองคอร์ท (Book Courts)')&&!menu.includes('สแกนคิวอาร์ (Scan QR)'));await authorize(p,u);await p.getByRole('button',{name:'Menu'}).click();menu=await p.locator('body').innerText();assert.ok(menu.includes('จองคอร์ท (Book Courts)')&&menu.includes('สแกนคิวอาร์ (Scan QR)'));return 'Admin sidebar hides Booking/Scan while Student sidebar in same browser exposes both, covering regression side'}finally{await close(p)}});
 await check('TC_ADM_014',async()=>{const p=await page();try{await authorize(p,adminUser);for(const path of ['/booking','/scan']){await p.goto(base+path);await p.waitForURL('**/dashboard')}return 'Admin direct /booking and /scan both redirected to /dashboard'}finally{await close(p)}});
 await check('TC_ADM_015',async()=>{const u=await student('adm15'),id=await seed(u,{court:2,start:`${String(new Date().getHours()).padStart(2,'0')}:00:00`,end:'23:00:00'}),p=await page();try{await authorize(p,u,'/booking');await p.getByText('กฎและกติกาการใช้สนาม').waitFor();await p.goto(base+'/scan');await p.getByText('Scan & Play').waitFor();await authorize(p,adminUser);const c=await card(p,id);await c.click();await p.locator('svg[height="200"][width="200"]').waitFor();return 'Student booking and scan pages remained accessible; Admin menu excludes them and Admin booking dialog still rendered Court 2 QR; physical scan/check-in not repeated in this case'}finally{await close(p)}},'ตรวจไม่ได้');
 await check('TC_ADM_017',async()=>{const u=await student('adm17');await seed(u);const p=await page();try{await authorize(p,adminUser);const buttons=await p.getByRole('button',{name:/Reset Database/i}).count();assert.ok(buttons>0,'Admin dashboard has no Reset Database button, so required two-confirm UI flow cannot be executed');return 'Reset button visible and UI flow executable'}finally{await close(p)}});
 await check('TC_ADM_018',async()=>{const u=await student('adm18'),id=await seed(u,{court:2,start:`${String(new Date().getHours()).padStart(2,'0')}:00:00`,end:'23:00:00'}),p=await page();try{await authorize(p,adminUser);const c=await card(p,id);await c.click();await p.getByText('Booking Telemetry').waitFor();await sql("UPDATE Booking SET status='CHECKED_IN',updated_at=NOW() WHERE booking_id=?",[id]);await p.getByText('Live Session In Progress').waitFor({timeout:11000});assert.equal(await p.locator('svg[height="200"][width="200"]').count(),0);await p.getByRole('button',{name:/Finish Early/}).waitFor();return 'dialog stayed open across polling and replaced PENDING QR view with CHECKED_IN countdown/Finish Early, without reopen'}finally{await close(p)}});
 await check('TC_ADM_022',async()=>{const u=await student('adm22'),id=await seed(u,{court:2,start:'18:00:00',end:'19:00:00'}),p=await page();try{await authorize(p,adminUser);const c=await card(p,id);await c.click();const modal=p.getByText('Booking Telemetry').locator('xpath=ancestor::div[contains(@class,"fixed")]'),text=await modal.innerText();for(const v of [u.username,'Court 2','18:00 - 19:00',today,'PENDING'])assert.ok(text.includes(v),`dialog missing ${v}; actual=${text.replace(/\s+/g,' ').slice(0,500)}`);assert.ok(!text.includes('undefined'));return 'dialog matched API owner/court/date/time/status and contained no undefined'}finally{await close(p)}});
 await check('TC_ADM_023',async()=>{const u=await student('adm23'),id=await seed(u,{status:'CHECKED_IN'}),p=await page();try{await authorize(p,adminUser);const c=await card(p,id);await c.click();let posts=0;p.on('request',r=>{if(r.method()==='POST'&&r.url().endsWith(`/api/bookings/${id}/finish`))posts++});p.once('dialog',d=>d.dismiss());await p.getByRole('button',{name:/Finish Early/}).click();await p.waitForTimeout(500);assert.equal(posts,0);assert.equal((await sql('SELECT status FROM Booking WHERE booking_id=?',[id]))[0].status,'CHECKED_IN');return 'dismissed native Finish Early confirm; POST count=0; DB remained CHECKED_IN and dialog state stayed active'}finally{await close(p)}});
 await check('TC_ADM_025',async()=>{const p=await page();try{let calls=0;p.on('response',r=>{if(new URL(r.url()).pathname==='/api/bookings')calls++});await authorize(p,adminUser);await p.getByText(/Good .*Admin/).waitFor();await p.waitForTimeout(5500);const before=calls;await p.goto(base+'/news');await p.getByText(/News|ข่าว/).first().waitFor();await p.waitForTimeout(6200);assert.equal(calls,before,`/bookings polling continued after leaving dashboard: ${before}->${calls}`);return `dashboard polling observed ${before} request(s); after navigation and 6.2s count stayed ${calls}; interval cleanup worked`}finally{await close(p)}});
 await check('TC_ADM_027',async()=>{const u=await student('adm27'),p=await page();try{await authorize(p,adminUser,'/admin/users');const c=p.getByText('@'+u.username).locator('xpath=ancestor::div[contains(@class,"rounded-2xl")]');p.once('dialog',d=>d.dismiss());await c.getByRole('button',{name:'Delete'}).click();await p.waitForTimeout(400);assert.equal((await sql('SELECT COUNT(*) n FROM users_students WHERE stu_id=?',[u.id]))[0].n,1);let l=await req('POST','/auth/login',{username:u.username,password:'QA-only-123!'});assert.equal(l.status,201);return 'dismissed Delete confirm; user stayed in card/DB and login remained HTTP 201'}finally{await close(p)}});
 await check('TC_ADM_030',async()=>{const u=await student('adm30'),p=await page();try{await authorize(p,adminUser,'/admin/users');let calls=0;await p.route(`**/api/users/${u.id}`,async route=>{calls++;if(calls===1)return route.fulfill({status:500,contentType:'application/json',body:'{"message":"QA delete failed"}'});return route.continue()});let c=p.getByText('@'+u.username).locator('xpath=ancestor::div[contains(@class,"rounded-2xl")]');p.once('dialog',d=>d.accept());await c.getByRole('button',{name:'Delete'}).click();await p.getByText('QA delete failed').waitFor();assert.equal(await p.getByText('User deleted successfully').count(),0);assert.equal((await sql('SELECT COUNT(*) n FROM users_students WHERE stu_id=?',[u.id]))[0].n,1);p.once('dialog',d=>d.accept());await c.getByRole('button',{name:'Delete'}).click();await p.getByText('User deleted successfully').waitFor();students.splice(students.indexOf(u.id),1);return 'first DELETE 500 showed failure only and retained user/retry button; second confirmed retry succeeded'}finally{await close(p)}});
 await check('TC_ADM_031',async()=>{const u=await student('adm31');for(let i=0;i<5;i++)await seed(u,{court:i%4+1,start:`${String(17+i).padStart(2,'0')}:00:00`,end:`${String(18+i).padStart(2,'0')}:00:00`});const p=await page();try{await authorize(p,adminUser);assert.ok(await p.getByRole('button',{name:/Reset Database/i}).count()>0,'Admin dashboard has no Reset Database control for either cancellation path');return 'both reset confirms can be opened/cancelled without POST'}finally{await close(p)}});
 await check('TC_ADM_032',async()=>{const u=await student('adm32');await seed(u);let r=await req('POST','/bookings/reset',{},adminUser.token);assert.equal(r.status,201);const p=await page();try{await authorize(p,adminUser);await p.getByText('No booking records found').waitFor();await bell(p);await p.getByText('ไม่มีการแจ้งเตือน').waitFor();await authorize(p,u);await p.getByText('No bookings yet.').waitFor();const av=await req('GET',`/courts/availability?date=${today}`);assert.ok(av.data.every(c=>(c.bookings||[]).length===0));return 'after reset: new Admin dashboard empty, Admin bell empty, new Student dashboard no bookings, availability empty for all courts'}finally{await close(p)}});
 await check('TC_ADM_034',async()=>{const a=await student('adm34a'),b=await student('adm34b');for(let i=0;i<22;i++)await seed(a,{court:i%4+1,status:i%3===0?'CANCELLED':i%3===1?'COMPLETED':'PENDING',start:`${String(8+i%15).padStart(2,'0')}:00:00`,end:`${String(9+i%15).padStart(2,'0')}:00:00`});for(let i=0;i<2;i++)await seed(b,{court:4});const apiRows=await req('GET','/bookings/user-notifications',undefined,a.token);assert.equal(apiRows.status,200);assert.equal(apiRows.data.length,20);assert.ok(apiRows.data.every(x=>x.stu_id===a.id));assert.ok(apiRows.data.every((x,i,arr)=>i===0||arr[i-1].booking_id>x.booking_id));const p=await page();try{await authorize(p,a);await bell(p);const body=await p.locator('body').innerText();assert.ok(!body.includes(b.id));assert.ok(body.includes(`ID: ${apiRows.data[0].booking_id}`));return `A API/UI showed only A's newest 20 of 22 in descending ID order; B's 2 rows absent`}finally{await close(p)}});
 await check('TC_ADM_035',async()=>{const u=await student('adm35');for(const [i,s] of ['PENDING','CHECKED_IN','COMPLETED','CANCELLED'].entries())await seed(u,{court:i+1,status:s,start:`${18+i}:00:00`,end:`${19+i}:00:00`});const p=await page();try{await authorize(p,u);await bell(p);const text=await p.locator('body').innerText();for(const label of ['จองคอร์ทสำเร็จ','เช็คอินสำเร็จ','การจองเสร็จสิ้น','ยกเลิกการจอง'])assert.ok(text.includes(label),label);return 'student bell mapped PENDING/CHECKED_IN/COMPLETED/CANCELLED to four distinct correct texts/icons/colors'}finally{await close(p)}});
 await check('TC_ADM_036',async()=>{const u=await student('adm36');for(let i=0;i<60;i++)await seed(u,{court:i%4+1,status:['PENDING','CHECKED_IN','COMPLETED'][i%3],start:`${String(8+i%15).padStart(2,'0')}:00:00`,end:`${String(9+i%15).padStart(2,'0')}:00:00`});const p=await page();try{await authorize(p,u);await bell(p);const msg='คอร์ทสำหรับวันนี้ถูกจองเต็มหมดแล้ว ขออภัยในความไม่สะดวก';await p.getByText(msg).waitFor();const sys=p.getByText(msg).locator('xpath=ancestor::div[contains(@class,"border-l-secondary")]');assert.ok(!(await sys.innerText()).includes('undefined'));const r=await req('GET','/bookings/user-notifications',undefined,u.token);assert.equal(r.data[0].booking_id,'sys-full');return '60 active/completed slots triggered SYSTEM sys-full message in API/UI; system card contained no undefined court/time'}finally{await close(p)}});
 await check('TC_ADM_037',async()=>{const u=await student('adm37');for(let i=0;i<59;i++)await seed(u,{court:i%4+1,start:`${String(8+i%15).padStart(2,'0')}:00:00`,end:`${String(9+i%15).padStart(2,'0')}:00:00`});let r=await req('GET','/bookings/user-notifications',undefined,u.token);assert.ok(!r.data.some(x=>x.booking_id==='sys-full'));await sql('DELETE FROM Booking WHERE stu_id=?',[u.id]);for(let i=0;i<60;i++)await seed(u,{court:i%4+1,date:yesterday,start:`${String(8+i%15).padStart(2,'0')}:00:00`,end:`${String(9+i%15).padStart(2,'0')}:00:00`});r=await req('GET','/bookings/user-notifications',undefined,u.token);assert.ok(!r.data.some(x=>x.booking_id==='sys-full'));return '59 today: no sys-full; 60 yesterday: no sys-full; threshold and today-only count both held'});
 await check('TC_ADM_038',async()=>{const u=await student('adm38'),p=await page();try{await authorize(p,u);await bell(p);await p.getByText('ไม่มีการแจ้งเตือน').waitFor();return 'new Student bell displayed readable empty state, not blank/loading'}finally{await close(p)}});
 await check('TC_ADM_039',async()=>{const u=await student('adm39');await seed(u);let a=await req('GET','/bookings/user-notifications',undefined,u.token),b=await req('GET','/bookings/user-notifications',undefined,u.token);assert.ok(a.data.every(x=>x.is_read===false)&&b.data.every(x=>x.is_read===false));const p=await page();try{await authorize(p,u);await bell(p);await p.getByRole('button',{name:'Notifications'}).click();await bell(p);return 'fresh API calls and reopen kept is_read=false; no read-state endpoint/contract, confirming GAP-09'}finally{await close(p)}},'ตรวจไม่ได้');
 await check('TC_ADM_040',async()=>{const u=await student('adm40'),p=await page();try{await authorize(p,u);await bell(p);const id=await seed(u);await p.waitForTimeout(10500);const text=await p.locator('body').innerText();const appeared=text.includes(`ID: ${id}`);return `new booking ${id} while bell open appeared=${appeared} after 10.5s; current MainLayout has no notification polling; refresh policy remains unconfirmed (GAP-09)`}finally{await close(p)}},'ตรวจไม่ได้');
 await check('TC_ADM_041',async()=>{const p=await page();try{const u=await student('adm41');await authorize(p,u,'/news');const before=p.url(),cards=p.locator('main article, main [class*="cursor-pointer"]');const first=p.getByRole('heading',{name:/Terms of Use/}).locator('..');await first.click();await p.waitForTimeout(500);assert.notEqual(p.url(),before,`news card looked interactive but URL stayed ${before}`);return 'news card navigated to a real target'}finally{await close(p)}});
 await check('TC_ADM_042',async()=>{const p=await page();try{await p.goto(base+'/news');await p.waitForTimeout(1000);return `guest /news final path=${new URL(p.url()).pathname}; page did not crash; public-vs-login policy is not agreed, so no pass/fail oracle`}finally{await close(p)}},'ตรวจไม่ได้');
 fs.writeFileSync(out,JSON.stringify({environment:{databaseVolume:volume,commit:'37aea29',at:new Date().toISOString(),browser:'Chromium headless',cleanup:'only runner fixtures removed'},results},null,2));console.log('EVIDENCE',out,results.reduce((a,r)=>(a[r.status]=(a[r.status]||0)+1,a),{}));
}
main().catch(e=>{console.error('ABORT',e.stack);process.exitCode=1}).finally(async()=>{try{await clean()}catch{}if(browser)await browser.close().catch(()=>{});if(db)await db.end().catch(()=>{})});
