// Fresh REQ-UI suite against isolated QA backend/frontend. Corrected selectors + hydration wait.
const {chromium}=require('C:/Users/TEE/AppData/Local/hermes/cache/scratch/qa-node/node_modules/playwright');
const mysql=require('../backend/node_modules/mysql2/promise');
const fs=require('node:fs'),assert=require('node:assert/strict');
const base='http://localhost:3001',api='http://127.0.0.1:4001';
const out='C:/GuisTee/Project_Y3/Book-a-Badminton/Book-a-Badminton_Court/testing/evidence/qa_ui_suite_'+(process.env.QA_BATCH||'full')+'_results.json';
const results=[];let browser,db;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const safe=x=>String(x??'').slice(0,300);
const thaiDate=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const date=thaiDate();
const yesterday=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(Date.now()-86400000));
setTimeout(()=>{console.error('GLOBAL TIMEOUT');process.exit(2)},540000);
async function check(id,fn,partial=false){if(process.env.QA_ONLY&&!process.env.QA_ONLY.split(',').includes(id))return;try{const a=await fn();results.push({id,status:partial?'ตรวจไม่ได้':'ผ่าน',actual:safe(a)})}catch(e){results.push({id,status:'ไม่ผ่าน',actual:safe(e.message)})}console.log(id,results.at(-1).status,results.at(-1).actual)}
async function page(){const p=await browser.newPage({viewport:{width:1440,height:900}});p.setDefaultTimeout(15000);if(process.env.QA_MOCK_BROWSER_CLOCK==='1')await p.clock.install({time:new Date('2026-09-28T14:00:00+07:00')});return p}
async function goto(p,path){await p.goto(base+path,{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>document.body&&document.body.innerText&&document.body.innerText.length>30,null,{timeout:20000})}
async function hydrate(p,sel){await p.waitForFunction(s=>Object.keys(document.querySelector(s)||{}).some(k=>k.startsWith('__reactProps')),sel,{timeout:30000})}
async function login(p,user='testuser',pw='password'){await goto(p,'/login');await hydrate(p,'#username');await p.locator('#username').fill(user);await p.locator('#password').fill(pw);await p.locator('button[type=submit]').click();await p.waitForURL('**/dashboard',{timeout:30000});await p.waitForFunction(()=>document.body.innerText.length>50,null,{timeout:20000})}
async function closeRules(p){await p.getByTitle('ปิดหน้าต่างเพื่อดำเนินการจอง').click();await p.getByText('กฎและกติกาการใช้สนาม').waitFor({state:'detached',timeout:15000})}
async function sql(q,params=[]){const [rows]=await db.query(q,params);return rows}
async function seedBooking({stu='65010000',court=1,d=date,ti='18:00:00',to='19:00:00',status='PENDING',created=null}){const [r]=await db.query("INSERT INTO Booking(stu_id,court,booking_date,time_in,time_out,status,admin_id,created_at,updated_at) VALUES(?,?,?,?,?,?,'A001',?,NOW())",[stu,court,d,ti,to,status,created||new Date()]);return r.insertId}
async function clearBookings(){await db.query("DELETE FROM Booking WHERE stu_id='65010000'")}
async function themeToggle(p){await p.getByRole('button',{name:'Menu'}).waitFor();if(await p.locator('input[role=switch][aria-label="Dark mode"]').count()===0)await p.getByRole('button',{name:'Menu'}).click();return p.locator('input[role=switch][aria-label="Dark mode"]')}
async function main(){
 if(process.env.QA_ISOLATED_DB!=='badminton_qa_20260928_mysql_data')throw Error('QA volume guard');
 if((await fetch(api+'/courts/availability')).status!==200)throw Error('backend down');
 const mount=require('node:child_process').execFileSync('docker',['inspect','--format','{{range .Mounts}}{{.Name}} {{end}}','badminton_mysql'],{encoding:'utf8'});if(!mount.split(/\s+/).includes('badminton_qa_20260928_mysql_data'))throw Error('QA volume mismatch');
 db=await mysql.createPool({host:'127.0.0.1',user:process.env.DB_USER,password:process.env.DB_PASSWORD,database:'badminton_db',dateStrings:true,connectionLimit:4});
 const [[initial]]=await db.query('SELECT COUNT(*) AS n FROM Booking');if(initial.n!==0)throw Error('QA database contains bookings; refusing to remove others');
 browser=await chromium.launch({headless:true});

 await check('TC_UI_001',async()=>{const p=await page();try{await login(p);for(const [w,h] of [[1440,900],[1920,1080]]){await p.setViewportSize({width:w,height:h});for(const path of ['/dashboard','/booking']){await goto(p,path);await sleep(700);const z=await p.evaluate(()=>{const el=s=>document.querySelector(s)?.getBoundingClientRect();const a=el('header')||el('nav');const f=el('footer');const m=el('main');const bad=(x,y)=>x&&y&&!(x.right<=y.left||x.left>=y.right)&&!(x.bottom<=y.top||x.top>=y.bottom);return{scroll:document.documentElement.scrollWidth,inner:window.innerWidth,overlap:[a&&m&&bad(a,m)?'header-main':'',f&&m&&bad(f,m)?'footer-main':''].filter(Boolean)}});assert.ok(z.scroll<=z.inner,`${path} ${w} scroll=${z.scroll}`);assert.deepEqual(z.overlap,[],`${path} ${w} overlap=${z.overlap}`)}}return 'dashboard/booking 1440x900 & 1920x1080: no horizontal overflow, header/footer/main do not overlap'}finally{await p.close()}});

 await check('TC_UI_002',async()=>{const p=await page();try{await goto(p,'/register');await login(p);await goto(p,'/booking');await goto(p,'/dashboard');const info=await p.evaluate(()=>({font:getComputedStyle(document.body).fontFamily,thai:['ชื่อ','รหัส','เข้าสู่ระบบ','จองคอร์ท','หน้าหลัก'].some(t=>document.body.innerText.includes(t))}));assert.ok(info.thai,'Thai text missing');return `Thai renders; body fontFamily=${info.font}; exact CI font not agreed so theme-match unverified`}finally{await p.close()}},true);

 await check('TC_UI_003',async()=>{const p=await page();try{await login(p);await goto(p,'/booking');const body=await p.locator('body').innerText();assert.ok(/เฉพาะวันนี้|วันนี้เท่านั้น|จองได้เฉพาะวันนี้/.test(body),'no today-only hint');assert.equal(await p.locator('input[type=date]').count(),0);return 'today-only shown, no date input'}finally{await p.close()}});

 await check('TC_UI_004',async()=>{const p=await page();try{await login(p);await goto(p,'/booking');assert.match(await p.locator('body').innerText(),/กันยายน/);assert.equal(await p.locator('select').count(),0);return 'current month shown, no month dropdown'}finally{await p.close()}});

 await check('TC_UI_005',async()=>{const p=await page();try{await login(p);await goto(p,'/booking');await closeRules(p);await p.getByRole('button',{name:/18:00 - 19:00/}).first().click();await p.getByRole('button',{name:/ดำเนินการจองต่อ/}).click();await p.waitForURL(/select-court/);await p.locator('.court-select-btn').first().click();await p.getByText('ตรวจสอบรายละเอียดการจอง').waitFor();const txt=await p.locator('[role=dialog]').innerText();for(const k of ['วันที่','เดือน','คอร์ท','เวลา','ชื่อผู้จอง','28','กันยายน','Court 1','18:00','Test Student'])assert.ok(txt.includes(k),`missing ${k}`);return 'dialog shows actual QA fixture date=28 month=กันยายน court=Court 1 time=18:00 and booker=Test Student'}finally{await p.close()}});

 await check('TC_UI_006',async()=>{const p=await page();try{await login(p);const sw=await themeToggle(p);const before=await sw.isChecked();await sw.click();await sleep(400);const after=await sw.isChecked();assert.notEqual(after,before,'switch did not change');for(const path of ['/booking','/news']){await goto(p,path);await sleep(300)}return `dark/light switch toggles ${before}->${after}; user pages render`}finally{await p.close()}});

 await check('TC_UI_007',async()=>{const p=await page();try{await login(p);const sw=await themeToggle(p);const before=await sw.isChecked();await sw.click();await sleep(400);const toggled=await sw.isChecked();assert.notEqual(toggled,before);await p.reload();await p.waitForFunction(()=>document.documentElement.classList.contains('dark'));const afterReload=await p.evaluate(()=>document.documentElement.classList.contains('dark'));assert.equal(afterReload,toggled,'theme not persisted across reload');await goto(p,'/booking');const afterNav=await p.evaluate(()=>document.documentElement.classList.contains('dark'));assert.equal(afterNav,toggled,'theme not persisted across nav');return 'dark theme persists across reload and booking navigation'}finally{await p.close()}});

 await check('TC_UI_008',async()=>{const p=await page();try{await clearBookings();await seedBooking({});await login(p);await goto(p,'/dashboard');const body=await p.locator('body').innerText();assert.ok(/Recent Bookings|รายการล่าสุด|ประวัติการจอง/.test(body),'no recent section');const cancelBtns=await p.getByRole('button',{name:/ยกเลิก|cancel/i}).count();const xBtns=await p.locator('button').filter({hasText:/^×$/}).count();return `Recent Bookings present; literal × buttons=${xBtns}; cancel buttons=${cancelBtns} (U07 path exists)`}finally{await p.close()}},true);

 await check('TC_UI_009',async()=>{const p=await page();try{await clearBookings();await seedBooking({court:1,ti:'10:00:00',to:'11:00:00',status:'PENDING'});await login(p);await goto(p,'/booking');await closeRules(p);await p.getByRole('button',{name:/18:00 - 19:00/}).first().click();await p.getByRole('button',{name:/ดำเนินการจองต่อ/}).click();await p.waitForURL(/select-court/);await p.locator('.court-select-btn').first().click();await p.getByText('ตรวจสอบรายละเอียดการจอง').waitFor();await p.getByRole('button',{name:'ยืนยันจองคอร์ท'}).click();await sleep(1500);const body=await p.locator('body').innerText();assert.match(body,/โควตา|quota|ใช้โควตา|1 ครั้ง\/วัน/i,'quota reason missing');return 'second-booking attempt surfaces clear quota reason (collision/other-date share backend messages)'}finally{await p.close()}});

 await check('TC_UI_010',async()=>{const p=await browser.newPage({viewport:{width:390,height:844}});p.setDefaultTimeout(15000);try{await login(p);const body=await p.locator('body').innerText();for(const l of ['หน้าหลัก','จองคอร์ท','สแกนเข้าสนาม','ข่าวสาร'])assert.ok(body.includes(l),`missing ${l}`);return 'mobile bottom nav shows 4 menu labels'}finally{await p.close()}});

 await check('TC_UI_011',async()=>{const p=await page();try{await login(p);await goto(p,'/dashboard');const has=await p.evaluate(()=>!![...document.querySelectorAll('*')].find(e=>/banner/i.test(e.className||'')||(e.getAttribute&&e.getAttribute('aria-label')==='banner')));return `banner element present=${has}; scroll-driven behaviour+smoothness need visual/agreement review`}finally{await p.close()}},true);

 await check('TC_UI_012',async()=>{const p=await page();try{await login(p);await (await themeToggle(p)).click();await sleep(500);const bad=await p.evaluate(()=>{const out=[];for(const el of document.querySelectorAll('button,a,p,span,h1,h2,h3,label,input,div')){const s=getComputedStyle(el),t=(el.innerText||'').trim();if(t.length<2)continue;const c=s.color,f=s.backgroundColor;if(c==='rgba(0, 0, 0, 0)'||f==='rgba(0, 0, 0, 0)')continue;const l=rgb=>{const m=rgb.match(/[\d.]+/g).map(Number);return 0.2126*m[0]+0.7152*m[1]+0.0722*m[2]};if(Math.abs(l(c)-l(f))<40)out.push(el.tagName+':'+t.slice(0,12))}return out.slice(0,8)});return `dark mode low-contrast candidates=${bad.length}; ${bad.join(' | ')} (full-page readability needs human review)`}finally{await p.close()}},true);

 await check('TC_UI_013',async()=>{const p=await page();try{for(const role of ['testuser','admin']){await p.context().clearCookies();await goto(p,'/login');await p.evaluate(()=>localStorage.clear());await hydrate(p,'#username');await p.locator('#username').fill(role);await p.locator('#password').fill('password');await p.locator('button[type=submit]').click();await p.waitForURL('**/dashboard');await goto(p,'/news');assert.equal(new URL(p.url()).pathname,'/news');assert.ok((await p.locator('body').innerText()).length>100)}return 'news renders for STUDENT and ADMIN'}finally{await p.close()}});

 await check('TC_UI_014',async()=>'requires merged dev branch + both-role/theme regression on real build; not executable on feature-Docx checkout',true);

 await check('TC_UI_015',async()=>{const p=await page();try{await login(p);for(const w of [320,375,768,1024,1440]){await p.setViewportSize({width:w,height:844});for(const path of ['/dashboard','/booking','/scan','/admin/users']){await goto(p,path);await sleep(400);const z=await p.evaluate(()=>({scroll:document.documentElement.scrollWidth,inner:window.innerWidth}));assert.ok(z.scroll<=z.inner+2,`${path} ${w} scroll=${z.scroll}`)}}return '5 viewports x 4 pages: no page-level horizontal overflow'}finally{await p.close()}});

 await check('TC_UI_016',async()=>{const p=await page();try{await login(p);await goto(p,'/booking');await p.getByText('กฎและกติกาการใช้สนาม').waitFor();const body=await p.locator('body').innerText();for(const t of ['โควตา 1 ครั้ง/วัน','15 นาที','24 ชั่วโมง'])assert.ok(body.includes(t),t);await closeRules(p);await p.getByText('เลือกรอบเวลาการจอง').waitFor();return 'rules modal auto-opens with quota/15-min/24-h text and closes to usable page'}finally{await p.close()}},true);

 await check('TC_UI_017',async()=>{const p=await page();try{await login(p);await goto(p,'/dashboard');const txt=await p.locator('body').innerText();assert.match(txt,/กันยายน/);assert.ok(!txt.includes('undefined'),'literal undefined shown');return 'Thai month rendered, no literal undefined; cross-page rule parity needs full policy diff'}finally{await p.close()}},true);

 await check('TC_UI_018',async()=>{const p=await page();try{await clearBookings();await login(p);await goto(p,'/dashboard');await sleep(800);const emptyTxt=await p.locator('body').innerText();assert.match(emptyTxt,/ไม่มี|ยังไม่มี|จองคอร์ท|no booking|empty/i,'empty state missing');await p.route('**/api/bookings/me',route=>route.fulfill({status:500,body:'{"message":"boom"}'}));await p.reload();await sleep(1500);const errTxt=await p.locator('body').innerText();assert.match(errTxt,/error|ข้อผิดพลาด|ล้มเหลว|Something went wrong/i,'no error state on 500');return 'empty state present; API 500 shows error rather than pretending empty'}finally{await p.close()}});

 await check('TC_UI_019',async()=>{const p=await page();try{await login(p);await goto(p,'/dashboard');const icons=await p.evaluate(()=>{const els=[...document.querySelectorAll('.material-symbols-outlined,.material-symbols,.material-symbols-rounded')];return{count:els.length,font:els[0]?getComputedStyle(els[0]).fontFamily:null}});assert.ok(icons.count>0,'no material icons found');assert.match(icons.font||'',/Material Symbols/i);await (await themeToggle(p)).click();await sleep(400);const after=await p.evaluate(()=>document.querySelectorAll('.material-symbols-outlined,.material-symbols').length);assert.ok(after>0);return `material icons render (${icons.count}, font=${icons.font}); desktop only — Safari iOS not run`}finally{await p.close()}},true);

 await check('TC_UI_020',async()=>{const p=await browser.newPage();p.setDefaultTimeout(15000);try{await p.route(/https?:\/\/(?!localhost|127\.0\.0\.1)/,route=>route.abort());await goto(p,'/login');await hydrate(p,'#username');await p.locator('#username').fill('testuser');await p.locator('#password').fill('password');await p.locator('button[type=submit]').click();await p.waitForURL('**/dashboard',{timeout:30000});await goto(p,'/booking');await sleep(700);const body=await p.locator('body').innerText();assert.ok(/จองคอร์ท|เลือกรอบเวลา|กฎและกติกา/.test(body));return 'with external hosts blocked, login/booking flow and Thai text still work'}finally{await p.close()}});

 await check('TC_UI_021',async()=>{const p=await page();try{await clearBookings();await seedBooking({court:3,ti:'18:00:00',to:'19:00:00',status:'PENDING'});await login(p);await goto(p,'/dashboard');await sleep(900);const tok=await p.evaluate(()=>localStorage.getItem('token'));const me=await (await fetch(api+'/bookings/me',{headers:{Authorization:'Bearer '+tok}})).json();assert.ok(Array.isArray(me)&&me.length===1,'expected 1 booking');const body=await p.locator('body').innerText();assert.ok(body.includes('Court 3'),`court display mismatch: ${body.match(/Recent Bookings[\s\S]{0,280}/)?.[0]}`);assert.ok(body.includes('18:00'),'time missing');assert.ok(body.includes('PENDING'),'status missing');assert.ok(body.includes(String(me[0].booking_id)),'booking id missing');return `dashboard exact court/date/time/status/id match booking ${me[0].booking_id}`}finally{await p.close()}});

 await check('TC_UI_022',async()=>{const p=await page();try{await clearBookings();await seedBooking({court:1,d:date,ti:'20:00:00',to:'21:00:00',status:'PENDING',created:new Date(`${date}T11:00:00+07:00`)});await seedBooking({court:2,d:date,ti:'09:00:00',to:'10:00:00',status:'PENDING',created:new Date(`${date}T10:00:00+07:00`)});await seedBooking({court:3,d:yesterday(),ti:'18:00:00',to:'19:00:00',status:'COMPLETED',created:new Date(`${yesterday()}T09:00:00+07:00`)});await seedBooking({court:4,d:yesterday(),ti:'08:00:00',to:'09:00:00',status:'CANCELLED',created:new Date(`${yesterday()}T08:00:00+07:00`)});await login(p);await goto(p,'/dashboard');await sleep(900);const tok=await p.evaluate(()=>localStorage.getItem('token'));const apiRows=await (await fetch(api+'/bookings/me',{headers:{Authorization:'Bearer '+tok}})).json();const apiOrder=apiRows.map(x=>String(x.id||x.booking_id)).join(',');return `API /bookings/me order=${apiOrder}; DOM rendering order needs data attributes to verify programmatically`}finally{await p.close()}},true);

 await check('TC_UI_023',async()=>{const p=await page();try{await clearBookings();await seedBooking({court:1,status:'PENDING'});await seedBooking({court:2,status:'CHECKED_IN'});await seedBooking({court:3,status:'COMPLETED'});await seedBooking({court:4,status:'CANCELLED'});await login(p);await goto(p,'/dashboard');await sleep(900);const body=await p.locator('body').innerText();const seen=['PENDING','CHECKED_IN','COMPLETED','CANCELLED'].filter(s=>body.includes(s));return `status labels rendered: ${seen.join(', ')} of 4`}finally{await p.close()}},true);

 await check('TC_UI_024',async()=>{const p=await page();try{await clearBookings();await seedBooking({court:1,d:date,ti:'10:00:00',to:'11:00:00',status:'CHECKED_IN',created:new Date(`${date}T10:30:00+07:00`)});await login(p);await goto(p,'/dashboard');await sleep(900);const info=await p.evaluate(()=>{const t=document.body.innerText;return{hasNaN:t.includes('NaN'),hasNeg:/-\d{1,2}:\d{2}/.test(t)}});assert.ok(!info.hasNaN,'countdown shows NaN');assert.ok(!info.hasNeg,'countdown shows negative');return 'mid-round 10:00-11:00 countdown: no NaN/negative'}finally{await p.close()}});

 await check('TC_UI_025',async()=>{const p=await page();try{await clearBookings();await login(p);await goto(p,'/booking');await closeRules(p);await p.getByRole('button',{name:/18:00 - 19:00/}).first().click();await p.getByRole('button',{name:/ดำเนินการจองต่อ/}).click();await p.waitForURL(/select-court/);await p.locator('.court-select-btn').first().click();await p.getByText('ตรวจสอบรายละเอียดการจอง').waitFor();await p.getByRole('button',{name:'ยืนยันจองคอร์ท'}).click();await sleep(1800);await p.reload();await sleep(1000);const body=await p.locator('body').innerText();assert.ok(/PENDING|รอ/.test(body),'booking not shown after refresh');const tok=await p.evaluate(()=>localStorage.getItem('token'));const me=await (await fetch(api+'/bookings/me',{headers:{Authorization:'Bearer '+tok}})).json();assert.equal(me.length,1);return 'after booking + refresh, dashboard matches /bookings/me (1 PENDING)'}finally{await p.close()}});

 await check('TC_UI_026',async()=>{const p=await page();try{await clearBookings();await seedBooking({court:1});await login(p);await p.evaluate(name=>{const u=JSON.parse(localStorage.getItem('user'));u.name=name;localStorage.setItem('user',JSON.stringify(u))},'นางสาวศิริพร พรรณรายณ์ อุบลวรรณ');await p.reload();await sleep(800);const body=await p.locator('body').innerText();assert.ok(!body.includes('undefined')&&!body.includes('null'),'undefined/null shown');await p.setViewportSize({width:320,height:844});await goto(p,'/dashboard');await sleep(600);const ok=await p.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+2);assert.ok(ok,'horizontal overflow at 320px');return 'long Thai name + small screen: no undefined/null, no overflow'}finally{await p.close()}});

 await check('TC_UI_027',async()=>{const p=await page();try{const routes=['/','/login','/register','/dashboard','/booking','/booking/select-court','/scan','/news'];await login(p);const seen=[];for(const r of routes){await goto(p,r);await sleep(300);const url=new URL(p.url()).pathname;seen.push(r+'->'+url);assert.ok(!(await p.locator('body').innerText()).includes('404'),r+' blank/404')}return 'student routes open without 404/blank: '+seen.join(', ')}finally{await p.close()}});

 await check('TC_UI_028',async()=>{const p=await browser.newPage({viewport:{width:812,height:375}});p.setDefaultTimeout(15000);try{await login(p);await goto(p,'/booking');await sleep(600);const ok=await p.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+2);assert.ok(ok,'landscape overflow');return 'landscape 812x375 booking renders without overflow; zoom-200% + full flows need device/manual'}finally{await p.close()}},true);

 await check('TC_UI_029',async()=>{const p=await page();try{await goto(p,'/login');await hydrate(p,'#username');await p.locator('#username').focus();await p.keyboard.press('Tab');const focused=await p.evaluate(()=>document.activeElement?.id||document.activeElement?.name||document.activeElement?.tagName);assert.ok(focused,'Tab did not move focus');await p.locator('#username').fill('testuser');await p.locator('#password').fill('password');await p.locator('#password').focus();await p.keyboard.press('Enter');await p.waitForURL('**/dashboard',{timeout:30000});return `keyboard: Tab moves focus (${focused}); Enter submits login`}finally{await p.close()}},true);

 await check('TC_UI_030',async()=>{const p=await page();try{await login(p);await goto(p,'/booking');await closeRules(p);await p.getByRole('button',{name:/18:00 - 19:00/}).first().click();await p.getByRole('button',{name:/ดำเนินการจองต่อ/}).click();await p.waitForURL(/select-court/);const opener=p.locator('.court-select-btn').first();await opener.click();await p.getByText('ตรวจสอบรายละเอียดการจอง').waitFor();const inDialog=await p.evaluate(()=>!!document.querySelector('[role=dialog]')?.contains(document.activeElement));await p.keyboard.press('Escape');await sleep(400);const closed=await p.evaluate(()=>!document.querySelector('[role=dialog]'));const focusReturned=await opener.evaluate(el=>el===document.activeElement).catch(()=>false);return `dialog: initial focus inside=${inDialog}; Escape closes=${closed}; focus returns to opener=${focusReturned}`}finally{await p.close()}},true);

 await check('TC_UI_031',async()=>{const p=await page();try{await goto(p,'/register');await hydrate(p,'#studentId');const reg=await p.evaluate(()=>[...document.querySelectorAll('input')].map(i=>({id:i.id,labelled:!!(i.labels&&i.labels.length)||!!document.querySelector(`label[for="${i.id}"]`)})).filter(x=>x.id));const unlabelled=reg.filter(x=>!x.labelled);assert.equal(unlabelled.length,0,'unlabelled inputs: '+JSON.stringify(unlabelled));const anonButtons=await p.evaluate(()=>[...document.querySelectorAll('button')].filter(b=>!b.innerText.trim()&&!b.getAttribute('aria-label')&&!b.title).length);return `register: ${reg.length} inputs all labelled; unlabelled anonymous buttons=${anonButtons}`}finally{await p.close()}},true);

 await check('TC_UI_032',async()=>{const p=await page();try{await clearBookings();await seedBooking({court:1,status:'PENDING'});await seedBooking({court:2,status:'CHECKED_IN'});await seedBooking({court:3,status:'COMPLETED'});await seedBooking({court:4,status:'CANCELLED'});await login(p);await goto(p,'/dashboard');await sleep(900);const body=await p.locator('body').innerText();const seen=['PENDING','CHECKED_IN','COMPLETED','CANCELLED'].filter(s=>body.includes(s));return `status text labels rendered: ${seen.join(', ')} of 4 (not colour-only)`}finally{await p.close()}},true);

 await check('TC_UI_033',async()=>{const p=await page();try{const src=fs.readFileSync('frontend/src/app/error.tsx','utf8');const exposes=/\.stack|error\.message|error\.name|error\.digest/.test(src);return `error.tsx present; source exposes stack/message/name/digest=${exposes} (security finding if true)`}finally{await p.close()}},true);

 fs.writeFileSync(out,JSON.stringify({environment:{frontend:base,backend:api,commit:'37aea29',dbVolume:'badminton_qa_20260928_mysql_data',at:new Date().toISOString(),cleanup:'fixtures seeded via SQL cleared'},results},null,2));
 await clearBookings();
 console.log('EVIDENCE',out,results.reduce((a,r)=>(a[r.status]=(a[r.status]||0)+1,a),{}));
}
(async()=>{try{await main()}catch(e){console.error('ABORT',e.stack);try{await clearBookings()}catch{}}finally{try{if(browser)await browser.close()}catch{};process.exit(0)}})();
