const assert=require('node:assert/strict'),mysql=require('../backend/node_modules/mysql2/promise'),fs=require('node:fs'),{execFileSync}=require('node:child_process');
const root='http://127.0.0.1:4001',volume='badminton_qa_20260928_mysql_data',out='C:/GuisTee/Project_Y3/Book-a-Badminton/Book-a-Badminton_Court/testing/evidence/qa_conc_api_focused_results.json',ids=['86010001','86010002'];let db,t=[],created=[];const results=[];const date=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok'}).format(new Date());
async function req(method,path,body,token){const r=await fetch(root+path,{method,headers:{...(body===undefined?{}:{'content-type':'application/json'}),...(token?{authorization:'Bearer '+token}:{})},body:body===undefined?undefined:JSON.stringify(body)});let data;try{data=await r.json()}catch{data=null}return {status:r.status,data}}
async function ck(id,fn,partial=false){try{const s=await fn();results.push({id,status:partial?'ตรวจไม่ได้':'ผ่าน',actual:String(s).slice(0,600)})}catch(e){results.push({id,status:'ไม่ผ่าน',actual:String(e.message).slice(0,600)})}console.log(id,results.at(-1).status,results.at(-1).actual)}
const rows=async(q,p=[])=> (await db.query(q,p))[0];
async function cleanupBookings(){await db.query('DELETE FROM Booking WHERE stu_id IN (?,?)',ids)}
async function race(a,b){return Promise.all([a(),b()])}
async function main(){assert.equal(process.env.QA_ISOLATED_DB,volume);assert.ok(execFileSync('docker',['inspect','--format','{{range .Mounts}}{{.Name}} {{end}}','badminton_mysql'],{encoding:'utf8'}).split(/\s+/).includes(volume));db=await mysql.createConnection({host:'127.0.0.1',port:Number(process.env.DB_PORT||13306),user:process.env.DB_USER,password:process.env.DB_PASSWORD,database:'badminton_db'});assert.equal((await rows('SELECT COUNT(*) n FROM Booking'))[0].n,0);for(let id of ids){let x=await req('POST','/auth/register',{studentId:id,username:'qaconc_'+id,name:'Conc QA',email:`qaconc${id}@kmitl.ac.th`,phone:'0812345678',major:'IT',year:3,password:'QA-only-123!'});assert.equal(x.status,201);t.push(x.data.access_token)}let adm=(await req('POST','/auth/login',{username:'admin',password:'password'})).data.access_token;
await ck('TC_CONC_001',async()=>{let payload={courtId:1,date,startTime:'22:00'},r=await race(()=>req('POST','/bookings',payload,t[0]),()=>req('POST','/bookings',payload,t[1]));let status=r.map(x=>x.status).sort((a,b)=>a-b);assert.deepEqual(status,[201,400]);let data=await rows('SELECT count(*) n FROM Booking WHERE booking_date=? AND court=1 AND time_in=?',[date,'22:00:00']);assert.equal(data[0].n,1);await cleanupBookings();return `same court simultaneous ${status.join('/')}, DB 1, no 500`});
await ck('TC_CONC_002',async()=>{let r=await race(()=>req('POST','/bookings',{courtId:1,date,startTime:'22:00'},t[0]),()=>req('POST','/bookings',{courtId:2,date,startTime:'22:00'},t[0]));let status=r.map(x=>x.status).sort((a,b)=>a-b);assert.deepEqual(status,[201,400]);assert.equal((await rows('SELECT count(*) n FROM Booking WHERE stu_id=?',[ids[0]]))[0].n,1);await cleanupBookings();return `same user two courts ${status.join('/')}, DB 1`});
await ck('TC_CONC_007',async()=>{let r=await race(()=>req('POST','/bookings',{courtId:1,date,startTime:'22:00'},t[0]),()=>req('POST','/bookings',{courtId:2,date,startTime:'22:00'},t[1]));assert.deepEqual(r.map(x=>x.status).sort((a,b)=>a-b),[201,201]);assert.equal((await rows('SELECT count(*) n FROM Booking WHERE stu_id IN (?,?)',ids))[0].n,2);return 'different users/courts 201/201, DB 2'});
await ck('TC_CONC_019',async()=>{let before=(await rows('SELECT COUNT(*) n FROM Booking'))[0].n;let r=await Promise.all([req('PUT','/auth/login',{}),req('DELETE','/courts'),req('POST','/bookings/abc/cancel',{},t[0]),req('GET','/route-nonexistent')]);let status=r.map(x=>x.status);assert.ok(status.every(x=>x>=400&&x<500),`statuses=${status}`);assert.equal((await rows('SELECT COUNT(*) n FROM Booking'))[0].n,before);return `bad method/route/id statuses=${status}; DB count unchanged`});
await ck('TC_CONC_020',async()=>{let extra=await req('POST','/bookings',{courtId:3,date,startTime:'22:00',status:'CHECKED_IN',admin_id:'fake'},t[0]);assert.equal(extra.status,400);let s=await rows('SELECT strikes,banned_until FROM users_students WHERE stu_id=?',[ids[0]]);assert.equal(s[0].strikes,0);return 'extra status/admin_id to active-quota user rejected 400; register extras/created booking owner not retested'},true);
await ck('TC_CONC_021',async()=>{let me=await req('GET','/bookings/me',undefined,t[0]),all=await req('GET','/bookings',undefined,adm),av=await req('GET','/courts/availability?date='+date);assert.equal(me.status,200);assert.equal(all.status,200);assert.equal(av.status,200);assert.ok(me.data.length&&all.data.length&&av.data.length);assert.equal(me.data[0].id,me.data[0].booking_id);assert.equal(all.data[0].id,all.data[0].booking_id);let b=av.data.flatMap(c=>c.bookings||[]);assert.ok(b.some(x=>x.start_time==='22:00:00'));return `me/all id=booking_id, availability start_time=22:00:00; IDs me=${me.data[0].id},all=${all.data[0].id}`});
await ck('TC_CONC_022',async()=>{let x=await Promise.all([req('POST','/bookings',{courtId:1,date,startTime:'10:30'},t[0]),req('GET','/bookings/me',undefined,'invalid.jwt'),req('GET','/users',undefined,t[0]),req('POST','/bookings/99999/check-in',{courtId:1},t[0])]);let s=x.map(v=>v.status);assert.deepEqual(s,[400,401,403,404]);let txt=x.map(v=>JSON.stringify(v.data)).join(' ');assert.ok(!/SQL syntax|SELECT .*FROM|stacktrace|password|at QueryRunner/i.test(txt));return `negative statuses=${s}, messages safe=${x.map(v=>String(v.data.message).slice(0,60)).join(' | ')}`});
await ck('TC_CONC_023',async()=>{let r=await fetch(root+'/courts/availability',{method:'OPTIONS',headers:{Origin:'https://untrusted.invalid','Access-Control-Request-Method':'GET'}});let h=r.headers.get('access-control-allow-origin');return `local OPTIONS from untrusted origin status=${r.status}, ACAO=${h}; deployed origin/policy unavailable`},true);
fs.writeFileSync(out,JSON.stringify({environment:{commit:require('node:child_process').execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),dbVolume:volume,at:new Date().toISOString()},results},null,2));console.log('EVIDENCE',out)}
main().catch(e=>{console.error('ABORT',e.message);process.exitCode=1}).finally(async()=>{if(db){try{await cleanupBookings();await db.query('DELETE FROM users_students WHERE stu_id IN (?,?)',ids);console.log('cleanup scoped fixtures')}finally{await db.end()}}});
