// Focused REQ-BOOK execution against the existing isolated QA MySQL only.
// Every created user and booking is removed by exact ID; no shared rows reset.
const assert=require('node:assert/strict');
const fs=require('node:fs');
const mysql=require('../backend/node_modules/mysql2/promise');
const {execFileSync}=require('node:child_process');
const volume='badminton_qa_20260928_mysql_data';
const root='http://127.0.0.1:4001';
const out='C:/GuisTee/Project_Y3/Book-a-Badminton/Book-a-Badminton_Court/testing/evidence/qa_book_api_results.json';
const date=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const yesterday=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(Date.now()-86400000));
const tomorrow=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(Date.now()+86400000));
const results=[]; const users=[];let db,seq=0;
const payload=(courtId=1,startTime='18:00',day=date)=>({courtId,date:day,startTime});
async function req(method,path,data,token){const r=await fetch(root+path,{method,headers:{...(data===undefined?{}:{'Content-Type':'application/json'}),...(token?{Authorization:'Bearer '+token}:{})},body:data===undefined?undefined:JSON.stringify(data)});return {status:r.status,data:await r.json().catch(()=>({}))}}
async function sql(q,p=[]){return(await db.query(q,p))[0]}
function status(r,v){assert.equal(r.status,v,`HTTP ${r.status}: ${String(r.data.message).slice(0,180)}`)}
async function student(){let n=String(76000000+Number(String(Date.now()).slice(-5))+ ++seq);let row=(await sql('SELECT COUNT(*) n FROM users_students WHERE stu_id=?',[n]))[0];assert.equal(row.n,0,`fixture collision ${n}`);let username='bookqa_'+n;let data={studentId:n,username,name:'Book QA '+n,email:`bookqa${n}@kmitl.ac.th`,phone:'0812345678',major:'IT',year:3,password:'QA-only-123!'};let r=await req('POST','/auth/register',data);status(r,201);users.push(n);return {id:n,username,token:r.data.access_token}}
async function booking(u,court=1,slot='18:00',day=date){return req('POST','/bookings',payload(court,slot,day),u.token)}
async function count(ids=users){if(!ids.length)return 0;return Number((await sql('SELECT COUNT(*) n FROM Booking WHERE stu_id IN (?)',[ids]))[0].n)}
async function clean(){if(!users.length)return;await sql('DELETE FROM Booking WHERE stu_id IN (?)',[users]);await sql('DELETE FROM users_students WHERE stu_id IN (?)',[users]);users.length=0}
async function check(id,fn,{partial=false}={}){try{let actual=await fn();results.push({id,status:partial?'ตรวจไม่ได้':'ผ่าน',actual:String(actual).slice(0,450)})}catch(e){results.push({id,status:'ไม่ผ่าน',actual:String(e.message).slice(0,450)})}finally{await clean()}console.log(id,results.at(-1).status,results.at(-1).actual)}
async function main(){
 assert.equal(process.env.QA_ISOLATED_DB,volume);assert.equal(process.env.DB_HOST,'127.0.0.1');assert.equal(process.env.DB_NAME,'badminton_db');
 assert.ok(execFileSync('docker',['inspect','--format','{{range .Mounts}}{{.Name}} {{end}}','badminton_mysql'],{encoding:'utf8'}).split(/\s+/).includes(volume));
 db=await mysql.createPool({host:'127.0.0.1',port:3306,user:process.env.DB_USER,password:process.env.DB_PASSWORD,database:'badminton_db',dateStrings:true});
 assert.equal((await sql('SELECT DATABASE() d'))[0].d,'badminton_db');
 assert.equal((await sql('SELECT COUNT(*) n FROM Booking'))[0].n,0,'QA Booking table not empty; preserve existing records');
 assert.equal((await req('GET','/courts/availability?date='+date)).status,200);
 await check('TC_BOOK_005',async()=>{let u=await student(),before=await count(),r=await booking(u,1,'10:00',tomorrow);status(r,400);assert.equal(r.data.message,'Day-by-day policy: You can only book courts for today.');assert.equal(await count(),before);return `tomorrow ${tomorrow}: 400 policy text; DB rows ${before}->${await count()}`});
 await check('TC_BOOK_022',async()=>{let u=await student(),seen=[];for(const v of ['10:30','ab:cd','24:00','25:99']){let r=await booking(u,1,v);seen.push(`${v}:HTTP${r.status} ${r.data.message}`)}assert.equal(await count(),0);assert.ok(seen.every(s=>s.includes('HTTP400 Invalid booking start time.')),seen.join(' | '));return seen.join(' | ')+'; no persisted rows'});
 await check('TC_BOOK_024',async()=>{let u=await student(),seen=[];for(const v of ['07:00','23:00']){let r=await booking(u,1,v);status(r,400);assert.equal(r.data.message,'Booking hours are 08:00 to 23:00.');seen.push(`${v}:${r.status}`)}assert.equal(await count(),0);return seen.join(', ')+'; expected message, no rows'});
 await check('TC_BOOK_009',async()=>{let u=await student();let r=await booking(u,1,'18:00');status(r,201);await sql('UPDATE Booking SET status=? WHERE booking_id=? AND stu_id=?',['COMPLETED',r.data.booking_id,u.id]);let second=await booking(u,2,'20:00');status(second,400);assert.match(second.data.message,/active booking/);assert.equal(await count(),1);return `COMPLETED fixture (set in QA DB, not cron), second booking 400 ${second.data.message}; 1 row`;},{partial:true});
 await check('TC_BOOK_011',async()=>{let a=await student(),b=await student(),first=await booking(a,1,'18:00');status(first,201);let r=await booking(b,1,'18:30');status(r,400);assert.match(r.data.message,/already booked|overlap/,`18:30 rejected as ${r.data.message}, not interval collision`);assert.equal(await count(),1);return 'partial overlap 18:30 rejected as overlap; one row'});
 await check('TC_BOOK_012',async()=>{let a=await student(),b=await student();status(await booking(a,1,'18:00'),201);let r=await booking(b,1,'19:00');status(r,201);let rows=await sql('SELECT stu_id,time_in,time_out FROM Booking WHERE stu_id IN (?) ORDER BY time_in',[users]);assert.equal(rows.length,2);assert.equal(rows[0].time_out,rows[1].time_in);return `two adjacent bookings; ${rows[0].time_in}-${rows[0].time_out} then ${rows[1].time_in}-${rows[1].time_out}`});
 await check('TC_BOOK_015',async()=>{let u=await student(),r=await booking(u,4,'22:00');status(r,201);let rows=await sql('SELECT time_in,time_out FROM Booking WHERE booking_id=? AND stu_id=?',[r.data.booking_id,u.id]);assert.equal(rows[0].time_in,'22:00:00');assert.equal(rows[0].time_out,'23:00:00');return 'API 201 Court 4 22:00-23:00; 15 UI slots not exercised here';},{partial:true});
 await check('TC_BOOK_016',async()=>{let a=await student(),b=await student(),first=await booking(a,1,'18:00');status(first,201);let cancel=await req('POST',`/bookings/${first.data.booking_id}/cancel`,{},a.token);status(cancel,201);let row=(await sql('SELECT status FROM Booking WHERE booking_id=?',[first.data.booking_id]))[0];assert.equal(row.status,'CANCELLED');let next=await booking(b,1,'18:00');status(next,201);return 'A 18:00 CANCELLED in time; B same court/time 201; status recorded in DB'});
 await check('TC_BOOK_020',async()=>{let u=await student(),r=await booking(u,3,'18:00');status(r,201);let [x]=await sql('SELECT stu_id,court,booking_date,time_in,time_out,status,admin_id FROM Booking WHERE booking_id=?',[r.data.booking_id]);assert.deepEqual([x.stu_id,x.court,x.booking_date,x.time_in,x.time_out,x.status,x.admin_id],[u.id,3,date,'18:00:00','19:00:00','PENDING','A001']);return `row bound to authenticated QA student ${u.id}; court=3 ${date} 18:00-19:00 PENDING admin=A001`});
 await check('TC_BOOK_023',async()=>{let a=await student(),b=await student(),c=await student();let first=await booking(a,1,'20:00:00');status(first,201);let collide=await booking(b,1,'20:00');status(collide,400);assert.equal(collide.data.message,'This court is already booked at this time.');let separate=await booking(c,2,'20:00');status(separate,201);let rows=await sql('SELECT time_in,time_out FROM Booking WHERE stu_id IN (?)',[users]);assert.equal(rows.length,2);assert.ok(rows.every(r=>r.time_in==='20:00:00'&&r.time_out==='21:00:00'));return '20:00:00 and 20:00 normalize to same interval; same-court collision 400, separate court 201'});
 await check('TC_BOOK_025',async()=>{let u=await student(),r=await booking(u,1,'10:00');status(r,400);assert.equal(r.data.message,'This booking round has already ended.');assert.equal(await count(),0);return `at ${new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Bangkok',hour:'2-digit',minute:'2-digit'}).format(new Date())} Thai, 10:00 -> 400 ended; no DB row`});
 await check('TC_BOOK_039',async()=>{let u=await student();await sql("INSERT INTO Booking(stu_id,court,booking_date,time_in,time_out,status,admin_id,created_at,updated_at) VALUES(?,1,?,'18:00:00','19:00:00','COMPLETED','A001',NOW(),NOW())",[u.id,yesterday]);let r=await booking(u,3,'18:00');status(r,201);let rows=await sql('SELECT booking_date,status FROM Booking WHERE stu_id=? ORDER BY booking_date',[u.id]);assert.deepEqual(rows.map(x=>x.booking_date),[yesterday,date]);return `yesterday COMPLETED (${yesterday}); today 18:00 Court 3 API 201`});
 await clean();fs.writeFileSync(out,JSON.stringify({environment:{databaseVolume:volume,commit:'37aea29',codeCommit:'581a654',caseCommit:'ed3bdca',date,at:new Date().toISOString(),cleanup:'all runner-created users/bookings removed'},results},null,2));console.log('EVIDENCE',out,results.reduce((m,x)=>(m[x.status]=(m[x.status]||0)+1,m),{}));
}
main().catch(e=>{console.error('ABORT',String(e.stack).slice(0,1600));process.exitCode=1}).finally(async()=>{if(db){try{await clean()}finally{await db.end()}}});
