// Fresh isolated-MySQL API evidence for REQ-ADMIN.
const assert=require('node:assert/strict'),fs=require('node:fs'),mysql=require('../backend/node_modules/mysql2/promise');
const {execFileSync}=require('node:child_process');
const api='http://127.0.0.1:4001',volume='badminton_qa_20260928_mysql_data',out='C:/GuisTee/Project_Y3/Book-a-Badminton/Book-a-Badminton_Court/testing/evidence/qa_admin_api_results.json';
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok'}).format(new Date());
const results=[],students=[],admins=[];let db,seq=0,adminToken;
async function sql(q,p=[]){return(await db.query(q,p))[0]}
async function req(method,path,data,token=adminToken){const r=await fetch(api+path,{method,headers:{...(data===undefined?{}:{'Content-Type':'application/json'}),...(token?{Authorization:'Bearer '+token}:{})},body:data===undefined?undefined:JSON.stringify(data)});return{status:r.status,data:await r.json().catch(()=>({}))}}
function status(r,s){assert.equal(r.status,s,`HTTP ${r.status}: ${r.data?.message||JSON.stringify(r.data)}`)}
async function student(prefix='admapi'){const id=String(80000000+Number(String(Date.now()).slice(-5))+ ++seq),username=`${prefix}_${id}`;const r=await req('POST','/auth/register',{studentId:id,username,name:`QA ${id}`,email:`${prefix}${id}@kmitl.ac.th`,phone:'0812345678',major:'IT',year:3,password:'QA-only-123!'},null);status(r,201);students.push(id);return{id,username,token:r.data.access_token}}
async function seed(u,{court=1,status='PENDING',date=today,start='21:00:00',end='22:00:00'}={}){return(await sql("INSERT INTO Booking(stu_id,court,booking_date,time_in,time_out,status,admin_id,created_at,updated_at) VALUES(?,?,?,?,?,?,'A001',NOW(),NOW())",[u.id,court,date,start,end,status])).insertId}
async function clean(){if(students.length){await sql('DELETE FROM Booking WHERE stu_id IN (?)',[students]);await sql('DELETE FROM users_students WHERE stu_id IN (?)',[students]);students.length=0}if(admins.length){await sql('DELETE FROM admin WHERE username IN (?)',[admins]);admins.length=0}}
async function check(id,fn,forced){try{results.push({id,status:forced||'ผ่าน',actual:String(await fn()).slice(0,900)})}catch(e){results.push({id,status:'ไม่ผ่าน',actual:String(e.message).slice(0,900)})}finally{await clean()}console.log(id,results.at(-1).status,results.at(-1).actual)}
async function main(){assert.equal(process.env.QA_ISOLATED_DB,volume);assert.ok(execFileSync('docker',['inspect','--format','{{range .Mounts}}{{.Name}} {{end}}','badminton_mysql'],{encoding:'utf8'}).split(/\s+/).includes(volume));db=await mysql.createPool({host:'127.0.0.1',user:process.env.DB_USER,password:process.env.DB_PASSWORD,database:'badminton_db',dateStrings:true});assert.equal((await sql('SELECT COUNT(*) n FROM Booking'))[0].n,0);let a=await req('POST','/auth/login',{username:'admin',password:'password'},null);status(a,201);adminToken=a.data.access_token;
 await check('TC_ADM_016',async()=>{const u1=await student('adm16a'),u2=await student('adm16b');const i1=await seed(u1,{court:1}),i2=await seed(u2,{court:2,status:'CANCELLED',start:'20:00:00',end:'21:00:00'});await seed(u1,{court:3,date:'2026-09-27',start:'19:00:00',end:'20:00:00'});const r=await req('GET',`/bookings?date=${today}`);status(r,200);assert.deepEqual(new Set(r.data.map(x=>x.booking_id)),new Set([i1,i2]));for(const row of r.data){assert.equal(row.booking_date,today);assert.ok(row.student?.username);assert.ok(['PENDING','CANCELLED'].includes(row.status))}return `dated Admin API returned exactly today's ${i1},${i2}, both users with student relation/status; excluded yesterday`});
 await check('TC_ADM_019',async()=>{const u=await student('adm19'),id=await seed(u,{status:'CHECKED_IN'});const rr=await Promise.all([req('POST',`/bookings/${id}/finish`,{}),req('POST',`/bookings/${id}/finish`,{})]);const statuses=rr.map(x=>x.status).sort();assert.deepEqual(statuses,[201,400],`concurrent finish statuses=${statuses.join(',')}`);assert.equal((await sql('SELECT status FROM Booking WHERE booking_id=?',[id]))[0].status,'COMPLETED');return `concurrent finish statuses=${statuses.join('/')}; final COMPLETED`});
 await check('TC_ADM_020',async()=>{const u=await student('adm20');await sql('UPDATE users_students SET strikes=1,banned_until=DATE_ADD(NOW(),INTERVAL 1 HOUR) WHERE stu_id=?',[u.id]);const id=await seed(u),courts=(await sql('SELECT COUNT(*) n FROM Court'))[0].n,usersBefore=(await sql('SELECT COUNT(*) n FROM users_students'))[0].n;const r=await req('POST','/bookings/reset',{});status(r,201);assert.equal((await sql('SELECT COUNT(*) n FROM Booking'))[0].n,0);const s=(await sql('SELECT strikes,banned_until FROM users_students WHERE stu_id=?',[u.id]))[0];assert.equal(s.strikes,1);assert.ok(s.banned_until);assert.equal((await sql('SELECT COUNT(*) n FROM Court'))[0].n,courts);assert.equal((await sql('SELECT COUNT(*) n FROM users_students'))[0].n,usersBefore);return `reset removed booking ${id} only; retained users=${usersBefore}, courts=${courts}, strikes=1 and banned_until`});
 await check('TC_ADM_021',async()=>{const dup=await req('POST','/users/admin',{admin_id:'A901',username:'admin',name:'Duplicate',password:'x'});const name=`adm_missing_${Date.now()}`,missing=await req('POST','/users/admin',{admin_id:'A902',username:name,name:'Missing Password'});if(missing.status===201)admins.push(name);assert.ok(dup.status>=400&&dup.status<500,`duplicate username returned HTTP ${dup.status}, expected 4xx`);assert.ok(missing.status>=400&&missing.status<500,`missing password created/returned HTTP ${missing.status}`);return `duplicate=${dup.status}, missing-password=${missing.status}; both rejected 4xx`});
 await check('TC_ADM_024',async()=>{const u=await student('adm24a'),b=await student('adm24b'),id=await seed(u,{court:1,status:'CHECKED_IN',start:'21:00:00',end:'22:00:00'});let f=await req('POST',`/bookings/${id}/finish`,{});status(f,201);let aTry=await req('POST','/bookings',{courtId:2,date:today,startTime:'22:00'},u.token),bTry=await req('POST','/bookings',{courtId:1,date:today,startTime:'21:00'},b.token);status(aTry,400);status(bTry,400);assert.match(aTry.data.message,/active booking/);assert.match(bTry.data.message,/already booked/);assert.equal((await sql('SELECT status FROM Booking WHERE booking_id=?',[id]))[0].status,'COMPLETED');return 'after Finish Early: A rebook HTTP 400 active quota; B same original slot HTTP 400 already booked; original remains COMPLETED'});
 await check('TC_ADM_026',async()=>{const name=`adm26_${Date.now()}`;let c=await req('POST','/users/admin',{admin_id:'A926',username:name,name:'QA No Password'});if(c.status===201)admins.push(name);assert.ok(c.status>=400&&c.status<500,`POST without password returned ${c.status}`);return `POST without password rejected HTTP ${c.status}`});
 await check('TC_ADM_028',async()=>{const u=await student('adm28'),id=await seed(u,{status:'COMPLETED'});const r=await req('DELETE',`/users/${u.id}`);const booking=(await sql('SELECT COUNT(*) n FROM Booking WHERE booking_id=?',[id]))[0].n,user=(await sql('SELECT COUNT(*) n FROM users_students WHERE stu_id=?',[u.id]))[0].n;assert.ok(r.status>=400&&r.status<500,`delete with booking returned HTTP ${r.status}: ${r.data?.message}`);assert.match(String(r.data?.message||''),/booking|history|reference|cannot/i,`unreadable reason: ${r.data?.message}`);assert.equal(booking,1);assert.equal(user,1);return `DELETE rejected ${r.status} with readable reason; booking/user retained`});
 await check('TC_ADM_029',async()=>{const survivor=await student('adm29s'),victim=await student('adm29v');let missing=await req('DELETE','/users/99999999'),first=await req('DELETE',`/users/${victim.id}`),again=await req('DELETE',`/users/${victim.id}`);assert.ok(missing.status<500&&first.status<500&&again.status<500,`${missing.status}/${first.status}/${again.status}`);assert.equal((await sql('SELECT COUNT(*) n FROM users_students WHERE stu_id=?',[survivor.id]))[0].n,1);students.splice(students.indexOf(victim.id),1);return `missing/first/repeated DELETE HTTP ${missing.status}/${first.status}/${again.status}; unrelated student retained`});
 await check('TC_ADM_033',async()=>{const a=await student('adm33a'),b=await student('adm33b'),id=await seed(a,{court:1,start:'21:00:00',end:'22:00:00'});const ops=await Promise.all([req('POST','/bookings/reset',{}),req('POST','/bookings',{courtId:2,date:today,startTime:'22:00'},b.token),req('POST',`/bookings/${id}/check-in`,{courtId:1},a.token)]);const rows=await sql('SELECT booking_id,stu_id,court,status FROM Booking WHERE stu_id IN (?)',[students]);for(const row of rows)assert.ok(students.includes(row.stu_id));assert.equal((await sql('SELECT COUNT(*) n FROM Booking b LEFT JOIN users_students s ON s.stu_id=b.stu_id WHERE s.stu_id IS NULL'))[0].n,0);const resetSaidSuccess=ops[0].status===201;if(resetSaidSuccess)assert.ok(rows.every(r=>r.booking_id!==id),'reset claimed success but original booking survived');return `simultaneous reset/create/check-in statuses=${ops.map(x=>x.status).join('/')}; final=${JSON.stringify(rows)}; no orphan rows; original removed when reset succeeded`});
 fs.writeFileSync(out,JSON.stringify({environment:{databaseVolume:volume,commit:'37aea29',at:new Date().toISOString(),cleanup:'only QA fixtures removed'},results},null,2));console.log('EVIDENCE',out,results.reduce((a,r)=>(a[r.status]=(a[r.status]||0)+1,a),{}));
}
main().catch(e=>{console.error('ABORT',e.stack);process.exitCode=1}).finally(async()=>{try{await clean()}catch{}if(db)await db.end().catch(()=>{})});
