// Focused browser/API QA for TC_BOOK_037, REQ-CANCEL, and REQ-CHECKIN.
// Runs only against the isolated QA MySQL volume and removes only its fixtures.
const {chromium}=require('C:/Users/TEE/AppData/Local/hermes/cache/scratch/qa-node/node_modules/playwright');
const mysql=require('../backend/node_modules/mysql2/promise');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {execFileSync}=require('node:child_process');
const base='http://localhost:3001', api='http://127.0.0.1:4001';
const volume='badminton_qa_20260928_mysql_data';
const out='C:/GuisTee/Project_Y3/Book-a-Badminton/Book-a-Badminton_Court/testing/evidence/qa_cancel_checkin_ui_results.json';
const shot='C:/GuisTee/Project_Y3/Book-a-Badminton/Book-a-Badminton_Court/testing/evidence/TC_CHK_001_admin_qr.png';
const camera='C:/Users/TEE/AppData/Local/hermes/cache/scratch/qr_court2.y4m';
const invalidCamera='C:/Users/TEE/AppData/Local/hermes/cache/scratch/qr_invalid.y4m';
const blankCamera='C:/Users/TEE/AppData/Local/hermes/cache/scratch/blank_camera.y4m';
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const yesterday=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(Date.now()-86400000));
const bangkokParts=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Bangkok',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date()).filter(x=>x.type!=='literal').map(x=>[x.type,Number(x.value)]));
const currentHour=bangkokParts.hour, currentMinute=bangkokParts.minute;
const liveHour=currentMinute>=45?currentHour+1:currentHour;
const liveStart=`${String(liveHour).padStart(2,'0')}:00:00`, liveEnd=`${String(liveHour+1).padStart(2,'0')}:00:00`;
const results=[], users=[];let db, browser, browserInvalid, browserBlank, browserDenied, seq=0;
async function sql(q,p=[]){return (await db.query(q,p))[0]}
async function req(method,path,data,token){const r=await fetch(api+path,{method,headers:{...(data===undefined?{}:{'Content-Type':'application/json'}),...(token?{Authorization:'Bearer '+token}:{})},body:data===undefined?undefined:JSON.stringify(data)});return {status:r.status,data:await r.json().catch(()=>({}))}}
function http(r,status){assert.equal(r.status,status,`HTTP ${r.status}: ${r.data?.message||JSON.stringify(r.data)}`)}
async function student(prefix='ccqa'){const id=String(78000000+Number(String(Date.now()).slice(-5))+ ++seq);const username=`${prefix}_${id}`;const name=`QA ${id}`;const r=await req('POST','/auth/register',{studentId:id,username,name,email:`${prefix}${id}@kmitl.ac.th`,phone:'0812345678',major:'IT',year:3,password:'QA-only-123!'});http(r,201);users.push(id);return {id,username,name,token:r.data.access_token}}
async function admin(){const r=await req('POST','/auth/login',{username:'admin',password:'password'});http(r,201);return {username:'admin',token:r.data.access_token}}
async function seed(u,{court=1,status='PENDING',date=today,start='22:00:00',end='23:00:00',created=new Date()}={}){const r=await sql('INSERT INTO Booking(stu_id,court,booking_date,time_in,time_out,status,admin_id,created_at,updated_at) VALUES(?,?,?,?,?,?,\'A001\',?,NOW())',[u.id,court,date,start,end,status,created]);return r.insertId}
async function cleanup(){if(!users.length)return;await sql('DELETE FROM Booking WHERE stu_id IN (?)',[users]);await sql('DELETE FROM users_students WHERE stu_id IN (?)',[users]);users.length=0}
async function check(id,fn,forced){try{const actual=await fn();results.push({id,status:forced||'ผ่าน',actual:String(actual).slice(0,700)})}catch(e){results.push({id,status:'ไม่ผ่าน',actual:String(e.message).slice(0,700)})}finally{await cleanup()}console.log(id,results.at(-1).status,results.at(-1).actual)}
async function newPage(b=browser,permissions=[]){const c=await b.newContext({viewport:{width:1440,height:900},permissions});const p=await c.newPage();p.setDefaultTimeout(18000);return p}
async function closePage(p){await p.context().close()}
async function goto(p,path,host=base){await p.goto(host+path,{waitUntil:'domcontentloaded'})}
async function hydrate(p,selector){await p.waitForFunction(s=>Object.keys(document.querySelector(s)||{}).some(k=>k.startsWith('__reactProps')),selector,{timeout:30000})}
async function login(p,u){await goto(p,'/login');await hydrate(p,'#username');await p.locator('#username').fill(u.username);await p.locator('#password').fill(u.username==='admin'?'password':'QA-only-123!');await p.locator('button[type=submit]').click();await p.waitForURL('**/dashboard',{timeout:30000})}
async function openScanner(p){await goto(p,'/scan');await p.getByText('Scan & Play').waitFor({timeout:30000});for(let i=0;i<8;i++){const request=p.getByText('Request Camera Permissions',{exact:false});if(await request.count()&&await request.first().isVisible().catch(()=>false)){await request.first().click();await p.waitForTimeout(500);continue}const start=p.getByText('Start Scanning',{exact:false});if(await start.count()&&await start.first().isVisible().catch(()=>false)){await start.first().click();await p.waitForTimeout(500);continue}const select=p.locator('#html5-qrcode-select-camera');if(await select.count()&&await select.isVisible().catch(()=>false)){const opts=await select.locator('option').count();if(opts>0)await select.selectOption({index:0});await p.waitForTimeout(300);continue}if(await p.locator('video').count())break;await p.waitForTimeout(400)}return p.locator('#qr-reader')}
async function adminCard(p,id){const ref=p.getByText(`REF: #BK-${id}`,{exact:true}).first();await ref.waitFor({timeout:30000});return ref.locator('xpath=ancestor::article')}
async function main(){
 assert.equal(process.env.QA_ISOLATED_DB,volume);assert.equal(process.env.DB_HOST,'127.0.0.1');assert.equal(process.env.DB_NAME,'badminton_db');
 const mounts=execFileSync('docker',['inspect','--format','{{range .Mounts}}{{.Name}} {{end}}','badminton_mysql'],{encoding:'utf8'});assert.ok(mounts.split(/\s+/).includes(volume));
 assert.ok(liveHour>=8&&liveHour<=22,`live QR test hour ${liveHour} is outside booking hours`);
 db=await mysql.createPool({host:'127.0.0.1',port:3306,user:process.env.DB_USER,password:process.env.DB_PASSWORD,database:'badminton_db',dateStrings:true});
 assert.equal((await sql('SELECT COUNT(*) n FROM Booking'))[0].n,0,'QA database must start with no bookings');
 const fakeArgs=file=>['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream',`--use-file-for-fake-video-capture=${file}`];
 browser=await chromium.launch({headless:true,args:fakeArgs(camera)});browserInvalid=await chromium.launch({headless:true,args:fakeArgs(invalidCamera)});browserBlank=await chromium.launch({headless:true,args:fakeArgs(blankCamera)});browserDenied=await chromium.launch({headless:true});

 await check('TC_BOOK_037',async()=>{const u=await student('book37'),p=await newPage();try{await login(p,u);let call=0,releaseFirst,secondSeen;const firstGate=new Promise(r=>releaseFirst=r),secondGate=new Promise(r=>secondSeen=r);const courts=(booked)=>[1,2,3,4].map(id=>({id,name:`Court ${id}`,description:'QA',status:'AVAILABLE',bookings:booked===id?[{start_time:booked===1?'18:00:00':'20:00:00',status:'PENDING'}]:[]}));await p.route('**/api/courts/availability**',async route=>{call++;if(call===1){await firstGate;await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(courts(1))})}else{await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(courts(2))});secondSeen()}});await goto(p,`/booking/select-court?date=${today}&time=18:00`);await p.waitForFunction(()=>location.search.includes('time=18'));await p.evaluate(({today})=>history.pushState(null,'',`/booking/select-court?date=${today}&time=20:00`),{today});await secondGate;await p.getByText(/20:00 - 21:00/).first().waitFor();releaseFirst();await p.waitForTimeout(800);assert.equal(call,2);assert.equal(await p.locator('.court-select-btn').nth(0).isEnabled(),true,'stale 18:00 response overwrote Court 1');assert.equal(await p.locator('.court-select-btn').nth(1).isDisabled(),true,'latest 20:00 response not retained for Court 2');return 'changed query 18:00→20:00 before first response; second response rendered Court 2 booked; delayed first response ignored; no stale overwrite'}finally{await closePage(p)}});

 await check('TC_CANC_001',async()=>{const u=await student('canc1'),id=await seed(u),p=await newPage();try{await login(p,u);await p.getByText('Upcoming Booking').waitFor();await p.getByRole('button',{name:/Cancel/}).click();const d=p.getByRole('dialog');await d.getByText(/ยืนยันการยกเลิก/).waitFor();const response=p.waitForResponse(r=>r.url().endsWith(`/api/bookings/${id}/cancel`));await d.getByRole('button',{name:/ยืนยันยกเลิก/}).click();assert.equal((await response).status(),201);await p.getByText(/ยกเลิกการจองสำเร็จ/).waitFor();const row=(await sql('SELECT status FROM Booking WHERE booking_id=?',[id]))[0],s=(await sql('SELECT strikes FROM users_students WHERE stu_id=?',[u.id]))[0];assert.equal(row.status,'CANCELLED');assert.equal(s.strikes,0);return `browser cancel confirmed; toast success; booking ${id}=CANCELLED; strikes=0`}finally{await closePage(p)}});
 await check('TC_CANC_010',async()=>{const u=await student('canc10');let a=await req('POST','/bookings',{courtId:1,date:today,startTime:'22:00'},u.token);http(a,201);let c=await req('POST',`/bookings/${a.data.booking_id}/cancel`,{},u.token);http(c,201);let me=await req('GET','/bookings/me',undefined,u.token);http(me,200);let row=me.data.find(x=>x.booking_id===a.data.booking_id);assert.equal(row.status,'CANCELLED');let b=await req('POST','/bookings',{courtId:2,date:today,startTime:'21:00'},u.token);http(b,201);return `GET /bookings/me includes ${a.data.booking_id}=CANCELLED; cancelled row does not consume active quota because rebook ${b.data.booking_id} succeeded HTTP 201`});
 await check('TC_CANC_011',async()=>{const u=await student('canc11'),p=await newPage();try{await login(p,u);await goto(p,'/booking');const modal=p.getByText('กฎและกติกาการใช้สนาม').locator('xpath=ancestor::div[contains(@class,"fixed")]');const text=await modal.innerText();assert.match(text,/ยกเลิกทันเวลา.*ก่อน 15 นาที/);assert.match(text,/ยกเลิกด้วยตนเองหลังเวลาผ่านไป 15 นาที.*ผิดกฎ 1 ครั้ง/);return 'booking rules modal visibly states timely-cancel deadline and one-strike late-cancel consequence'}finally{await closePage(p)}});
 await check('TC_CANC_012',async()=>{const u=await student('canc12'),id=await seed(u,{court:1,start:'18:00:00',end:'19:00:00'}),p=await newPage();try{await login(p,u);await p.getByRole('button',{name:/Cancel/}).click();const d=p.getByRole('dialog');const text=await d.innerText();for(const expected of ['Court 1',today,'18:00','ต้องยกเลิกก่อนครบ 15 นาที'])assert.ok(text.includes(expected),`cancel dialog missing ${expected}; actual=${text.replace(/\s+/g,' ')}`);return `dialog for ${id} contains court/date/time/deadline and can confirm`}finally{await closePage(p)}});
 await check('TC_CANC_016',async()=>{const u=await student('canc16'),id=await seed(u),p=await newPage();try{await login(p,u);let calls=0;await p.route('**/api/bookings/*/cancel',async route=>{calls++;if(calls===1)return route.fulfill({status:500,contentType:'application/json',body:'{"message":"QA simulated cancel failure"}'});return route.continue()});await p.getByRole('button',{name:/Cancel/}).click();let d=p.getByRole('dialog');await d.getByRole('button',{name:/ยืนยันยกเลิก/}).click();await p.getByText('QA simulated cancel failure').waitFor();assert.equal((await sql('SELECT status FROM Booking WHERE booking_id=?',[id]))[0].status,'PENDING');assert.equal(await d.isVisible(),true);await d.getByRole('button',{name:/ยืนยันยกเลิก/}).click();await p.getByText(/ยกเลิกการจองสำเร็จ/).waitFor();assert.equal((await sql('SELECT status FROM Booking WHERE booking_id=?',[id]))[0].status,'CANCELLED');return `first POST 500: error shown, dialog stayed retryable, DB PENDING; second POST succeeded, DB CANCELLED (calls=${calls})`}finally{await closePage(p)}});
 await check('TC_CANC_017',async()=>{const u=await student('canc17'),id=await seed(u),p=await newPage();try{await login(p,u);let posts=0;p.on('request',r=>{if(r.method()==='POST'&&r.url().endsWith(`/api/bookings/${id}/cancel`))posts++});await p.getByRole('button',{name:/Cancel/}).click();const d=p.getByRole('dialog');await d.getByRole('button',{name:/ปิด/}).click();await d.waitFor({state:'hidden'});const row=(await sql('SELECT status FROM Booking WHERE booking_id=?',[id]))[0],s=(await sql('SELECT strikes FROM users_students WHERE stu_id=?',[u.id]))[0];assert.equal(posts,0);assert.equal(row.status,'PENDING');assert.equal(s.strikes,0);return 'closed cancel dialog: POST count=0, booking remains PENDING, strikes=0'}finally{await closePage(p)}});

 await check('TC_CHK_001',async()=>{const u=await student('chk1'),id=await seed(u,{court:2,start:`${String(currentHour).padStart(2,'0')}:00:00`,end:'23:00:00'}),a=await admin(),p=await newPage();try{await login(p,a);const card=await adminCard(p,id);await card.click();const modal=p.getByText('Booking Telemetry').locator('xpath=ancestor::div[contains(@class,"fixed")]');const qr=modal.locator('svg[height="200"][width="200"]');await qr.waitFor();await qr.screenshot({path:shot});return `Admin dashboard opened booking ${id}/Court 2 and rendered 200x200 QR; screenshot=${shot}; decode verification follows`}finally{await closePage(p)}});
 await check('TC_CHK_002',async()=>{const u=await student('chk2'),id=await seed(u,{court:2,start:liveStart,end:liveEnd}),p=await newPage(browser,['camera']);try{let posts=0;p.on('request',r=>{if(r.method()==='POST'&&r.url().endsWith(`/api/bookings/${id}/check-in`))posts++});await login(p,u);await openScanner(p);await p.getByText('Check-in successful! Enjoy your game.').waitFor({timeout:30000});await p.waitForURL('**/dashboard');assert.equal((await sql('SELECT status FROM Booking WHERE booking_id=?',[id]))[0].status,'CHECKED_IN');assert.equal(posts,1);return `fake camera decoded real QR value 2; UI success toast and /dashboard redirect; DB ${id}=CHECKED_IN; POST count=1; server time inside allowed window for ${liveStart}`}finally{await closePage(p)}});
 await check('TC_CHK_005',async()=>{const u=await student('chk5'),id=await seed(u,{court:1,start:liveStart,end:liveEnd}),p=await newPage(browser,['camera']);try{await login(p,u);await openScanner(p);await p.getByText('You do not have a pending booking for this court right now.').waitFor({timeout:30000});assert.equal((await sql('SELECT status FROM Booking WHERE booking_id=?',[id]))[0].status,'PENDING');return `real QR camera decoded Court 2 while booking ${id} is Court 1; exact UI error shown; DB remains PENDING`}finally{await closePage(p)}});
 await check('TC_CHK_006',async()=>{const u=await student('chk6'),p=await newPage(browserInvalid,['camera']);try{await login(p,u);await openScanner(p);await p.getByText('Invalid QR Code. Please scan a valid court QR.').waitFor({timeout:30000});await p.waitForTimeout(800);const active=await p.locator('video').count();const retry=await p.getByText(/Request Camera Permissions|Start Scanning/, {exact:false}).count();assert.ok(active>0||retry>0,`invalid QR error appeared but scanner was cleared with no active video or retry control`);return `invalid URL QR rejected with exact message; scanner recoverable (video=${active}, retry=${retry})`}finally{await closePage(p)}});
 await check('TC_CHK_007',async()=>{const u=await student('chk7'),id=await seed(u,{court:2,status:'CANCELLED',start:liveStart,end:liveEnd}),p=await newPage(browser,['camera']);try{await login(p,u);await openScanner(p);await p.getByText('You do not have a pending booking for this court right now.').waitFor({timeout:30000});assert.equal((await sql('SELECT status FROM Booking WHERE booking_id=?',[id]))[0].status,'CANCELLED');return `cancelled booking ${id}; Court 2 QR produced no-pending error; status remained CANCELLED`}finally{await closePage(p)}});
 await check('TC_CHK_008',async()=>{const u=await student('chk8'),id=await seed(u,{court:2,start:liveStart,end:liveEnd}),p=await newPage(browser,['camera']);try{let posts=0;p.on('request',r=>{if(r.method()==='POST'&&r.url().endsWith(`/api/bookings/${id}/check-in`))posts++});await login(p,u);await openScanner(p);await p.waitForURL('**/dashboard',{timeout:30000});await p.waitForTimeout(1500);assert.equal(posts,1);assert.equal((await sql('SELECT status FROM Booking WHERE booking_id=?',[id]))[0].status,'CHECKED_IN');return 'continuous QR video generated exactly one check-in POST before scanner clear/navigation; DB CHECKED_IN'}finally{await closePage(p)}});
 await check('TC_CHK_009',async()=>{const u=await student('chk9'),id=await seed(u,{court:2,start:liveStart,end:'23:00:00'}),a=await admin(),p=await newPage();try{await login(p,a);const card=await adminCard(p,id);assert.match(await card.innerText(),/PENDING/);const start=Date.now(),r=await req('POST',`/bookings/${id}/check-in`,{courtId:2},u.token);http(r,201);await card.getByText('ACTIVE',{exact:true}).waitFor({timeout:10500});const elapsed=Date.now()-start;assert.ok(elapsed<=10500);return `Admin page stayed open; user API check-in 201; polling changed card PENDING→ACTIVE without reload in ${elapsed} ms`}finally{await closePage(p)}});
 await check('TC_CHK_010',async()=>{const u=await student('chk10'),id=await seed(u,{court:2,start:liveStart,end:'23:00:00'}),a=await admin(),p=await newPage();try{await login(p,a);const card=await adminCard(p,id);await card.click();await p.getByText('Booking Telemetry').waitFor();const r=await req('POST',`/bookings/${id}/check-in`,{courtId:2},u.token);http(r,201);await p.getByText('Live Session In Progress').waitFor({timeout:10500});const timer=p.locator('text=/^\\d{2}:\\d{2}:\\d{2}$/').first();await timer.waitFor();const first=await timer.innerText();await p.waitForTimeout(1200);const second=await timer.innerText();assert.notEqual(first,'--:--');assert.notEqual(first,second);return `open Admin modal updated after polling; CHECKED_IN state and countdown to time_out visible/ticking ${first}→${second}`}finally{await closePage(p)}});
 await check('TC_CHK_011',async()=>{const u=await student('chk11'),id=await seed(u,{court:2,status:'CHECKED_IN',start:liveStart,end:'23:00:00'}),a=await admin(),p=await newPage();try{await login(p,a);const card=await adminCard(p,id);await card.click();await p.getByText('Live Session In Progress').waitFor();p.once('dialog',d=>d.accept());const response=p.waitForResponse(r=>r.url().endsWith(`/api/bookings/${id}/finish`));await p.getByRole('button',{name:/Finish Early/}).click();assert.equal((await response).status(),201);await p.getByText('Booking finished successfully').waitFor();assert.equal((await sql('SELECT status FROM Booking WHERE booking_id=?',[id]))[0].status,'COMPLETED');return `Admin confirmed Finish Early; POST 201; exact success toast; DB ${id}=COMPLETED`}finally{await closePage(p)}});
 await check('TC_CHK_013',async()=>{const u=await student('chk13');const now=new Date();const hm=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Bangkok',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(now);let [h,m]=hm.split(':').map(Number);const end=`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:00`;const start=`${String(Math.max(0,h-1)).padStart(2,'0')}:${String(m).padStart(2,'0')}:00`;const id=await seed(u,{court:2,status:'CHECKED_IN',start,end});const t=Date.now();let status='CHECKED_IN';while(Date.now()-t<75000){await new Promise(r=>setTimeout(r,2000));status=(await sql('SELECT status FROM Booking WHERE booking_id=?',[id]))[0].status;if(status==='COMPLETED')break}assert.equal(status,'COMPLETED',`real scheduler did not complete booking within 75s; final=${status}`);return `seeded CHECKED_IN with past end ${end}; running Nest @Cron (EVERY_MINUTE) changed it to COMPLETED without API/UI in ${Date.now()-t} ms`});
 await check('TC_CHK_014',async()=>{const u=await student('chk14'),p=await newPage(browserDenied,[]);try{await login(p,u);await goto(p,'/scan');await p.getByText('Scan & Play').waitFor();const btn=p.getByText('Request Camera Permissions',{exact:false});if(await btn.count())await btn.first().click();await p.waitForTimeout(2500);const text=await p.locator('#qr-reader').innerText();assert.match(text,/permission|camera|notallowed|not found|ไม่อนุญาต/i,`no readable camera-permission/device guidance: ${text}`);assert.equal(new URL(p.url()).pathname,'/scan');return `headless browser with no camera permission/device stayed responsive on /scan and showed: ${text.replace(/\s+/g,' ').slice(0,220)}`}finally{await closePage(p)}},'ตรวจไม่ได้');
 await check('TC_CHK_020',async()=>{const u=await student('chk20'),id=await seed(u,{court:2,start:'22:00:00',end:'23:00:00'}),p=await newPage(browser,['camera']);try{await login(p,u);await p.clock.install({time:new Date(`${today}T22:05:00+07:00`)});await openScanner(p);await p.getByText('You cannot check in more than 15 minutes before the booking time starts.').waitFor({timeout:30000});assert.equal((await sql('SELECT status FROM Booking WHERE booking_id=?',[id]))[0].status,'PENDING');await sql('DELETE FROM Booking WHERE booking_id=?',[id]);const active=await seed(u,{court:2,status:'CHECKED_IN',start:'20:00:00',end:'21:00:00'});await p.clock.setFixedTime(new Date(`${today}T23:00:00+07:00`));await goto(p,'/dashboard');await p.getByText('Currently Playing').waitFor();await p.getByText('00:00',{exact:true}).waitFor();return `client clock spoofed to 22:05 but server rejected early check-in and DB stayed PENDING; separate CHECKED_IN ${active} with client clock after end displayed 00:00, not negative`}finally{await closePage(p)}});
 await check('TC_CHK_022',async()=>{const u=await student('chk22'),id=await seed(u,{court:2,start:liveStart,end:liveEnd}),p=await newPage(browser,['camera']);try{await login(p,u);await p.route('**/api/bookings/me',async route=>{await new Promise(r=>setTimeout(r,12000));await route.continue()});await openScanner(p);await p.getByText('You do not have a pending booking for this court right now.').waitFor({timeout:30000});await p.waitForTimeout(4000);assert.equal(new URL(p.url()).pathname,'/scan','scan before bookings loaded redirected away instead of keeping a loading/retry state');assert.equal((await sql('SELECT status FROM Booking WHERE booking_id=?',[id]))[0].status,'PENDING');return 'delayed bookings did not cause a permanent no-booking result; stayed on scan and can retry'}finally{await closePage(p)}});
 await check('TC_CHK_023',async()=>{const u=await student('chk23'),p=await newPage(browserBlank,['camera']);try{await login(p,u);await openScanner(p);await p.locator('video').waitFor({timeout:30000});await p.evaluate(()=>{window.__qaTrack=document.querySelector('video')?.srcObject?.getVideoTracks?.()[0]});await p.getByRole('button',{name:'Cancel'}).click();await p.waitForURL('**/dashboard');await p.waitForTimeout(500);const state=await p.evaluate(()=>window.__qaTrack?.readyState);assert.equal(state,'ended',`camera track after navigation=${state}`);await openScanner(p);await p.locator('video').waitFor({timeout:30000});assert.equal(await p.locator('#qr-reader').count(),1);return 'camera track readyState became ended after leaving /scan; returning created one scanner/video without duplicate DOM'}finally{await closePage(p)}});
 await check('TC_CHK_024',async()=>{const u=await student('chk24'),id=await seed(u,{court:2,start:liveStart,end:liveEnd}),p=await newPage(browser,['camera']);try{let posts=0;await p.route(`**/api/bookings/${id}/check-in`,async route=>{posts++;if(posts===1)return route.fulfill({status:500,contentType:'application/json',body:'{"message":"QA simulated check-in failure"}'});return route.continue()});await login(p,u);await openScanner(p);await p.getByText('QA simulated check-in failure').waitFor({timeout:30000});assert.equal((await sql('SELECT status FROM Booking WHERE booking_id=?',[id]))[0].status,'PENDING');await p.waitForURL('**/dashboard',{timeout:7000});await openScanner(p);await p.getByText('Check-in successful! Enjoy your game.').waitFor({timeout:30000});assert.equal((await sql('SELECT status FROM Booking WHERE booking_id=?',[id]))[0].status,'CHECKED_IN');assert.equal(posts,2);return 'first camera check-in POST 500: error shown and DB PENDING; after returning to scan, second QR attempt succeeded and DB CHECKED_IN'}finally{await closePage(p)}});
 await check('TC_CHK_026',async()=>{const a=await admin(),p=await newPage();try{await login(p,a);const mockBooking={booking_id:9026,court:1,booking_date:today,time_in:'10:00:00',time_out:'11:00:00',status:'PENDING',student:{first_name:'QA',last_name:'Rule',username:'qa-rule'}};await p.route('**/api/bookings',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify([mockBooking])}));await p.clock.install({time:new Date(`${today}T09:50:00+07:00`)});await goto(p,'/dashboard');const card=await adminCard(p,9026);await card.click();await p.getByText('Too Early for Check-in').waitFor();assert.equal(await p.locator('svg[height="200"][width="200"]').count(),0);return 'at 09:50 for 10:00 booking, Admin UI hides QR as Too Early although backend boundary evidence accepts check-in from 09:45; GAP-03 reproduced'}finally{await closePage(p)}},'ตรวจไม่ได้');
 await check('TC_CHK_028',async()=>{const u=await student('chk28');await seed(u,{court:1,date:yesterday,start:'18:00:00',end:'19:00:00'});await seed(u,{court:2,date:today,start:'20:00:00',end:'21:00:00'});const r=await req('GET','/courts/availability');http(r,200);const dates=[...new Set(r.data.flatMap(c=>(c.bookings||[]).map(b=>String(b.booking_date).slice(0,10))))];assert.deepEqual(dates,[today],`GET /courts/availability without date returned ${dates.join(', ')} instead of Thai today only (${today})`);return `availability without date filtered to Thai today ${today}`});

 fs.writeFileSync(out,JSON.stringify({environment:{databaseVolume:volume,branch:'feature-Docx',commit:'37aea29',date:today,at:new Date().toISOString(),browser:'Playwright Chromium headless; generated Y4M QR camera feeds',cameraHash:'67c4d1c2f00cbd50a4d5df6aeb3de0f3956b145743c187824cb5a47b11a6cbd3',cleanup:'only runner-created users/bookings removed'},results},null,2));
 console.log('EVIDENCE',out,results.reduce((a,r)=>(a[r.status]=(a[r.status]||0)+1,a),{}));
}
main().catch(e=>{console.error('ABORT',String(e.stack).slice(0,2200));process.exitCode=1}).finally(async()=>{try{await cleanup()}catch{}for(const b of [browser,browserInvalid,browserBlank,browserDenied])if(b)await b.close().catch(()=>{});if(db)await db.end().catch(()=>{})});
