const {chromium}=require('C:/Users/TEE/AppData/Local/hermes/cache/scratch/qa-node/node_modules/playwright');const assert=require('node:assert/strict'),fs=require('node:fs'),jwt=require('../backend/node_modules/jsonwebtoken'),{execFileSync}=require('node:child_process');
const root='http://localhost:3001',api='http://127.0.0.1:4001',out='C:/GuisTee/Project_Y3/Book-a-Badminton/Book-a-Badminton_Court/testing/evidence/qa_sec_browser_results.json',results=[];let browser;async function ck(id,fn,partial=false){try{let a=await fn();results.push({id,status:partial?'ตรวจไม่ได้':'ผ่าน',actual:String(a).slice(0,600)})}catch(e){results.push({id,status:'ไม่ผ่าน',actual:String(e.message).slice(0,600)})}console.log(id,results.at(-1).status,results.at(-1).actual)}
async function page(){let p=await browser.newPage({viewport:{width:1440,height:900}});p.setDefaultTimeout(13000);return p}
async function goto(p,path){await p.goto(root+path,{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>document.body?.innerText?.length>20,null,{timeout:18000})}
async function hydrate(p,s){await p.waitForFunction(x=>Object.keys(document.querySelector(x)||{}).some(k=>k.startsWith('__reactProps')),s,{timeout:18000})}
async function login(p){await goto(p,'/login');await hydrate(p,'#username');await p.locator('#username').fill('testuser');await p.locator('#password').fill('password');await p.locator('button[type=submit]').click();await p.waitForURL('**/dashboard',{timeout:20000})}
async function getToken(p){return p.evaluate(()=>localStorage.getItem('token'))}
async function main(){assert.equal(process.env.QA_ISOLATED_DB,'badminton_qa_20260928_mysql_data');assert.ok(execFileSync('docker',['inspect','--format','{{range .Mounts}}{{.Name}} {{end}}','badminton_mysql'],{encoding:'utf8'}).split(/\s+/).includes(process.env.QA_ISOLATED_DB));assert.equal((await fetch(api+'/courts/availability')).status,200);browser=await chromium.launch({headless:true});
await ck('TC_SEC_003',async()=>{let p=await page();try{await login(p);let old=await getToken(p),v=jwt.decode(old),expired=jwt.sign({sub:v.sub,username:v.username,role:v.role},'DO_NOT_USE_THIS_VALUE_IN_PROD',{expiresIn:-1});let x=await fetch(api+'/bookings/me',{headers:{authorization:'Bearer '+expired}});assert.equal(x.status,401);await p.evaluate(t=>{localStorage.setItem('token',t)},expired);await goto(p,'/dashboard');await p.waitForURL('**/login',{timeout:12000});assert.equal(await getToken(p),null);return 'expired signed JWT ->401, dashboard redirects /login and clears token'}finally{await p.close()}});
await ck('TC_SEC_011',async()=>{let p=await page();try{await login(p);const v=await p.evaluate(()=>Object.fromEntries(Object.entries(localStorage)));assert.deepEqual(Object.keys(v).sort(),['token','user']);assert.ok(!/password/i.test(JSON.stringify(v)));let u=JSON.parse(v.user);assert.ok(!('password' in u));return `localStorage keys=${Object.keys(v)}; user fields=${Object.keys(u).join(',')}; no password`}finally{await p.close()}});
await ck('TC_SEC_012',async()=>{let p=await page();try{await login(p);let redirects=0;p.on('framenavigated',f=>{if(f===p.mainFrame()&&new URL(f.url()).pathname==='/login')redirects++});await p.route('**/api/bookings/me',r=>r.fulfill({status:401,contentType:'application/json',body:'{"message":"Unauthorized"}'}));await goto(p,'/dashboard');await p.waitForURL('**/login',{timeout:12000});assert.equal(await getToken(p),null);assert.equal(await p.evaluate(()=>localStorage.getItem('user')),null);assert.ok(redirects<=2,`redirect count ${redirects}`);return `protected 401 clears token/user and redirects to login; navigation count=${redirects}`}finally{await p.close()}});
await ck('TC_SEC_013',async()=>{let p=await page();try{await goto(p,'/login');await hydrate(p,'#username');await p.evaluate(()=>{localStorage.setItem('token','QA_SENTINEL');localStorage.setItem('user','{"id":"QA"}')});await p.locator('#username').fill('testuser');await p.locator('#password').fill('wrong-test-password');await p.locator('button[type=submit]').click();await p.getByText(/Invalid credentials/i).waitFor({timeout:12000});assert.equal(await getToken(p),'QA_SENTINEL');return 'login 401 shows credentials error and does not clear existing storage; register 400 not exercised'}finally{await p.close()}},true);
await ck('TC_SEC_014',async()=>{let p=await page();try{await login(p);let token=await getToken(p);const request=async url=>p.evaluate(async u=>{const token=localStorage.getItem('token');try{return (await fetch(u,{headers:{authorization:'Bearer '+token}})).status}catch{return 0}},url);assert.equal(await request('/api/users'),403);assert.equal(await getToken(p),token);await p.route('**/api/bookings/me',r=>r.fulfill({status:500,body:'{"message":"QA 500"}'}));await goto(p,'/dashboard');await new Promise(r=>setTimeout(r,600));assert.equal(await getToken(p),token);await p.unroute('**/api/bookings/me');return '403 /users + mocked 500 /bookings/me did not clear token; network failure not exercised'}finally{await p.close()}},true);
await ck('TC_SEC_015',async()=>{let p=await page();try{await login(p);let old=await getToken(p);let newToken=old+'.QA_NEW_SESSION';let first;await p.route('**/api/bookings/me',async r=>{if(!first){first=r;return}await r.continue()});await p.evaluate(async()=>{const token=localStorage.getItem('token');fetch('/api/bookings/me',{headers:{authorization:'Bearer '+token}}).catch(()=>{})});await p.waitForFunction(()=>true);assert.ok(first,'old request did not start');await p.evaluate(t=>localStorage.setItem('token',t),newToken);await first.fulfill({status:401,contentType:'application/json',body:'{"message":"Unauthorized"}'});await new Promise(r=>setTimeout(r,700));assert.equal(await getToken(p),newToken);return 'old fetch 401 after replacing token kept new token; Axios interceptor path not exercised'}finally{await p.close()}},true);
await ck('TC_SEC_017',async()=>{let p=await page();try{let routes=['/dashboard','/booking','/booking/select-court?date=2026-09-28&time=18:00','/scan','/admin/users'];for(let path of routes){await goto(p,path);await p.waitForURL('**/login',{timeout:12000});let body=await p.locator('body').innerText();assert.ok(!body.includes('testuser')&&!body.includes('Court 1'),'PII leaked to guest')}return 'guest direct-open 5 protected routes -> /login without student/court details'}finally{await p.close()}});
await ck('TC_SEC_018',async()=>{let p=await page();try{await login(p);await goto(p,'/admin/users');await p.waitForURL('**/dashboard',{timeout:12000});let token=await getToken(p),r=await fetch(api+'/users',{headers:{authorization:'Bearer '+token}});assert.equal(r.status,403);return 'STUDENT /admin/users redirects dashboard; GET /users returns 403'}finally{await p.close()}});
await ck('TC_SEC_019',async()=>{let p=await page();try{await login(p);await p.evaluate(()=>{let u=JSON.parse(localStorage.getItem('user'));u.role='ADMIN';u.id='A001';localStorage.setItem('user',JSON.stringify(u))});let token=await getToken(p),r=await fetch(api+'/users',{headers:{authorization:'Bearer '+token}});assert.equal(r.status,403);return 'localStorage role/id forged ADMIN; backend GET /users still 403; booking owner override not exercised'}finally{await p.close()}},true);
await ck('TC_SEC_021',async()=>{let p=await page();try{await login(p);let alarms=0;p.on('dialog',d=>{alarms++;d.dismiss()});let payload='<script>alert(1)</script>teetest';await p.evaluate(t=>{let u=JSON.parse(localStorage.getItem('user'));u.name=t;localStorage.setItem('user',JSON.stringify(u))},payload);await p.reload();await new Promise(r=>setTimeout(r,500));assert.equal(alarms,0);assert.equal(await p.locator('script').filter({hasText:'alert(1)'}).count(),0);return 'localStorage display-name script payload did not execute on dashboard; persisted DB name/admin users not exercised'}finally{await p.close()}},true);
await ck('TC_SEC_025',async()=>{let p=await page();try{let urls=[],messages=[];p.on('request',r=>urls.push(r.url()));p.on('console',m=>messages.push(m.text()));await login(p);await goto(p,'/booking');let token=await getToken(p);assert.ok(!urls.some(u=>u.includes(token)),'token in URL');return `login+booking requests=${urls.length}: no token in URLs; console/backend logs need secure redacted review`}finally{await p.close()}},true);
await ck('TC_SEC_028',async()=>{let p=await page();try{await login(p);let token=await getToken(p);await p.getByRole('button',{name:'Menu'}).click();await p.getByRole('button',{name:/ออกจากระบบ/}).click();await p.waitForURL('**/login');assert.equal(await getToken(p),null);let r=await fetch(api+'/bookings/me',{headers:{authorization:'Bearer '+token}});return `logout clears browser session; old JWT replay HTTP ${r.status} (revocation policy not yet confirmed)`}finally{await p.close()}},true);
fs.writeFileSync(out,JSON.stringify({environment:{commit:'37aea29',dbVolume:process.env.QA_ISOLATED_DB,at:new Date().toISOString()},results},null,2));console.log('EVIDENCE',out)}
main().catch(e=>{console.error('ABORT',e.stack);process.exitCode=1}).finally(async()=>{if(browser)await browser.close()});
