// Real Chromium UI flows for AUTH_017, AUTH_032, CANC_017 on guarded isolated QA DB.
const assert=require('node:assert/strict'),fs=require('node:fs'),mysql=require('../backend/node_modules/mysql2/promise'),{execFileSync}=require('node:child_process');
const {chromium}=require('C:/Users/TEE/AppData/Local/hermes/cache/scratch/qa-node/node_modules/playwright');
const {fillWhenHydrated}=require('./login_helper.cjs');
const base='http://localhost:3001',api='http://127.0.0.1:4001',volume='badminton_qa_20260928_mysql_data',commit=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),stamp=new Date().toISOString().replace(/[:.]/g,'-'),out=`testing/evidence/qa_real_auth_cancel_ui_${stamp}.json`,results=[],fixtures=[],net={};let db,browser;
const sql=async(q,p=[])=>{const [r]=await db.query(q,p);return r}, safe=(s)=>String(s||'').replace(/password[^,\s]*/ig,'password=[redacted]').slice(0,350);
async function snap(page,id){await page.screenshot({path:`testing/evidence/${id}_${stamp}.png`,fullPage:true})}
async function open(page,path){await page.goto(base+path,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>document.body?.innerText?.length>30,{timeout:20000});await page.waitForFunction(()=>!document.querySelector('[aria-busy="true"]'),{timeout:25000}).catch(()=>{});await page.waitForTimeout(400)}
async function login(page,user,pw){await open(page,'/login');await fillWhenHydrated(page,'#username',user,'#password',pw);const post=page.waitForResponse(r=>r.url().endsWith('/api/auth/login')&&r.request().method()==='POST');await page.locator('button[type=submit]').click();const r=await post;if(!r.ok())throw Error(`login HTTP ${r.status()}`);await page.waitForURL('**/dashboard',{timeout:20000});}
async function register(page,p){await open(page,'/register');await page.locator('#studentId').fill(p.id);await page.locator('#name').fill(p.name);await page.locator('#email').fill(`${p.username}@kmitl.ac.th`);await page.locator('#phone').fill('0812345678');await page.locator('#major').fill('IT');await page.locator('#year').selectOption('3');await page.locator('#username').fill(p.username);await page.locator('#password').fill(p.password);const post=page.waitForResponse(r=>r.url().includes('/api/auth/register')&&r.request().method()==='POST');await page.locator('button[type=submit]').click();const r=await post;if(!r.ok())throw Error('register HTTP '+r.status()+' '+await r.text());await page.waitForURL('**/dashboard',{timeout:20000});}
async function create(prefix,name='Fixture QA'){const id=String(7700000+Number(String(Date.now()).slice(-5))%100000+fixtures.length),username=prefix+id+'x'+Math.random().toString(36).slice(2,7),password='QAonly!pass123',p={id,username,password,name};const [r]=await fetch(api+'/auth/register',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({studentId:id,username,name,email:`${username}@kmitl.ac.th`,phone:'0812345678',major:'IT',year:3,password})}).then(async r=>[r]);assert.equal(r.status,201,'isolated fixture registration');fixtures.push(id);return p}
async function run(id,fn){try{const actual=await fn();results.push({id,status:'PASS',actual});console.log(id,'PASS',actual)}catch(e){results.push({id,status:'FAIL',actual:safe(e.message)});console.log(id,'FAIL',safe(e.message))}}
(async()=>{try{
 const mounts=JSON.parse(execFileSync('docker',['inspect','badminton_mysql','--format','{{json .Mounts}}'],{encoding:'utf8'}));assert.ok(mounts.some(m=>m.Type==='volume'&&m.Name===volume&&m.Destination==='/var/lib/mysql'),'QA external volume guard');
 db=await mysql.createPool({host:'127.0.0.1',port:13306,user:'badminton_user',password:'password',database:'badminton_db',dateStrings:true});assert.equal(Number((await sql('SELECT COUNT(*) n FROM Booking'))[0].n),0,'DB must be empty before isolated fixture run');
 browser=await chromium.launch({headless:true});
 await run('TC_AUTH_017',async()=>{const p=await browser.newPage({viewport:{width:1440,height:900}}),f={id:'7777788',username:'thaiui'+Date.now(),password:'QAonly!pass123',name:'  สมชาย ใจดี  '};fixtures.push(f.id);const registrations=[];p.on('response',r=>{if(/\/api\/auth\/register$/.test(r.url()))registrations.push(r.status())});try{await register(p,f);assert.equal(registrations.at(-1),201,'register POST observed');const user=JSON.parse(await p.evaluate(()=>localStorage.getItem('user')));assert.match(user.name,/สมชาย\s+ใจดี/);const row=(await sql('SELECT first_name,last_name FROM users_students WHERE stu_id=?',[f.id]))[0];assert.deepEqual([row.first_name,row.last_name],['สมชาย','ใจดี']);await snap(p,'TC_AUTH_017_dashboard');await open(p,'/admin/users');await p.waitForTimeout(700);const text=await p.locator('body').innerText();assert.ok(text.includes('สมชาย')&&text.includes('ใจดี'),'name shown in admin users UI');await snap(p,'TC_AUTH_017_admin_users');return `Chromium register submitted HTTP ${registrations.at(-1)}; dashboard user displays ${user.name}; DB first/last=${row.first_name}/${row.last_name}; admin users page displays both Thai name parts`}finally{await p.close()}});
 await run('TC_AUTH_032',async()=>{const p=await browser.newPage({viewport:{width:1440,height:900}}),a=await create('acctA'),b=await create('acctB');try{await login(p,a.username,a.password);await open(p,'/dashboard');const tokenA=await p.evaluate(()=>localStorage.getItem('token'));assert.ok(tokenA);await sql("INSERT INTO Booking(stu_id,court,booking_date,time_in,time_out,status,admin_id,created_at,updated_at) VALUES(?,1,DATE_FORMAT(DATE_ADD(CURDATE(),INTERVAL 1 DAY),'%Y-%m-%d'),'18:00','19:00','PENDING','A001',NOW(),NOW())",[a.id]);await p.reload();await p.waitForTimeout(500);const bodyA=await p.locator('body').innerText();assert.ok(bodyA.includes(a.id)||bodyA.includes(a.username)||bodyA.includes('Court 1'),'A data visible on A dashboard');await p.getByRole('button',{name:'Menu'}).click();await p.getByRole('button',{name:/ออกจากระบบ/}).click();await p.waitForURL('**/login');assert.equal(await p.evaluate(()=>localStorage.getItem('token')),null);await login(p,b.username,b.password);const tokenB=await p.evaluate(()=>localStorage.getItem('token'));assert.ok(tokenB&&tokenB!==tokenA,'B session differs');const me=await fetch(api+'/bookings/me',{headers:{Authorization:`Bearer ${tokenB}`}}).then(r=>r.json());assert.ok(Array.isArray(me)&&me.length===0,'B sees no A booking');await open(p,'/dashboard');const bodyB=await p.locator('body').innerText();assert.ok(!bodyB.includes(a.id),'A identifier not leaked in B dashboard');await snap(p,'TC_AUTH_032_account_B');return `same Chromium context logout/login A→B; token changed, B /bookings/me=${me.length}; B dashboard omits A student ID`}finally{await p.close()}});
 await run('TC_CANC_017',async()=>{const p=await browser.newPage({viewport:{width:1440,height:900}}),f=await create('cancelui');try{const [ins]=await db.query("INSERT INTO Booking(stu_id,court,booking_date,time_in,time_out,status,admin_id,created_at,updated_at) VALUES(?,1,DATE_ADD(CURDATE(),INTERVAL 1 DAY),'18:00','19:00','PENDING','A001',NOW(),NOW())",[f.id]);const bid=ins.insertId;await login(p,f.username,f.password);await open(p,'/dashboard');await p.waitForTimeout(1000);await p.getByRole('button',{name:/Cancel/}).first().click();await p.getByText('ยืนยันการยกเลิกจองคอร์ท (Cancel Booking)').waitFor();await snap(p,'TC_CANC_017_dialog');let posts=0;p.on('request',r=>{if(r.method()==='POST'&&/cancel/i.test(r.url()))posts++});const close=p.getByRole('button',{name:/ปิดหน้าต่าง \(Close\)/});if(await close.count())await close.click();else{const dialog=p.getByRole('dialog');await p.mouse.click(50,400);await dialog.waitFor({state:'detached'});}await p.waitForTimeout(500);const row=(await sql('SELECT status FROM Booking WHERE booking_id=?',[bid]))[0],body=await p.locator('body').innerText();assert.equal(posts,0,'no cancel POST');assert.equal(row.status,'PENDING');assert.ok(!body.includes('ยกเลิกการจองสำเร็จ'),'no success message');await snap(p,'TC_CANC_017_closed');return `real cancel dialog opened then closed without confirmation; cancel POSTs=${posts}; DB status=${row.status}; no success toast`}finally{await p.close()}});
 }catch(e){console.error('RUN ABORT',safe(e.stack));results.push({id:'RUN_GUARD',status:'BLOCKED',actual:safe(e.message)})}finally{if(db&&fixtures.length){await sql('DELETE FROM Booking WHERE stu_id IN (?)',[fixtures]);await sql('DELETE FROM users_students WHERE stu_id IN (?)',[fixtures])}let remaining=null;if(db)remaining=Number((await sql('SELECT COUNT(*) n FROM Booking'))[0].n);const doc={environment:{frontend:base,api,dbVolume:volume,commit,at:new Date().toISOString(),browser:'Playwright Chromium '+(browser?browser.version():'not launched'),fixtureCleanup:'deleted only created student IDs and associated bookings'},results,cleanup:{remainingBookings:remaining}};fs.writeFileSync(out,JSON.stringify(doc,null,2));console.log('EVIDENCE',out,results,`remainingBookings=${remaining}`);if(browser)await browser.close();if(db)await db.end();if(results.filter(x=>x.status==='PASS').length!==3)process.exitCode=1;}})();
