from pathlib import Path
import json
root=Path('.')
section='''\n## 2026-10-01 pending API 17-case regression closeout\n- Incorporated parent batch `testing/evidence/qa_pending_api_batch_2026-10-01T02-24-08-926Z.json` into the workbook, then reran against the rebuilt backend and updated the same 17 requirement rows from fresh evidence `testing/evidence/qa_pending_api_batch_2026-10-01T02-32-31-566Z.json`: **17/17 PASS**. The first fresh attempt reported AUTH_011 FAIL because its evidence regex incorrectly escaped literal `$`; fixed the runner assertion (not product behavior), reran successfully. API subchecks remain supplemental and are not counted as full test cases.\n- Backend fixes: registration now requires a nonblank password, a syntactically valid `@kmitl.ac.th` email, and an 8-digit student ID (length/shape enforced by the existing varchar(8) student-ID contract); new student passwords are bcrypt hashed with no `password` fallback. Login rejects non-string/missing username/password as generic 401 without repository query. `/users` removes password properties. Booking rejects non-integer/invalid or nonexistent court IDs before booking transaction/persistence. Existing stored legacy plaintext password records are not mass-migrated or rewritten; login comparison remains backward-compatible for legacy rows while new registrations are hashed.\n- Regression verification: full backend Jest **11 suites / 24 tests PASS**. Rebuilt isolated QA backend image `sha256:0c4da5a293918daf17d484ae7ff83b34afa962e2cf84211abb1daeec2f0e0a36`; live API batch verified source hashes against image, exact MySQL volume `badminton_qa_20260928_mysql_data`, and cleanup `remainingBookings=0`, `remainingBatchStudents=0`, `remainingBatchAdmins=0`.\n- Workbook `testing/Test_Case_Book-a-Badminton_Court_Results_20261001_feature-Docx_QA.xlsx` updated in canonical requirement sheets and new `25_Pending_API_20261001` evidence sheet; 271 unique requirement IDs now count **56 ผ่าน / 11 ไม่ผ่าน / 46 ตรวจไม่ได้ / 158 รอทดสอบ**. (Supplemental subchecks are not added to the requirement count.)\n- Source HEAD remains `60a23c800d56a4f012cdead21adf4ab3f38d0e82`; worktree dirty/uncommitted. No commit or push. Existing workbook metadata and DOCX remain draft; physical QR/camera flow remains untested.\n'''
p=root/'testing/QA_API_PROGRESS_20261001_TH.md'; p.write_text(p.read_text(encoding='utf-8')+section,encoding='utf-8')
p=root/'testing/PROGRESS_CHECKPOINT.md'; p.write_text(p.read_text(encoding='utf-8')+'\n'+section,encoding='utf-8')
j=root/'testing/PROGRESS_CHECKPOINT.json'; d=json.loads(j.read_text(encoding='utf-8'))
d['updated']='2026-10-01T02:32:31+07:00';d['source_commit']='60a23c800d56a4f012cdead21adf4ab3f38d0e82';d['image']='sha256:0c4da5a293918daf17d484ae7ff83b34afa962e2cf84211abb1daeec2f0e0a36'
d['unit']={'command':'cd backend && npm test -- --runInBand','suites':11,'tests':24,'status':'PASS'}
d['pending_api_batch']={'path':'testing/evidence/qa_pending_api_batch_2026-10-01T02-32-31-566Z.json','cases':17,'passed':17,'failed':0,'cleanup':{'remainingBookings':0,'remainingBatchStudents':0,'remainingBatchAdmins':0},'volume':'badminton_qa_20260928_mysql_data'}
d['workbook']={'path':'testing/Test_Case_Book-a-Badminton_Court_Results_20261001_feature-Docx_QA.xlsx','cases':271,'pending':158,'pass':56,'unable':46,'fail':11}
d['notes']=['No push or commit','DOCX remains draft','Legacy plaintext account passwords were not mass-migrated; legacy login comparison retained; new registration hashes passwords.','Supplemental API subchecks are not counted as full test cases.','Physical QR/camera flow not tested.']
j.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(json.dumps({'updated':[str(root/'testing/QA_API_PROGRESS_20261001_TH.md'),str(root/'testing/PROGRESS_CHECKPOINT.md'),str(j)],'batch':d['pending_api_batch'],'workbook':d['workbook']},ensure_ascii=False))